### ISSUE TITLE
custom component

### ISSUE THREAD

**Issue by gavieritei** [formio/angular-formio#101]
Hi,
You have [here](https://help.form.io/userguide/form-components/#custom) an example on how to create a custom component.

I've done this in angularjs and it works (using the example), but how can you register the component in angular2? 

Basically I can register the new type in the builder, build a form, but I need to be able to render it in an  angular2 app. Otherwise I'd have the **Unknown component:** message

I've see the Render Resource example, but can I do the same with a custom component?

Thanks!

**Comment by rmckeel** [comment]
@gavieritei Wondering if you have found a way since to have a custom component?  I just came to realize ng2-formio does not have the file component (nor does formio.js), so it seems ngFormio is the way to go if you want file upload behaviors.

**Comment by gavieritei** [comment]
I've managed only to lookup the problem but not solve it itself (due to other priorities in my projects).
The problem is with the way the components are registered [here](https://github.com/formio/formio.js/blob/master/src/components/index.js) and the check in the create function.
But this is in js code not in angular2 code, and I don't know of an easy solution to extend that. (I'm not that experienced in js at this time).

**Comment by gowthaman-i2i** [comment]
@gavieritei @rmckeel  I'm also facing the same problem.Anyone have solution for this

**Comment by rmckeel** [comment]
@gowthaman-i2i Is your issue specific to a file upload component, or some other custom component you want to build?

I didn't get very far on custom NG2 components (we decided to stick to AngularJS version).  However, I do remember a Formio message that they released a file component for NG2.

**Comment by travist** [comment]
I just created some examples of a custom component in Angular. You can see it in the Angular Demo application @ https://github.com/formio/angular-demo.

Here is the custom component.

https://github.com/formio/angular-demo/blob/master/src/app/components/CheckMatrix.js

And here is how you register it within your application.

https://github.com/formio/angular-demo/blob/master/src/app/app.module.ts#L19

Hope this helps.
