### ISSUE TITLE
Change in FormJson dynamically doesn't update Form

### ISSUE THREAD

**Issue by anikets43** [formio/angular-formio#116]
Hi, 

I modified the ng2-formio start kit and added a button to update the form schema json.
`  <button class="btn btn-primary" (click)="addControl()"> Add Control </button>
`

`addControl() {
    var data = {
      'type': 'textfield',
      'input': true,
      'tableView': true,
      'inputType': 'text',
      'inputMask': '',
      'label': 'Last Name',
      'key': 'lastName',
      'placeholder': 'Enter your last name',
      'prefix': '',
      'suffix': '',
      'multiple': false,
      'defaultValue': '',
      'protected': false,
      'unique': false,
      'persistent': true,
      'validate': {
        'required': true,
        'minLength': 2,
        'maxLength': 10,
        'pattern': '',
        'custom': '',
        'customPrivate': false
      },
      'conditional': {
        'show': '',
        'when': null,
        'eq': ''
      }
    };

    this.formJson.components.push(data);
  };`

It doesn't update the form dynamically. Am I missing anything??

Thanks,
Aniket

**Comment by ens121** [comment]
I have the same question. Looking for a way to refresh or reload the component and formio angular documentation does not seem to provide this information.

**Comment by travist** [comment]
You can include an event emitter as an input to the ```refresh``` property like so.

```
<formio [refresh]="triggerRefresh" ....></formio>
```

Then in your controller do the following.

```ts
this.triggerRefresh = new EventEmitter();

this.triggerRefresh.emit();
```

**Comment by ens121** [comment]
Is this documented anywhere? I am having this problem with the Angular 1.x version and the above does not work for me. I realize this is the angular 4 project so maybe the above code only works with 4.

**Comment by roshank92** [comment]
Hi This is worked for me 

   ` triggerRefresh:any;
`
```

ngOnInit() {

        this.triggerRefresh = new EventEmitter();
}
```

Call function whenever object changes
change(){
```
this.triggerRefresh.emit({
            property: 'form',
            value: this.formData
        });
}
```

**Comment by rohitsiddha** [comment]
Hi @travist, I'm using onChange eventListener on form as follows- 
```
<formio [form]="formInput" (change)="onChange($event)" [refresh]="triggerRefresh"></formio>

Here is the component.ts file ->

@Input() formInput: any;

ngOnChanges(changes) {
    if (this.formInput) {
      this.changeForm();
   }
}

ngOnInit() {
    this.triggerRefresh = new EventEmitter();
}

changeForm () {
    this.triggerRefresh.emit({
      property: 'form',
      value: this.formInput
    });
}
onChange(event) {
    console.log(event);
}
```
When I change the value of `formInput`, form on the UI updates with the new data. However, event.data in the onChange function contains values for the previous form as well.
How to reset it to the new form?

Thanks

**Comment by ahka01** [comment]
Hi @rohitsiddha,
This link should help how to do it for submissions: https://github.com/formio/angular-formio/wiki/Form-Renderer#updating-forms-and-submissions

**Comment by rohitsiddha** [comment]
@ahka01 , Thanks for the reply.
The problem isn't with updating the form and submission data. It works as expected.
I'm talking about the form change event callback. If you inspect the object you get when form change event triggers, you'll see previous as well as new form submission keys in the data object.
