### ISSUE TITLE
submit & date/time component problem

### ISSUE THREAD

**Issue by gavieritei** [formio/angular-formio#120]
Use case:
I have a form with multiple fields of all types.

Date/time component is received at submit even though it was not completed by the user.
The submit seems to trigger it somehow, and the date/time component is received as current time.

This does not seem to happen in ngFormBuilder but it does happen in ng2-formio.

Thanks for all the hard work!

**Comment by methanome** [comment]
I have the same problem, datetime field filled with the current date when left empty while submitting, making it impossible to submit an empty date when the date is not required.
I appreciate the help.

**Comment by gavieritei** [comment]
Did anyone manage to find a workaround/fix for this?

**Comment by beniaminp** [comment]
I have the same problem, there is a fix for this?

Thank you!

**Comment by VladRM** [comment]
Hi, is there a fix or at least a workaround for this?
Any input would be appreciated.

**Comment by travist** [comment]
This should be fixed with the latest version. Will you confirm that it is still a problem with the latest version of this library?

**Comment by VladRM** [comment]
Thank you, travist, for the quick reply and for contributing to this awesome project.

Will check with the latest and get back to you.

**Comment by VladRM** [comment]
I confirm this issue is fixed in the latest version (2.24.0).
Thanks again!
