### ISSUE TITLE
rc.34 --prod compilation breaks even though rc.33 works

### ISSUE THREAD

**Issue by mikethm** [formio/angular-formio#122]
rc.33 compiles with --prod (aot)
however, rc.34 has an error

```
Error: Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function 
            calls are not supported. Consider replacing the function or lambda with a reference to an exported function, 
            resolving symbol Injectable in 
            ng2-formio/node_modules/@angular/core/core.d.ts, 
            resolving symbol FormioAppConfig in 
            ng2-formio/src/formio.config.d.ts, resolving symbol 
            FormioAppConfig in 
           ng2-formio/src/formio.config.d.ts 
```

**Comment by travist** [comment]
That may be because of the upgrade to TypeScript. Try downgrading the typescript to 2.3.4 and let me know if that works.

**Comment by mtsang** [comment]
changing the version back down avoided that error, however, confirmed working versions of typescript that compile for rc33 (2.3,2.2)  fails with rc-34  with the same error each time:

[00:33:54]  Error: ./~/formiojs/build/components/base/Base.js Module not found: Error: Can't resolve 
            'text-mask-all/vanilla'

**Comment by travist** [comment]
I think this may now work with the >1.0.0 releases. Let me know otherwise.
