### ISSUE TITLE
compile issue for 1.0.1

### ISSUE THREAD

**Issue by mikethm** [formio/angular-formio#131]
Congrats on 1.x release! 
However, I seem to get an error on compilation

[12:10:45]  Error: ./node_modules/formiojs/dist/formio.form.min.css Module parse failed: 
            node_modules/formiojs/dist/formio.form.min.css Unexpected token 
            (1:0) You may need an appropriate loader to handle this file type. | .flatpickr-calendar{background:0 
            0;overflow:hidden;max-height:0;opacity:0;visibility:hidden;text-align:center;padding:0;-webkit-animation:none;animation:none;direction:ltr;border:0;font-size:14px;line-height:24px;border-radius:5px;position:absolute;width:307.875px;-webkit-box-sizing:border-box;box-sizing:border-box;-ms-touch-action:manipulation;touch-action:manipulation;background:#fff;-webkit-box-shadow:1px
...

@ ./node_modules/angular-formio/formio.component.js 225:29-73
 @ ./src/pages/survey-entry/survey-entry.ngfactory.js
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts

**Comment by travist** [comment]
So, are you just trying to run this repo with ```npm start```? I updated https://github.com/formio/angular-app-starterkit with this version and am not getting that error. It may help to know the environment you are running into this issue.

**Comment by mikethm** [comment]
ionic application.
typescript 2.4.2
npm run ionic:build --prod

**Comment by travist** [comment]
that would be awesome. thanks.

**Comment by mikethm** [comment]
git clone https://github.com/mikethm/issue-1.git
npm i
npm run ionic:build --prod

**Comment by travist** [comment]
This should be fixed in version ```1.2.0```. Thanks.
