### ISSUE TITLE
You must provide an AppConfig within your application!

### ISSUE THREAD

**Issue by krixerx** [formio/angular-formio#133]
I get a warning in console:
"You must provide an AppConfig within your application!"

How to provide AppConfig?

Thanks!
Erki

**Comment by krixerx** [comment]
Solution:
1) create empty configuration file "formio-config.ts" with content:
export const AppConfig = {

};

2) add import to "app.module.ts":
import {AppConfig} from '../formio-config';

3) add provider (providers section) to "app.module.ts":
{provide: FormioAppConfig, useValue: AppConfig}

4) import FormioAppConfig in  "app.module.ts":
import {FormioModule, FormioAppConfig} from 'angular-formio';

**Comment by binury** [comment]
@krixerx This workaround breaks the form builder

**Comment by Marc-Hoch** [comment]
I have the same problem. Does anyone have a solution? When I add the empty config, the form builder no longer works.

**Comment by binury** [comment]
> I have the same problem. Does anyone have a solution? When I add the empty config, the form builder no longer works.

Create a valid config

**Comment by Marc-Hoch** [comment]
okay, but I don't use the formio backend service. Do you use the formio service? Or what valid data have you entered?

**Comment by hbaldwinRPT** [comment]
i also havethis issue using angular formio with my own custom backend

**Comment by hbaldwinRPT** [comment]
@Marc-Hoch 
`
import { FormioAppConfig } from "@formio/angular"

export const AppConfig: FormioAppConfig = {
    appUrl:'',
    apiUrl: 'api',
}
`

**Comment by hbaldwinRPT** [comment]
`import { FormioAppConfig } from "@formio/angular"

export const AppConfig: FormioAppConfig = {
    appUrl:'',
    apiUrl: 'api',
}`

@Marc-Hoch

**Comment by simionato-ennovaresearch** [comment]
Is it really needed to provide an AppConfig?

**Comment by edwinanciani** [comment]
@simionato-ennovaresearch Is not required, but is recommended. The AppConfig helps the Formio instance to be in context with the API server and Project. I used for Formio Services in the Angular Library, to get forms, save submissions, auth etc.

**Comment by simionato-ennovaresearch** [comment]
@edwinanciani and what if I don't need it to be in context with the API server and Project? Is there a way to silence the warning? Or maybe to configure it to not use any AppConfig (?)

**Comment by lane-formio** [comment]
There isn't currently a way to silence the warning, but we are always happy to review any contributions to potentially do this.
