### ISSUE TITLE
question for apiUrl and appURL

### ISSUE THREAD

**Issue by starbugs2008** [formio/angular-formio#138]
I am not sure how these two variables are setup, and how the been use.

**Comment by lookatmypinky** [comment]
https://github.com/formio/angular-app-starterkit/blob/master/src/config.js

**Comment by YuryRybakSoftensity** [comment]
@starbugs2008 Here is updatedd ref:
https://github.com/formio/angular-app-starterkit/blob/master/src/config.ts

**Comment by mauricios** [comment]
Hi, is there a better explanation or documentation on how to configure those variables than the code snippets from the app?

**Comment by jhen1422** [comment]
@mauricios 
Can you please open a new issue regarding your question?
