### ISSUE TITLE
How to register custom component in angular-formio

### ISSUE THREAD

**Issue by abhishek-priyadarshi** [formio/angular-formio#144]
I have created a custom component after following instruction from [here](https://github.com/formio/angular-formio/wiki/Resource-Management).

But after using that component getting error like "Unknown component: user".

I have tried solution from [this](https://github.com/formio/angular-formio/issues/85) but not able to find "BaseComponent" in angular-4.

Thanks,
AP

**Comment by travist** [comment]
That is instructions on how to implement a custom resource component. If you wish to register a new component, it actually will look something like this.

https://gist.github.com/travist/cda7a4abf0dfa287806aa9039a2fccf3.js

It seems all you need is to add the following at the bottom of the file.

```
Formio.registerComponent('custom', CustomComponent);
```

**Comment by catchshyam** [comment]
@travist In your example, you just use the custom component class,

import { BaseComponent } from './Base';
import { Formio } from 'formiojs/full';
export class CustomComponent extends BaseComponent {
  constructor(component, options, data) {
    super(component, options, data);
  }
}

Formio.registerComponent('custom', CustomComponent);

Any idea how can I include the template for the component?

**Comment by shivlila01** [comment]
In the older version of angular-formio(1.18.0) we registered the custom components using Formio.registerComponent() method and it was working perfectly. 

Recently we have upgraded our application with latest version of angular formio (3.9.0), after this up-gradation our custom components are not working it is showing error message as "unknown component : mycustomcomponent". Please help.
