### ISSUE TITLE
Error: Metadata version mismatch after update from 1.8.0 to 1.9.0

### ISSUE THREAD

**Issue by tianshibai** [formio/angular-formio#154]
Error: Error: Metadata version mismatch for module /node_modules/angular-formio/index.d.ts, found version 4, expected 3, resolving symbol AppModule in /src/app/app.module.ts, resolving symbol AppModule in /src/app/app.module.ts

**Comment by travist** [comment]
So, this may be a version you have within your AppModule that is conflicting with what is defined in this module now. I upgraded all dependencies, but thought I did that in a way where it would work with all version of Angular. Please identify what module this is complaining about and I can make an adjustment to the package.json of this library so that it is compatible.

**Comment by tianshibai** [comment]
here is my package.json file
`
{
  "name": "angular-src",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "prodbuild": "ng build --prod",
    "test": "ng test --sm=false",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@amcharts/amcharts3-angular": "^1.5.0",
    "@angular/animations": "^4.2.4",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "@nicky-lenaers/ngx-scroll-to": "^0.4.0",
    "angular-formio": "1.8.0",
    "angular2-moment": "^1.7.0",
    "bootstrap": "4.0.0-beta",
    "c3": "^0.4.18",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.5.1",
    "font-awesome": "^4.7.0",
    "isotope-layout": "^3.0.4",
    "jquery": "^3.2.1",
    "karma-intl-shim": "^1.0.3",
    "ng-pick-datetime": "5.0.0-beta.11",
    "ng2-toastr": "^4.1.2",
    "ngx-file-drop": "^1.0.18",
    "popper.js": "^1.12.5",
    "rxjs": "^5.4.3",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.4.4",
    "@angular/compiler-cli": "^4.2.4",
    "@angular/language-service": "^4.2.4",
    "@types/c3": "^0.4.45",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/jquery": "^3.2.16",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.2.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-sonarqube-unit-reporter": "0.0.14",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.3.3"
  }
}
`

**Comment by travist** [comment]
This should be fixed with ```version 1.10.0```. Please verify.

**Comment by cfsilence** [comment]
Verified - upgrading to 1.10.0 now builds fine in our environment.
(@tianshibai is on my team)
