### ISSUE TITLE
Field textarea with wysiwyg insert extra <p><br></p>

### ISSUE THREAD

**Issue by prizzio** [formio/angular-formio#160]
Hi,

Our project have some forms with textarea fields which have WYSIWYG mode activated, and we found an issue during its usage.

We observed that when one of these forms is completed, `"<p><br></p>"` tags are added to the first line break in the WYSIWYG textarea fields. I attach two images of this problem, one corresponds to the form before being saved, and the other corresponds to the form after being saved.

Before:
![image](https://user-images.githubusercontent.com/7702980/36437780-4438a1a6-1668-11e8-9d7b-30803ca0cdae.png)

After:
![image](https://user-images.githubusercontent.com/7702980/36437813-5aa5cda6-1668-11e8-9e2c-5b33cbd265fb.png)
![image](https://user-images.githubusercontent.com/7702980/36438168-5d60f9ac-1669-11e8-864f-c21619cf3b95.png)

---------------------

Additionally, I would like to ask you if there is any way to configure the editor to allow "<script>" tags to be inserted in the WYSIWYG content using "source" option.

![image](https://user-images.githubusercontent.com/7702980/36438194-7741fae2-1669-11e8-9e50-1bd3bf6f68e9.png)

Thank you

**Comment by travist** [comment]
This is basically how the Quill editor works. We are not sure why they add that extra content either, but maybe you could open up an issue in their queue.
