### ISSUE TITLE
Load custom component template

### ISSUE THREAD

**Issue by asalhani** [formio/angular-formio#166]
@travist @Navpreet2289  @zackurben @AlameerDev

I searched all over form.io Github repositories and site documentation looking for a way to load custom component template. All the sample I've found was applicable for angular 1, unfortunately, noting mentioned for angular 2.

So, I've created my custom component. I register it. I was able to render it using `<formio>` component. Now I'm looking for a way to develop (inject) component HTML template. I reviewed the code in core render project "formio.js" , I noticed that you are rendering, drawing, component in Type script file. However, I think that there is another way which is through injecting HTML template somehow as in below sample:

[Angular 1 Sample](https://github.com/formio/ngFormBuilder/blob/f5b2b351b23cd9c4c24a70bebb210896efe85f31/src/components/password.js)

So I'm wondering, since `$templateCache` is an Angular JS spacific service, what it should be in Angular 2?

**Comment by asalhani** [comment]
As it turns out, i noticed that $templateCache was to render the custom component on builder side. However I'm still trying to find the samething in render side.

**Comment by catchshyam** [comment]
@asalhani have you found a solution for this? Even I am struggling with the same

**Comment by asalhani** [comment]
@catchshyam unfortunately no. It looks like in render part, the only supported way is thru JavaScript. I believe that this is to make the library portable to any framework. However, on building part, you can define a set of html templates in building g mode.

**Comment by seanzamora** [comment]
I was able to inject my custom form-io component using Component Factory Resolver, and ViewContainerRef;

**Comment by asalhani** [comment]
Hi @seanzamora
Can you show us a code snippet of your solution so we get a better idea.. 
Thank you

**Comment by travist** [comment]
I just created some examples of a custom component in Angular. You can see it in the Angular Demo application @ https://github.com/formio/angular-demo.

Here is the custom component.

https://github.com/formio/angular-demo/blob/master/src/app/components/CheckMatrix.js

And here is how you register it within your application.

https://github.com/formio/angular-demo/blob/master/src/app/app.module.ts#L19

Hope this helps.
