### ISSUE TITLE
npm install errors

### ISSUE THREAD

**Issue by StefanHoutzager** [formio/angular-formio#174]
I downloaded the repo today and ran npm install (node 8.11.2 x64 windows 10 professional) and get errors:
[npm-debug.log](https://github.com/formio/angular-formio/files/2025907/npm-debug.log)
Very anxious to see the demo...
  npm install --save angular-formio gives errors also
[npm-debug.log](https://github.com/formio/angular-formio/files/2025996/npm-debug.log)

**Comment by travist** [comment]
Please try the latest version 2.0.0-alpha.8. It is installing fine for me.
