### ISSUE TITLE
npm run demo error

### ISSUE THREAD

**Issue by bmadhan90** [formio/angular-formio#176]
PS C:\Users\madhan\Downloads\Working Ex\angular-formio-master> npm run demo

> angular-formio@2.0.0-alpha.8 demo C:\Users\madhan\Downloads\Working Ex\angular-formio-master
> gulp build; concurrently --raw "webpack-dev-server --open" "npm run test:watch"

[11:54:45] Using gulpfile ~\Downloads\Working Ex\angular-formio-master\gulpfile.js
[11:54:45] Task 'build;' is not in your gulpfile
[11:54:45] Please check the documentation for proper gulpfile formatting
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-formio@2.0.0-alpha.8 demo: `gulp build; concurrently --raw "webpack-dev-server --open" "npm run test:watch"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-formio@2.0.0-alpha.8 demo script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\madhan\AppData\Roaming\npm-cache\_logs\2018-05-25T03_54_45_232Z-debug.log
PS C:\Users\madhan\Downloads\Working Ex\angular-formio-master>

**Comment by grigoreme** [comment]
Same error here.

**Comment by travist** [comment]
I am not getting this error. The task exists within the gulpfile.

**Comment by kikkiraj** [comment]
same issue here

**Comment by kikkiraj** [comment]
@travist Can you please share your gulpfile

**Comment by bmadhan90** [comment]
still same error.

**Comment by kaleguy** [comment]
This seems to be a windows issue. Windows doesn't like the semi colon after "build". 

Tried changing the semi-colon to "&&" but then got other errors on Windows. Seems to run OK on Ubuntu.

**Comment by Narasinha** [comment]
@kaleguy : I'm also facing same issue. Please can you explain me where excellently needs to be changed

**Comment by kaleguy** [comment]
I couldn't get it to work on Windows even after fixing the semi colon. Works fine on Mac or Ubuntu with no changes though. What OS are you using?

**Comment by Narasinha** [comment]
@kaleguy  We are using Windows 10

**Comment by kaleguy** [comment]
If you are running Windows on a desktop (and not an AWS virtual
machine) you should be able to get the app working with Docker. If you
need instructions I'll upload some.

**Comment by Narasinha** [comment]
@kaleguy  Thank you ! Please update instructions as well

**Comment by kaleguy** [comment]
Just added Dockerized version PR.
https://github.com/kaleguy/angular-formio/tree/docker

Should work on Windows, check it out.

BTW angular-starterkit works fine on Windows, issue is with this project's setup, not with Form.io.

**Comment by travist** [comment]
Fixed with the latest. The demo is now hosted @ https://github.com/formio/angular-demo.
