### ISSUE TITLE
Parser Error: Got interpolation ({{}}) where expression was expected

### ISSUE THREAD

**Issue by asmirljumic** [formio/angular-formio#179]
I have implemented angular-formio in my Angular 5 application. It works perfectly, but if I try to use the SELECT field with data from a url i get this error. The error is caused by the `"template": "{{ item.TZ }}",` .
Here is my code:
https://pastebin.com/raw/PHZimdvj
Here is my error:
https://pastebin.com/raw/s0zEZJFe

**NPM: 5.6.0
Angular CLI: 1.7.0
Node: 8.11.2
Angular: 5.2.11**

**Comment by asmirljumic** [comment]
I fixed it. What you need to do is define the form in the controler and then just call it in the template. Like this: `<formio [form]='forma'></formio>`

**Comment by benihime1** [comment]
Could you please share how you defined the form in the controller class, was this using typescript interfaces, or in a normal json format?

**Comment by nyaupane** [comment]
Guys! Did anybody find solutions? I am also facing this problems.

**Comment by asmirljumic** [comment]
The solution is to declare the form in .ts file of your component, like this:
`public myForm = {
    "title": "My Test Form",
    "components": [{
        "label": "Select",
        "mask": false,
        "type": "select",
         "input": true,
        "key": "select",
        "data": {
            "url": "http://www.mocky.io/v2/5b28f85a2f00009000f55f84",
            "headers": [{
                "key": "",
                "value": ""
            }],
            "values": []
        },
        "defaultValue": "",
        "dataSrc": "url",
        "template": "{{ item.TZ }}",
        "selectValues": "",
        "disableLimit": false,
        "searchField": "",
        "clearOnRefresh": false,
        "reference": false
    }]
};`
And then just call it in the .html file of your component, like this:
`<formio [form]='myForm'></formio>`

**Comment by nyaupane** [comment]
Hello @asmirljumic  I have this json It show above error do you have any idea? I tried your way it didn't work.
`{"components": [
    {
        "label": "Columns",
        "columns": [
          {
            "components": [
              {
                "label": "Text Field",
                "labelPosition": "top",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "prefix": "",
                "suffix": "",
                "widget": {
                  "type": "input"
                },
                "inputMask": "",
                "allowMultipleMasks": false,
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "showWordCount": false,
                "showCharCount": false,
                "mask": false,
                "autofocus": false,
                "disabled": false,
                "alwaysEnabled": false,
                "tableView": true,
                "multiple": false,
                "defaultValue": null,
                "persistent": true,
                "inputFormat": "plain",
                "protected": false,
                "dbIndex": false,
                "case": "",
                "encrypted": false,
                "redrawOn": "",
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "pattern": "",
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "minLength": "",
                  "maxLength": "",
                  "strictDateValidation": false
                },
                "unique": false,
                "errorLabel": "",
                "key": "textField",
                "tags": "",
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "textfield",
                "input": true,
                "refreshOn": "",
                "inputType": "text",
                "hideOnChildrenHidden": false,
                "id": "essgnaw"
              }
            ],
            "width": 6,
            "offset": 0,
            "push": 0,
            "pull": 0
          },
          {
            "components": [
              {
                "label": "Select",
                "labelPosition": "top",
                "widget": "choicesjs",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "autofocus": false,
                "disabled": false,
                "alwaysEnabled": false,
                "tableView": true,
                "multiple": false,
                "dataSrc": "values",
                "defaultValue": null,
                "data": {
                  "values": [],
                  "resource": "",
                  "json": "",
                  "url": "",
                  "custom": ""
                },
                "valueProperty": "",
                "dataType": "",
                "template": <span>{{item.label}}</span>,
                "searchEnabled": true,
                "selectThreshold": 0.3,
                "readOnlyValue": false,
                "customOptions": {},
                "persistent": true,
                "protected": false,
                "dbIndex": false,
                "encrypted": false,
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "strictDateValidation": false
                },
                "unique": false,
                "errorLabel": "",
                "key": "select",
                "tags": "",
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "select",
                "minSearch": 0,
                "limit": 100,
                "input": true,
                "prefix": "",
                "suffix": "",
                "refreshOn": "",
                "redrawOn": "",
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "clearOnRefresh": false,
                "lazyLoad": true,
                "filter": "",
                "searchField": "",
                "authenticate": false,
                "selectFields": "",
                "searchThreshold": 0.3,
                "fuseOptions": {
                  "include": "score",
                  "threshold": 0.3
                },
                "hideOnChildrenHidden": false,
                "id": "e0c1md"
              }
            ],
            "width": 6,
            "offset": 0,
            "push": 0,
            "pull": 0
          },
          {
            "components": [],
            "width": 12,
            "offset": 0,
            "push": 0,
            "pull": 0
          }
        ],
        "autoAdjust": false,
        "hideOnChildrenHidden": false,
        "customClass": "",
        "hidden": false,
        "hideLabel": false,
        "alwaysEnabled": false,
        "tableView": false,
        "key": "columns",
        "tags": "",
        "properties": {},
        "conditional": {
          "show": null,
          "when": null,
          "eq": "",
          "json": ""
        },
        "customConditional": "",
        "logic": [],
        "attributes": {},
        "overlay": {
          "style": "",
          "page": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "type": "columns",
        "input": false,
        "placeholder": "",
        "prefix": "",
        "suffix": "",
        "multiple": false,
        "defaultValue": null,
        "protected": false,
        "unique": false,
        "persistent": false,
        "clearOnHide": false,
        "refreshOn": "",
        "redrawOn": "",
        "labelPosition": "top",
        "description": "",
        "errorLabel": "",
        "tooltip": "",
        "tabindex": "",
        "disabled": false,
        "autofocus": false,
        "dbIndex": false,
        "customDefaultValue": "",
        "calculateValue": "",
        "widget": null,
        "validateOn": "change",
        "validate": {
          "required": false,
          "custom": "",
          "customPrivate": false,
          "strictDateValidation": false
        },
        "allowCalculateOverride": false,
        "encrypted": false,
        "showCharCount": false,
        "showWordCount": false,
        "allowMultipleMasks": false,
        "tree": false,
        "id": "edqvl6w",
        "path": "columns"
      }
    ]}`
