### ISSUE TITLE
Submission Occuring Twice

### ISSUE THREAD

**Issue by seanzamora** [formio/angular-formio#181]
Upon submission it appears form-io is submitting data twice, has anyone experience this issue?

A few things to note:

I am loading the component with the form-io tag onto my page using Component Factory. Could this be the issue?

**Comment by seanzamora** [comment]
I implemented a temporary fix that uses a bool flag to check if form has already been submitted.

**Comment by seanzamora** [comment]
Fixed this issue. Caused by memory leak. Unsubscribe your observable guys. 😊

**Comment by travist** [comment]
Will you please provide more detail how you solved the problem.
