### ISSUE TITLE
Unable to edit child components using form builder.

### ISSUE THREAD

**Issue by lcharanteja** [formio/angular-formio#184]
When I try to edit text field getting parent.editcomponent is not a function exception
![git](https://user-images.githubusercontent.com/9964952/42336171-dbb06f3a-8050-11e8-8849-9a0470c5a501.PNG)

 ```javascript
    var editButton = parent.ce('div', {
          class: 'btn btn-xxs btn-default component-settings-button component-settings-button-edit'
        }, parent.getIcon('cog'));
        parent.addEventListener(editButton, 'click', function () {
          return parent.editComponent(comp);
        });
```

Code is breaking at above mentioned code snippet in WebFormBuilder.js.  What could be the issue.

**Comment by mail4regist** [comment]
waiting...

**Comment by dslshweta** [comment]
Same issue.. Can anyone provide solution to it please.
