### ISSUE TITLE
Container data will not be updated on submit

### ISSUE THREAD

**Issue by jensober** [formio/angular-formio#195]
The form below uses a container component. When the data is pre-populated by [submission], the changes made by the user in the from are ignored when he hits the submit button.

So, when i change the value of the Name field from "Fred" to "Barney", the value "Fred" remains in the submitted data.

Is there anything that i am doing wrong here?

```html
<formio 
  (submit)="onSubmit($event)"
  [submission]='{
    data: {
      "recipient": {
        "Name": "Fred"
      }
    }
  }'
  [form]='{
    "title": "Test Form",
    "components": [
      {
        "input": true,
        "tree": true,
        "components": [
          {
            "autofocus": false,
            "input": true,
            "tableView": true,
            "inputType": "text",
            "inputMask": "",
            "label": "Name",
            "key": "Name",
            "placeholder": "",
            "prefix": "",
            "suffix": "",
            "multiple": false,
            "defaultValue": "",
            "protected": false,
            "unique": false,
            "persistent": true,
            "hidden": false,
            "clearOnHide": true,
            "spellcheck": true,
            "validate": {
              "required": false,
              "minLength": "",
              "maxLength": "",
              "pattern": "",
              "custom": "",
              "customPrivate": false
            },
            "conditional": {
              "show": "",
              "when": null,
              "eq": ""
            },
            "type": "textfield",
            "labelPosition": "top",
            "inputFormat": "plain",
            "tags": [],
            "properties": {},
            "lockKey": true
          }
        ],
        "tableView": true,
        "label": "Recipient",
        "key": "recipient",
        "protected": false,
        "persistent": true,
        "clearOnHide": true,
        "type": "container",
        "labelPosition": "top",
        "tags": [],
        "conditional": {
          "show": "",
          "when": null,
          "eq": ""
        },
        "properties": {}
      },
      {
        "autofocus": false,
        "input": true,
        "label": "Submit",
        "tableView": false,
        "key": "submit",
        "size": "md",
        "leftIcon": "",
        "rightIcon": "",
        "block": false,
        "action": "submit",
        "disableOnInvalid": false,
        "theme": "primary",
        "type": "button"
      }
    ]
  }
'>
</formio>```

**Comment by wag110894** [comment]
Hello Jensober, 

This is William with the Form.io support team. Thanks for reaching out.

**Comment by wag110894** [comment]
Hello Jensober,

This is William with the Form.io support team. Thanks for reaching out! 

Form.io offers support packages as well as development services to help with your application. These services connect you directly with a Form.io developer and can be a huge help with your app. Please let me know if you’re interested, I’d be more than happy to send you additional information.

Please let me know if you have any further questions or concerns. 

Thanks,
William Gay
Form.io Support

**Comment by jensober** [comment]
Hi William,
i am IT-Consultant and just evaluating form.io as a solution for some customers of us.

I wondered if this issue is a bug. Where can i ask those questions?
Cheers Jens

**Comment by wag110894** [comment]
Hello Jensober,

We will investigate this and will notify you once we find the issue. I have created a ticket and have tagged you on it. For reference, the ticket number is FOR-1628. Every Monday we have a planning meeting to discuss issues. We will let you know the priority of this issue on Monday. 

Thanks,
William Gay
Form.io Support

**Comment by wag110894** [comment]
Hello Jensober,
William here again. 

Our development team has estimated this issue  at 4 hours.  Please let me know if you’re interested and I can send you a formal quote.

Please let me know if you have any further questions or concerns.

Thanks, 
William Gay 
Form.io Developer Support

**Comment by franke-mc** [comment]
This appears to be working now. Both beforeSubmit and onSubmit show recipient: Object { Name: "Barney" } in the submission data.
