### ISSUE TITLE
Adding custom components in Angular6

### ISSUE THREAD

**Issue by virajkanwade** [formio/angular-formio#204]
The gist provided https://gist.github.com/travist/59fa77086ec899e24992fc1508e61075 does not work for Angular6.

What changes are required to get it to work?

Has anybody managed to get it to work?

Thanks

**Comment by travist** [comment]
We will work on some updated documentation for custom components.

**Comment by travist** [comment]
I just created some examples of a custom component in Angular. You can see it in the Angular Demo application @ https://github.com/formio/angular-demo.

Here is the custom component.

https://github.com/formio/angular-demo/blob/master/src/app/components/CheckMatrix.js

And here is how you register it within your application.

https://github.com/formio/angular-demo/blob/master/src/app/app.module.ts#L19

Hope this helps.
