### ISSUE TITLE
overriding component builderInfo

### ISSUE THREAD

**Issue by dolphinsd** [formio/angular-formio#212]
Is there a way to override builderInfo for each component? 
For example, we want to change icon and override Title with international version.
Thanks.

**Comment by wag110894** [comment]
Hello again,

Here is an example of how to accomplish this by using a custom builder. 
http://formio.github.io/formio.js/app/examples/custombuilder.html

Please let me know if you have any further questions or concerns.

Thanks, 
William Gay 
Form.io Developer Support

**Comment by dolphinsd** [comment]
@wag110894 thanks, I see how to add components. we just want to override default builderInfo  on built in components. Do you have an example? Thanks.

**Comment by wag110894** [comment]
Hello Again, 
You can do this like this: 
var textFieldInfo = Formio.Components.components.textfield.builderInfo;
textFieldInfo.title = 'My TextField';
Formio.Components.components.textfield.builderInfo = textFieldInfo;

Please let me know if you have any further questions or concerns.

Thanks, 
William Gay 
Form.io Developer Support

**Comment by dolphinsd** [comment]
@wag110894 your example does not seems to work, as there is not setter on builderinfo.
Here is an error:
error: TypeError: Cannot set property builderInfo of function TextFieldComponent() {
    _classCallCheck(this, TextFieldComponent);

    return _possibleConstructor...<omitted>... } which has only a getter

**Comment by wag110894** [comment]
Hello again,

 Here is an example of how it looks in angular as it is a little different. https://github.com/formio/angular-demo/blob/master/src/app/components/CheckMatrix.js

Please let me know if you have any further questions or concerns.

Thanks,

**Comment by dolphinsd** [comment]
@wag110894 thanks for the example. we are using angular and familiar with custom component. The original question is asking how to override builderInfo on predefined components. As the current code uses only get as showing in your example:
static get builderInfo()
{
....
}

Javascript would not allow to set values on static get property!

**Comment by travist** [comment]
By creating a class that extends a base component class and then provides its own ```static get builderInfo()```, you are basically "overriding" it. I am curious why this is not working for you since the code provided above does exactly this. You can return whatever JSON you would like from your overridden class.

**Comment by felipebelluco** [comment]
This works for me:

```
const BaseComponent = require('formiojs/components/base/Base').default;
const Components = require('formiojs/components/Components').default;
const TextFieldComponent = require('formiojs/components/textfield/TextField').default;

export class MyTextFieldComponent extends TextFieldComponent {

    static schema() {
        return BaseComponent.schema({
            type: 'mytextfield',
            label: 'My Text Field',
            placeholder: 'Insert text here...',
        });
    }

    static get builderInfo() {
        return {
            title: 'My Text Field',
            group: 'basic',
            icon: 'fa fa-bath',
            weight: 0,
            documentation: 'http://help.form.io/userguide/#textfield',
            schema: MyTextFieldComponent.schema()
        };
    }
}

Components.addComponent('mytextfield', MyTextFieldComponent);
```

Don't forget to add the import of your component to your module:

import './my-text-field.component';

**Comment by davidyoung77** [comment]
@dolphinsd did you ever figure this out?
