### ISSUE TITLE
glyphicon are not in the build

### ISSUE THREAD

**Issue by dolphinsd** [formio/angular-formio#221]
In component settings dialog glyphicon icons for plus and minus are missing. Consider replacing them with fa icons like fa-plus-square and fa-minus-square

**Comment by wag110894** [comment]
Hello,
 
Thank you for the recommendation. We will add this to our planning doc under needs to be discussed.  We also have processes in place to quote feature requests if you are interested.
 
 
Thank you!

**Comment by travist** [comment]
No glyphicons are supported since this is based on Bootstrap 4. We are using fontawesome.
