### ISSUE TITLE
encrypted checkbox is mapped to autofocus

### ISSUE THREAD

**Issue by dolphinsd** [formio/angular-formio#222]
When textbox data tab encrypted checkbox is checked, it resolves to autofocus true/false in template. Does not seems right. Here are two templates. The only difference between them is encrypt was checked. See 2 files attached.
[template2.txt](https://github.com/formio/angular-formio/files/2559822/template2.txt)
[tempalte1.txt](https://github.com/formio/angular-formio/files/2559823/tempalte1.txt)

![1f43b99a3ef81b289837f1038ee2d38d](https://user-images.githubusercontent.com/3460517/48169830-ba6f3200-e2a9-11e8-9db8-fc03fb3d3232.png)

**Comment by wag110894** [comment]
Hello Again,
 
Thank you for bring this issue to our attention. This will require some investigation on our side to replicate this issue.  We have created a ticket (FOR-1850) and have added to our backlog. We will let you know when this issue has been prioritized.
 
 
Please let me know if you have any further questions or concerns. 
 
Thank you!

**Comment by travist** [comment]
This is fixed in latest renderer.
