### ISSUE TITLE
Select Componet Issue PreSelect value

### ISSUE THREAD

**Issue by AnasHijazi** [formio/angular-formio#228]
There are something wrong in select component i have array of JSON of object So i used  **URL as Data Source Type** until now every thing it's ok .

I want now preselect on of these options, based on documention should  be there are field called "value property" but it's not there .

there are any advice to solve this ?

**Comment by jhen1422** [comment]
Hello,

The ‘Value Property’ field has not been added to  our beta site yet but is definitely on our backlog.  This is available on our production portal at https://portal.form.io/ . 

Let us know if you need anything else

**Comment by randallknutson** [comment]
If you are using the Value Property option, you should be able to use the default value option to set the property value. For example, for your select field, if the Value Property is set to "value", you can set the default value to "BH" and it will select that one from the list by default.

**Comment by AnasHijazi** [comment]
@randalkuntson thanks for your response,
The **Value property** available in beta website , currently I use angular-formio version 3.8.0 , how can get this feild property in my project

**Comment by travist** [comment]
@AnasHijazi the Beta website just uses the core builder which is already available within the form manager module within this library. The documentation shows how this can be used within your own application.

**Comment by AnasHijazi** [comment]
@travist  i can't understand you , i have get component select manual ? if yes can share me location please ?

**Comment by wag110894** [comment]
Here is that documentation for select: https://help.form.io/userguide/form-components/#select

**Comment by AnasHijazi** [comment]
@wag110894 , I know this documention based on this there are field **value property** it's available on beta web site how can get this property ?

 I can't understand comment @travist



I using angular-formio version 3.9.0
