### ISSUE TITLE
How to call angular component on formio events

### ISSUE THREAD

**Issue by shivlila01** [formio/angular-formio#230]
We are able to call validation events on onBlur and OnChange events of the angular-formio controls. Please let us know how to call methods of angular component on the events like onBlur , FormLoad of angular-formio.

**Comment by travist** [comment]
You can reference the actual form component using the following method.

https://gist.github.com/travist/4d8ea88a1ea3683c24125b560be86c39

You could then just use the Form.io JS SDK to gain whatever methods and event handlers you need.

https://formio.github.io/formio.js/app/sdk
