### ISSUE TITLE
Validation is triggered with a delay (Wizard)

### ISSUE THREAD

**Issue by gorjupleon** [formio/angular-formio#231]
Validation of any component can be skipped if you click "next" or "submit" quickly after editing the field before the validation is triggered. 

For example, the input field on the first page of this form: https://formview.io/#/sunncakniycksmm/testform?header=1 
If you type text in quickly enough and immediately click next, the change / validation event is not triggered. That is almost a second of time to write whatever you want in there, intentionally or accidentally. 

When using input masks, you can also end up with an additional character at the end, or an underscore, if you edit the text in the middle. Even the server-side validation doesn't seem to check these.

In our case, we have a custom PHP backend with no server-side validation support, so a frontend solution would be appreciated.

**Comment by travist** [comment]
formview.io is using our legacy Angular 1.x renderer. Will you test this within our "core" renderer @ https://github.com/formio/formio.js. I am thinking that this may not exist within our core renderer but would like verification if that is the case.

**Comment by gorjupleon** [comment]
Hi, sorry for the late reply. Indeed, the issue does not seem to happen with the core renderer. The Angular 4 renderer also works fine now that I checked. The issue is just with ngFormio and ngFormBuilder, which I guess is also the one on formview.io.

**Comment by travist** [comment]
Yeah, we will be upgrading the formview.io to the core renderer eventually. For now, I am closing this ticket since there is currently nothing to do with this library.
