### ISSUE TITLE
Angular component and form.io component interaction for validation and data setup.

### ISSUE THREAD

**Issue by chetanmenge** [formio/angular-formio#234]
Hello,
		Need help to apply form level validation and data setup. Please find below details,

What is working ( Component level )
	
- With custom validation ( using validate.custom ) we are able to set component level validation.
- With data ( using data.defaultValue ) we are able to set component level data.
 
 
What we are looking for is 
	Setting validation and data setup at form level.  Which can be form level event such as
 formLoad ( form.io formLoad event ) , or event generating from any external button defined at angular component  ( such as  cancel , setdata button which are outside of form.io and are defined at angular component level which are triggering validatio or data setup )
 
  
-On click of button ( defined outside of form.io ) can we trigger validation for only few fileds ? 
-On click of button ( defined outside of form.io ) can we trigger data setup for only few fileds ?
- The way we have component level validation ( using validate.custom ) and data setup ( using data.defaultValue) do we have any anything similar for form level. ( Within JSON ) or any other approach for this use case ?

 Please let me know if more details needed.

 FYI,
- Our data setup and validation rule can be dynamic ( e.g on angular button click , I would like to validate only few components from form or set value for few button.)
- These validation and data setup will be separate or on top of component level validation. 

Thanks,
Chetan.

**Comment by travist** [comment]
We received your support via email. We will respond to this inquiry there.
