### ISSUE TITLE
Errors using <formio-grid src="..." [components]='...'>

### ISSUE THREAD

**Issue by franke-mc** [formio/angular-formio#251]
Is there a working example of <formio-grid [components]=...> somewhere?

Referring to https://github.com/formio/angular-formio/commit/7245407545de249b435390b15aebee0eff5f7b22#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR73

Starting from a working grid: `<formio-grid src="https://examples.form.io/company"></formio-grid>` in angular-app-starterkit, I need to customize it using `[components]='{header:..., body:..., footer:...}'`. Where do SubmissionGridHeaderComponent etc. come from? Without any imports, the errors I get are:
> error TS2304: Cannot find name 'SubmissionGridHeaderComponent'
> ...

With importing them as follows, I get the errors below:
- app.module.ts:
```
import { FormioGrid } from 'angular-formio/grid';
...
imports: [FormioGrid, ...]
```
- home/home.component.ts:
```
import { FormioGrid } from 'angular-formio/grid';
import { SubmissionGridHeaderComponent } from 'angular-formio/grid/submission/SubmissionGridHeader.component';
import { SubmissionGridBodyComponent   } from 'angular-formio/grid/submission/SubmissionGridBody.component';
import { SubmissionGridFooterComponent } from 'angular-formio/grid/submission/SubmissionGridFooter.component';
```
- home/home.component.html:
```
    <formio-grid src="https://examples.form.io/company"
                 [components]='{
                 header: SubmissionGridHeaderComponent,
                 body:   SubmissionGridBodyComponent,
                 footer: SubmissionGridFooterComponent
                 }'
                 ></formio-grid>
```
- ERRORS in JS console:
> ERROR Error: "No component factory found for undefined. Did you add it to @NgModule.entryComponents?"
> in View_HomeComponent_0
> ...
> ERROR TypeError: "this.header is undefined"
> in loadGrid

I tried adding those same imports (with corresponding declarations) to app.module.ts, but that caused complaints about duplicate declarations in different modules...

Any help is very much appreciated.

**Comment by travist** [comment]
The idea is to extend these components with your own components within your application and then register the extended components (which will not complain about duplicate declarations). For example, you could do this..

```CustomSubmissionGridHeaderComponent.ts
export default class CustomSubmissionGridHeaderComponent extends SubmissionGridHeaderComponent {
}
```

```html
<formio-grid src="https://examples.form.io/company"
  [components]='{
     header: CustomSubmissionGridHeaderComponent,
  }'
></formio-grid>
```

**Comment by franke-mc** [comment]
Thanks Travis! For future reference, here is one way to solve it:
[formio-grid-components-for-angular-app-starterkit.patch.txt](https://github.com/formio/angular-formio/files/2901142/formio-grid-components-for-angular-app-starterkit.patch.txt)
