### ISSUE TITLE
Form json not updated when components position changed using drag and drop

### ISSUE THREAD

**Issue by deepanshuda** [formio/angular-formio#261]
When we drop a textfield and a number component in form builder we get correct form JSON. But after that if number component is moved above textfield using drag and drop, the JSON remains same and new form configuration is not available. If we drag new component from list that updates json.
<img width="934" alt="screenshot 2019-03-06 at 12 30 11 pm" src="https://user-images.githubusercontent.com/16358251/53862009-e6a67f80-400b-11e9-988b-d342f08ac945.png">
<img width="960" alt="screenshot 2019-03-06 at 12 30 03 pm" src="https://user-images.githubusercontent.com/16358251/53862011-e73f1600-400b-11e9-9a03-9914fbbb5739.png">

**Comment by travist** [comment]
I just tried this on this demo and it works fine. https://formio.github.io/formio.js/app/builder

Are you sure you are binding to the correct events. Take a look at the source from that page to see how it should be done.

**Comment by 0mohit** [comment]
@travist : thanks for the reply but we are using https://formio.github.io/angular-demo/#/forms/builder library .In this if we try to change the position json is not being updated .

**Comment by travist** [comment]
They are using the same builder, so it may be the case that the angular library may implement the SDK incorrectly. We will take a look, but it may take a while for this item to make our developer backlog. Pull requests welcome.

**Comment by wag110894** [comment]
Hello,

Thank you for your patience while we discussed this issue. After discussion, we do not view this as a high priority on our end. If you need this fix, we do offer a chance to expedite this fix. Our developers have estimated this issue at 4 hours. 

Please let me know if you are interested in expediting this issue and we would be happy to send you a formal quote.

Thanks,
William Gay 
Form.io Support

**Comment by 0mohit** [comment]
@wag110894 : thanks for your support . but I solved the issue .

**Comment by Vedhachala** [comment]
@0mohit I was looking over the issue .. the fix is to capture 'change' event emitted  from Webformbuilder.js 
in form-builder.component.ts right .?
@wag110894 It would be helpful if you can expedite the issue and fix it.
