### ISSUE TITLE
Chrome freezes on rendering big JSON Schema

### ISSUE THREAD

**Issue by bolatk** [formio/angular-formio#266]
Hi there,
We have a big form (a combination of many other forms) with conditional logic which shows some area based on initial data. It generates a big JSON Schema [http://formio.mis.bizml.ru/s0015](url), 575Kb.
When we render the big form in Angular application it loads almost 5-6 sec and freezes Chrome Browser.
Then Chrome display typing on input element with some delay. Is there any approaches how to solve this issue?
`<formio *ngIf="form"
                        [src]="'http://formio.mis.bizml.ru/'+form"
                        class="mb-3"
                        #formio
                        (beforeSubmit)="onBeforeSubmit($event)"
                        (submit)="onSubmit(form, $event)"
                        [submission]="submissionInitial"
                        [refresh]="refreshFormInitial">
                </formio>`

**Comment by randallknutson** [comment]
Can you test this out using just formio.js and see if it is something wrong in angular-formio? Also, you may want to test out the 4.x branch as we are changing the way things render and you might get better performance.

**Comment by bolatk** [comment]
Thank you for ideas, but it does not help. What I did:
1. Replaced `<formio ...>` with `<div id='formio'></div>` in html.
2. Created **CustomFormio.js** in **assets/javascript** folder with contents:
```
export function createForm(src) {
  window.onload = function() {
    Formio.createForm(document.getElementById('formio'), src);
  };
}
```
3. Created **CustomFormio.d.ts** in **assets/javascript** folder with contents:
`export declare function createForm(src: string);`
4. In my FormioComponent import implemented function with:
`import { createForm } from '../../../../assets/javascript/customFormio';`
```
ngOnInit() {
  createForm('http://formio.mis.bizml.ru/s0015');
}
```
I tried with v 3.16 and formiojs@4.0.0-beta.10.
Any other ideas?

**Comment by travist** [comment]
We will need to assign this to an engineer on our team to investigate this issue for you. Please contact support@form.io if you want to go down that route.

**Comment by bolatk** [comment]
@randallknutson @travist we found a reason of freezing input elements. It's because of conditional logic like:
`show = ((data.speciality == "гинеколог" || data.speciality == "акушер-гинеколог" || data.speciality == "маммолог" || data.speciality == "онколог" || data.speciality == "ангиохирург" || data.speciality == "акушер-гинеколог") && data.patientGender == 'f');`

**Comment by randallknutson** [comment]
We've had some issues with infinite change events when using conditional logic. In order to resolve this you can contact support and we can work through the specific form and figure out why it is happening.

**Comment by bolatk** [comment]
@randallknutson thank you for pointing out. We've resolve the issue with [JSON Conditional](http://formio.github.io/formio.js/app/examples/conditions.html) instead of Formio Advanced Conditional logic.
