### ISSUE TITLE
Angular 2 css not loaded

### ISSUE THREAD

**Issue by Moshewiner** [formio/angular-formio#269]
Hello,
I'm using the latest version of angular & formio,
I did all the instructions and even have look at the source code.
I am NOT using bootstrap, but I am using angular matrial.
The formbuilder component (I didn't try the rest, yet) loads without any css.
as any other library - I thought maby I need to import to the angular.json styles array costum css,
I found some issued about things like that but it seems to be very old and not relevant to the current version..

How am I suppposed to add the css? 
thanks!

**Comment by travist** [comment]
We currently do not support angular material, but just through the "materia" theme in bootstrap.

**Comment by Moshewiner** [comment]
I understand, I must import bootstrap to the main project? There's any trick to import it only for this component?
