### ISSUE TITLE
Send its own errors to fields and display it instantly

### ISSUE THREAD

**Issue by Narsciz** [formio/angular-formio#274]
Hi, i'm working with a lot of third party to get the data used to populate my forms (like select options for example) and i would like to display my errors messages under the fields as error validation do it. But i can't find a way with form.io to set the error status of a field to allow me to display such message.
Is there a way to do it?
Thanks in advance for your answer and sorry for my possibly bad english.

**Comment by wag110894** [comment]
Hello,

You can accomplish this with our Custom Error Message on the validation tab of most of our components. This will allow you to customize the error message that displays underneath the field and override the existing.

Here is a screenshot of where you can find the custom error message textfield.
https://www.screencast.com/t/YbH8xqMt

**Comment by Narsciz** [comment]
Hi Will, thanks for your answer,
I've already explore this but my problem is to display errors whenever i want on a field, not only when change, blur or submit event is triggered, and after form is rendered. Is there a way to do this, with the refresh properties for example?

**Comment by randallknutson** [comment]
Probably the best way to do this right now is to implement options.hooks.customValidation. This only runs on submit but can be used to do asynchronous validation and set custom messages on fields. We don't have lots of documentation around this yet but you can see the code here: https://github.com/formio/formio.js/blob/master/src/Webform.js#L1186

**Comment by Narsciz** [comment]
Thanks for your time Randall, i will take this as final answer, and will conclude that it's not possible right now to manage my errors exactly like i want. 
I close the issue, thanks to you two.
