### ISSUE TITLE
Form builder Sub form (nested form) error "Unable to load resources for form"

### ISSUE THREAD

**Issue by ttomytiss** [formio/angular-formio#276]
When in form builder adding "Nested Form" component. Select sub form from select box and try to save (add this component in form template) returns in browser console warning "Unable to load resources for form". Nested form is not added in form template. Last working version was "angular-formio": "3.10.2" and "formiojs": "3.15.6". From version "angular-formio": "3.11.0" and/or "formiojs": "3.16.0" does not work. 

Full error code: 
`Unable to load resources for form
(anonymous) @ 4.c65186cb703bef595416.js:1
t.invoke @ polyfills.fa1bceeb95634527c1fa.js:1
onInvoke @ main.f5990ff31cb383a3acb2.js:1
t.invoke @ polyfills.fa1bceeb95634527c1fa.js:1
e.run @ polyfills.fa1bceeb95634527c1fa.js:1
(anonymous) @ polyfills.fa1bceeb95634527c1fa.js:1
t.invokeTask @ polyfills.fa1bceeb95634527c1fa.js:1
onInvokeTask @ main.f5990ff31cb383a3acb2.js:1
t.invokeTask @ polyfills.fa1bceeb95634527c1fa.js:1
e.runTask @ polyfills.fa1bceeb95634527c1fa.js:1
g @ polyfills.fa1bceeb95634527c1fa.js:1
e.invokeTask @ polyfills.fa1bceeb95634527c1fa.js:1
invoke @ polyfills.fa1bceeb95634527c1fa.js:1
n.args.(anonymous function) @ polyfills.fa1bceeb95634527c1fa.js:1
setTimeout (async)
u @ polyfills.fa1bceeb95634527c1fa.js:1
t.scheduleTask @ polyfills.fa1bceeb95634527c1fa.js:1
onScheduleTask @ polyfills.fa1bceeb95634527c1fa.js:1
t.scheduleTask @ polyfills.fa1bceeb95634527c1fa.js:1
e.scheduleTask @ polyfills.fa1bceeb95634527c1fa.js:1
e.scheduleMacroTask @ polyfills.fa1bceeb95634527c1fa.js:1
v @ polyfills.fa1bceeb95634527c1fa.js:1
(anonymous) @ polyfills.fa1bceeb95634527c1fa.js:1
A.i.(anonymous function) @ polyfills.fa1bceeb95634527c1fa.js:1
Br @ 4.c65186cb703bef595416.js:1
(anonymous) @ 4.c65186cb703bef595416.js:1
b @ 4.c65186cb703bef595416.js:1
value @ 4.c65186cb703bef595416.js:1
value @ 4.c65186cb703bef595416.js:1
value @ 4.c65186cb703bef595416.js:1
value @ 4.c65186cb703bef595416.js:1
value @ 4.c65186cb703bef595416.js:1
value @ 4.c65186cb703bef595416.js:1
(anonymous) @ 4.c65186cb703bef595416.js:1
value @ 4.c65186cb703bef595416.js:1
value @ 4.c65186cb703bef595416.js:1
value @ 4.c65186cb703bef595416.js:1
value @ 4.c65186cb703bef595416.js:1
(anonymous) @ 4.c65186cb703bef595416.js:1
value @ 4.c65186cb703bef595416.js:1
(anonymous) @ 4.c65186cb703bef595416.js:1
value @ 4.c65186cb703bef595416.js:1
(anonymous) @ 4.c65186cb703bef595416.js:1
t.invokeTask @ polyfills.fa1bceeb95634527c1fa.js:1
onInvokeTask @ main.f5990ff31cb383a3acb2.js:1
t.invokeTask @ polyfills.fa1bceeb95634527c1fa.js:1
e.runTask @ polyfills.fa1bceeb95634527c1fa.js:1
e.invokeTask @ polyfills.fa1bceeb95634527c1fa.js:1
m @ polyfills.fa1bceeb95634527c1fa.js:1
b @ polyfills.fa1bceeb95634527c1fa.js:1`

**Comment by travist** [comment]
This sounds like the ```Formio.setProjectUrl``` is incorrect. This would cause the forms to load from the wrong location.

**Comment by ttomytiss** [comment]
Found out how to repeat this. Same problem exists on [https://formio.github.io/formio.js/app/builder](https://formio.github.io/formio.js/app/builder) . When you drag and drop "Nested form" component in to form builder. And straight go to "Form" tab without entering any value to Field label input in "Display" tab and press "Save". In browser console appears previous warning. But when go back to "Display" tab fill label field and when press "Save" it works as expected.

**Comment by samdidos** [comment]
I don't know if it's related but I have the same issue and I realized that the nested forms' links are not rendered well.

Since I work with a FormIO server on-premise, the URL of a project is 
```
# Cloud URL
https://<my_formio_project>.form.io
# On-premise URL
https://<my_formio_server_URL>/<my_formio_project>
```
But when it renders the form and tries to fetch the nested form, it tries to reach : 
```
https://<my_formio_server_URL>/form/<form_id>
``` 
So I receive this errors : `Failed to load resource: the server responded with a status of 400 (Bad Request)` and `ERROR Error: Uncaught (in promise): Invalid alias`.

It says `invalid alias` because it's missing the project context, so it check if 'form' is an existing project. The nested form's URL should be like this instead :
```
https://<my_formio_server_URL>/<my_formio_server_URL>/form/<form_id>
```

@travist it seems to be linked to `Formio.setProjectUrl`. I didn't made any funky config, I don't know why it's not working properly. When I use the "Launch" option, the standalone form renders well the nested forms, so it seems really related to `formio-angular`. Is there any ways to fix this?

**Comment by travist** [comment]
You actually need to use both ```setProjectUrl``` in addition to ```setBaseUrl``` within your application to get this to render correctly. For example, it will need to be.

```
Formio.setBaseUrl('https://<my_formio_server_URL>');
Formio.setProjectUrl('https://<my_formio_server_URL>/<my_formio_project>');
```

**Comment by lane711** [comment]
What about if I am using the angular version of formio without a connecting to a server? I am getting the same error while trying to use a nested form.

**Comment by wag110894** [comment]
Hello @lane711,

Could you open this issue as a new issue. This chain has gone stale.

Thanks.
