### ISSUE TITLE
Sub form (nested form) component shows undefined instead of title in form builder

### ISSUE THREAD

**Issue by ttomytiss** [formio/angular-formio#277]
When add Sub form (nested form) component to form template in form builder this component are showed with label 'undefined'. Should show 'Nested form' component`s label value.? When load this form json template in form builder these nested forms components still are with 'undefined' values.

**Comment by travist** [comment]
I am unable to reproduce this issue... do you have any js fiddle examples?

**Comment by ttomytiss** [comment]
Now it works. In response was missing title attribute. Thank you.
