### ISSUE TITLE
Submit Event not being triggered

### ISSUE THREAD

**Issue by sabinayakc** [formio/angular-formio#281]
### Angular 7 Submit Event not being triggered.

Hello,
I am working on a **Angular 7** Project. I downloaded the Angular Demo code [https://formio.github.io/angular-demo](https://formio.github.io/angular-demo) and ran it locally. 

In the `renderer.component.html` I added the `(submit)` event and in the `renderer.component.ts` I added a method `onSubmit($event)`. The `(change`) event gets triggered but the `(submit)` event doesn't after clicking on the **Submit** button. Its the same case for `(invalid)`. See below image for the simple change I made to test this bug. 

![image](https://user-images.githubusercontent.com/13154166/55282701-b0f96b80-5317-11e9-8f0e-7c545ecb4af8.png)

![image](https://user-images.githubusercontent.com/13154166/55282707-07ff4080-5318-11e9-999a-2ed106f396d3.png)

**Comment by travist** [comment]
This may be caused by that you are using a form object instead of the url. We will investigate.

**Comment by ziishaned** [comment]
I solved the issue by using `action: 'submit'`

**Comment by sabinayakc** [comment]
@ziishaned Could you share the code snippet? Where should I add `action: 'submit'`?

**Comment by ziishaned** [comment]
> @ziishaned Could you share the code snippet? Where should I add `action: 'submit'`?

![code](https://user-images.githubusercontent.com/16267321/59996005-15ec0580-966a-11e9-99d7-cef478fd1243.png)

**Comment by sabinayakc** [comment]
It is now working so closing the issue.
