### ISSUE TITLE
building form with schema

### ISSUE THREAD

**Issue by charbelkh** [formio/angular-formio#284]
is there a full documentation of what each form "type" does in schema and what each of the attributes are used to do(i mean within the component structure i have already seen the [form renderer wiki page](https://github.com/formio/angular-formio/wiki/Form-Renderer) )
thanks in advance

**Comment by travist** [comment]
We do have this https://github.com/formio/formio.js/wiki/Form-JSON-Schema but it needs to be updated with the latest. Is this not what you are looking for?

**Comment by charbelkh** [comment]
Yes this is very helpful. Thank you .
