### ISSUE TITLE
formio with json

### ISSUE THREAD

**Issue by charbelkh** [formio/angular-formio#288]
is there a way to use formio to generate a form that edits json files(autogenerate a schema or something)?

**Comment by travist** [comment]
that is what Form.io's builder does. Please look here for a demo of this.

https://formio.github.io/formio.js/app/builder

**Comment by charbelkh** [comment]
no i mean as in I provide a json file and that file is parsed into a form that has the data from the file so that is can be edited.

**Comment by randallknutson** [comment]
You can pass a submission object into the form as well to add data to the form using the submission attribute.

**Comment by randallknutson** [comment]
https://github.com/formio/angular-formio/wiki/Form-Renderer#inputs
