### ISSUE TITLE
Event Fired Twice

### ISSUE THREAD

**Issue by sanjaykrgaur** [formio/angular-formio#290]
Event attached to a button control is fired twice.
Steps to replicate:-

1. Place a button component on canvas.
2. Set its action as 'Event' and button event as 'Test'
3. Place a Textbox on canvas
4. In its logic tab add a new Event named 'Test'
5. Add action to the event and put console.log('1111'); in the Value(Javascript) field.
6. Now when the button is clicked '1111' is printed twice on console.

**Comment by wag110894** [comment]
Hello,
 
We have added this item to our backlog. We welcome a pull request for this item to be resolved or we have a process to expedite this issue if you are interested. Please send an email to support@form.io if you would like the price to expedite this for you.
 
Thanks.

**Comment by wag110894** [comment]
Hello, 

This should be resolved using Angular version 4.9.6. I hope that this helps.
