### ISSUE TITLE
refresh data source url in Select Component

### ISSUE THREAD

**Issue by pselis** [formio/angular-formio#291]
Hi,
is there a way to refresh data source in Select Component when "Data Source Type" =  URL?
Actually I have to reload the page to see the new values
Thanks for your help!

**Comment by travist** [comment]
Yes, this is what the "refresh on" setting is used for. You can set this select to something and it will refresh the values in the select component when that component within the "refresh on" configuration changes.

**Comment by pselis** [comment]
thanks for the response Travist,
unfortunately I had already tried without success.
even if I set the "refresh on" nothing happens.
also, if I use the "any change" value, I am no longer able to access the component settings from the builder

**Comment by travist** [comment]
Please provide a JSON or a jsfiddle showing the problem so we can investigate.

**Comment by sreesama** [comment]
I am also having the same issue. The url is executed once when the page is loaded first time and the data is showing up in drop down. But when i reopen the same page after some navigation, the url is not triggered. The same old data is showing up. If there is any change to the data during this time will not be available in drop down as the url is not triggered. I tried refreshOn as well, but no help, still the same old data and url is not triggered when i verify Network tab in developer tools.. 

My component details:
{
                                    "label" : "Site",
                                    "widget" : "choicesjs",
                                    "dataSrc" : "url",
                                    "data" : {
                                        "url" : "http://Some URL"
                                    },
                                    "valueProperty" : "",
                                    "template" : "<span>{{ item.name }}</span>",
                                    "validate" : {
                                        "required" : true,
                                        "unique" : false,
                                        "multiple" : false
                                    },
                                    "key" : "site",
                                    "type" : "select",
                                    "selectValues" : "value",
                                    "limit" : 10.0,

**Comment by thanhvietnguyen255** [comment]
Hi @pselis,
Has the issue been fixed yet? Could you please give me your solution?

**Comment by nageshyaho** [comment]
Hi @ghost!,
You can pass random key in your url (dont use it in query just pass it), it will give you new result.

> Hi @pselis,
> Has the issue been fixed yet? Could you please give me your solution?
