### ISSUE TITLE
design not displaying properly

### ISSUE THREAD

**Issue by lakhank143** [formio/angular-formio#292]
Hello,
I am newly integrating form.io in my angular 6 project. I want to implement the same functionality as formio form builder. 
I have installed formio package in my project using 
"npm install --save angular-formio"

`
<form-builder [form]="form" (change)="onChange($event)"></form-builder>
`

` 
@ViewChild('json') jsonElement?: ElementRef;
  public form: Object = {
    components: []
  };

 onChange(event) {
    this.jsonElement.nativeElement.innerHTML = '';
    this.jsonElement.nativeElement.appendChild(document.createTextNode(JSON.stringify(event.form, null, 4)));
  }
`

this is my html & ts code for form builder. drag & drop functionality working a bit fine but the issue is it is not displaying as same as displayed on form io website or in other demos.
do I miss anything to like CSS in my style file or anything else please help? 
the output will be like as displayed in the following image
![Untitled](https://user-images.githubusercontent.com/30143510/57185208-d401d700-6ee4-11e9-858e-2e1a462df483.png)

**Comment by travist** [comment]
Is your Angular application importing Bootstrap CSS? If not then that would cause this problem. For an example of how to do this, take a look @ https://github.com/formio/angular-demo/blob/master/src/styles.scss

**Comment by mouliraji** [comment]
I had the exact same issue, I could able to resolve by referring the bootstrap CSS and fonts in my index.html file.
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
