### ISSUE TITLE
Form Manager form search not working properly

### ISSUE THREAD

**Issue by DeBueno** [formio/angular-formio#297]
When I make a query filtering the forms and there are more than one page, the query is lost when I change the page.

I made a provisional solution changing the line 175 of grid.component.ts on ```refreshGrid(query?: any)```. It was

```javascript
query = query || {};
```

I changed to

```javascript
this.query = query || this.query;
```

If someone can look further into the issue, I'd appreciate.

Thanks!

**Comment by travist** [comment]
This looks reasonable. Please make a pull request and we will look into it.

**Comment by DeBueno** [comment]
Pull request made.
