### ISSUE TITLE
Cannot put language field : language.subscribe does not exists

### ISSUE THREAD

**Issue by samdidos** [formio/angular-formio#305]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: formio-enterprise (latest)
- angualr-formio version: 3.16.2
- Formio.js version: ^3.20.11
- Frontend framework: Angular 7
- Browser: Chrome 
- Browser version: 74

## Steps to Reproduce

1. Based approximately on the [PhraseApp example](https://help.form.io/tutorials/walkthroughs/phraseapp/)

2. Create an HTML page containing : 
```
    <formio
      [form]="form"
      [(submission)]="sub"
      [language]="translateService.currentLang"
      [options]="formOptions"
    ></formio>
```
3. Create an Angular component containing : 
```
ngOnInit() {
    const formio = new FormioService(`${this.config.appUrl}/${this.formName}`);

    formio.loadForm().subscribe(loadedForm => {
      this.formOptions = this.translate(loadedForm);
      this.form = loadedForm;
      if (this.formName === 'test') {
        this.sub = {
          data: {
            firstName: 'Hello',
            lastName: 'World',
          },
        };
      }
    });
  }
```
The `translate` function just parse the form JSON to retrieve labels of Form.io components and map our translations into the form options (i18n). 

## Expected behavior
The [language] tag should allow to switch form language when we change language and refresh the form.

## Observed behavior
Language seems not to be setted at all and I recieve this error in Chrome console : 
```
ERROR TypeError: this.language.subscribe is not a function
    at FormioComponent.push../node_modules/angular-formio/components/formio/formio.component.js.FormioComponent.ngOnInit
```

Any clue for this? In fact the only reason why I load the form is to be able to retrieve the labels that has to be translated, but if there is another way to retrieve them I could switch to using URL with [src] instead of [form]. I believe my problem is related to my use of the FormioService which is uncommon

**Comment by samdidos** [comment]
Even if I change back to a simple example, as soon as I add the `language` tag option, I got the same error, still no clue.

**Comment by samdidos** [comment]
Ok I've found my problem : language tag is expecting a EventEmitter, I was only using a string.

**Comment by ankitabhatt17** [comment]
Hello,  I have stcuk in the same issue. Her, I have even built an eventEmitter 

ngOninit(){
 this.getLanguage = new EventEmitter<string>();  this.getLanguage.emit(window.navigator.language.substring(0, 2));
}


But subscribe method is not called and my new language is not  set successfully.

@samdidos  Can you please help :)

Thanx in advance.

**Comment by samdidos** [comment]
Hi, assuming that you're using the same HTML formio tag of my issue, and assuming that you have populated your translations into the formio options tag (i18n), then what can help us to make your EventEmitter async (this.getLanguage = new EventEmitter(true); ). Else, you may have to reload the form, or use the refresh tag (another EventEmitter). Source code is very helpful since there's not a lot of documentation : https://github.com/formio/angular-formio/blob/master/src/components/formio/formio.component.ts

(Sorry for the formatting, I'm on my cellphone ;) )
