### ISSUE TITLE
[BUG] Angular-formio@3.18.0 has broken formiojs/core-js dependency? 

### ISSUE THREAD

**Issue by bh-adrienne** [formio/angular-formio#307]
## Environment
Please provide as many details as you can:
I have an angular application running using angular cli. 
When I upgraded angular-formio (to 3.18.0), I started getting lots (dozens!) of compile errors about the dependent formiojs "core-js" dependencies that looked like this

```
ERROR in ./node_modules/formiojs/components/password/Password.js
Module not found: Error: Can't resolve 'core-js/modules/web.dom-collections.iterator' in '(path to my application)/node_modules/formiojs/components/password'
```

My workaround for now was removing npm's formiojs and angular-formio and reinstalling 
at version 3.16.2.  

So: 
`npm install angular-formio@3.16.2`

Which leads me to believe this issue was introduced by a recent change in dependencies. 

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 3.22.0 is the FAILED version,  3.21.5 is the WORKAROUND installed version that still works. 
- Frontend framework: Angular
- Browser: n/a
- Browser version: n/a

## Steps to Reproduce
1.  In angular cli project, "npm install angular-formio@3.18.0"  results in the problem for me, as does just running "npm update angular-formio"

## Expected behavior
Latest package should work.

**Comment by travist** [comment]
We have upgraded the core-js to use 3.x in our latest builds. Does your application use core-js@2?

If so, then is it possible to upgrade to 3.x? If not, then maybe we need to add a hard dependency on angular-formio to 3.x so that it will install a local dependency on 3.x.

**Comment by bh-adrienne** [comment]
I don’t directly use core-js 2 or 3.  However, when I removed core-js and formiojs from my package.json and did a fresh install with angular-formio 3.18.0,  the resulting package-lock.json 
Installed core-js 2.6.9 instead of core-js@3, so if 3 is needed then you probably do need to add an ^3.0.0 dependency declaration of some variety.

It looks like there are some serious differences between the versions: 
https://github.com/zloirock/core-js/blob/master/docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md <https://github.com/zloirock/core-js/blob/master/docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md>

**Comment by travist** [comment]
Yes, I will make a new build that includes core-js as a dependency to this library which should resolve the problem.

**Comment by travist** [comment]
Please try version ```3.19.0``` and let me know if it resolves this problem.
