### ISSUE TITLE
Angular-formio   install 3.18.0  release  issue

### ISSUE THREAD

**Issue by kamleshmirani** [formio/angular-formio#310]
Hi There ,
 am  using formio version 3.11.5  in my project but from 11-6-2019  when new version of formio released   when i run  npm install its always install   3.18.0  latest version instead  of  formio version i have specified   in  package.json file..

**Comment by hallim** [comment]
Hi,
The caret ^ is more relaxed. It matches the most recent minor version (the second number).
The tilde ~ matches the most recent patch version (the third number) for the specified minor version (the second number). SO
In your package.json file replace: 
"angular-formio": "^3.11.5",
BY
"angular-formio": "~3.11.5",

**Comment by travist** [comment]
Is the issue you are seeing related to ```core-js```?  We upgraded this in our core renderer and should probably add a hard dependency on that in this library.

**Comment by travist** [comment]
Please try version ```3.19.0``` and let me know if it resolves this problem.

**Comment by hallim** [comment]
Me, I have version 3.16.2 of angular form-io installed, and the dependency of this version is formiojs with version 3.20.11.  But I have an issue of compatibility with core-js with new version of formiojs 3.22.x. So the workround to fix it is to make this change in my package.json of my angular project:
- replace "angular-formio": "^3.16.2", by "angular-formio": "~3.16.2",
- add this "formiojs": "~3.20.11",  
This work for me and the dependency formiojs installed is 3.20.17 and not 3.22.x

**Comment by travist** [comment]
The core-js issues should have been resolved with the latest release. Let me know otgerwise.
