### ISSUE TITLE
Need help Urgently

### ISSUE THREAD

**Issue by ankitabhatt17** [formio/angular-formio#312]
## Environment
Please provide as many details as you can:
https://github.com/formio/angular-formio/wiki/Translations

Here, 
createForm(document.getElementById('formio'), this.formURL, {
      language: 'en',  i18n: { 'en': { Submit: 'Complete' } }
    }).then(function(form) {
      window.setLanguage = function (lang) {
        form.language = lang;
      };
We have this code in angular 2 to set language. 

Can anyone help me what is the way to set the language in angular 8.

Code example is attached below. Where i can  pass language parameter in angular 8 code as shown in angular  2 implementations.

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version:
- Frontend framework:
- Browser:
- Browser version:

For code or form JSON, please enclose in a code block:

<form-builder [form]="form" (change)="onChange($event)"></form-builder>
@Component({
  ...
  ...
})
export class BuilderComponent {
  @ViewChild('json') jsonElement?: ElementRef;
  public form: Object = {
    components: []
  };

  onChange(event) {
    this.jsonElement.nativeElement.innerHTML = '';
    this.jsonElement.nativeElement.appendChild(document.createTextNode(JSON.stringify(event.form, null, 4)));
  }
}

**Comment by ankitabhatt17** [comment]
@peterblazejewicz @travist  @randallknutson @albertvolkman 

Thanx in advance.

**Comment by ankitabhatt17** [comment]
I found solution

<form-builder #formBuilder [form]="formResultJson" [options]="formBuilderConfig" (change)="onBuilderChange($event)"></form-builder>


And i have passed language in options

options  object constructed below:  { builder, editForm, i18n, language }

// Below is the form builder config format.
        const builder = {
            basic: false,
            advanced: false,
            data: false,
            layout: false,
            customBasic: {
                title: customConfig.customFormControls.title,
                default: customConfig.customFormControls.default,
                components: customConfig.customFormControls.components,
            },
        };
        const editForm = this.generateEditFormConfig(customConfig.controlTabsToIgnore, customConfig.controlOptionsToIgnore);
       // const i18n = { language : 'de' , de : { 'Text Field' : 'Ankita', 'Submit' : 'Ankita' , 'BUILDER' : 'Ankita' } };
        const i18n = { language : 'de' , de : {
            'Text Field': 'FRENTCH_Text Field',
            'Text Area': 'FRENCH_Text Area',
            'Number': 'FRENCH_Number',
            'Radio': 'FRENCH_RADIO',
            'checkbox': 'FRENCH_Checkbox',
            'Content': 'FRENCH_Content',
            'Select': 'FRENCH_Select',
            'Add Another': 'FRENCH_Add_Another',
            'Save': 'FRENCH_Save',
            'Cancel': 'FRENCH_Cancel',
            'Remove': 'FRECNH_Remove',
            'Display': 'FRENCH_Display',
            'Data': 'FRENCH_Data',
            'Label': 'FRENCH_Label',
            'Value': 'FRENCH_Value',
            'Edit': 'FRECNH_Edit',
            'Copy': 'FRENCH_Copy',
            'Paste': 'FRENCH_Paste',
            'Drag andDrop a form component': 'FRENCH_Drag andDrop a form component',
            'Text Field Component': 'FRENCH_Text Field Component',
            'Text Area Component': 'FRENCH_ Text Area Component',
            'Number Component': 'FRENCH_Number Component',
            'Radio Component': 'FRENCH_Radio Component',
            'Checkbox Component': 'FRENCH_Checkbox Component',
            'Content Component': 'FRENCH_Content Component',
            'Select Component': ' FRENCH_Select Component',
            'Placeholder': 'FRENCH_Placeholder',
            'Preview': 'FRENCH_Preview',
            'Default Value': 'FRENCH_Default Value',
            'Use Delimiter': 'FRENCH_Use Delimiter',
            'Values': 'FRENCH_Values',
            'Data Source Values': 'FRENCH_Data Source Values',
        } };
        const language = window.navigator.language.substring(0, 2);
        return { builder, editForm, i18n, language };

**Comment by ankitabhatt17** [comment]
<img width="962" alt="Finally" src="https://user-images.githubusercontent.com/29516159/59737486-78649080-927b-11e9-9baa-e282b2696bdc.PNG">

**Comment by ankitabhatt17** [comment]
Hope this helps to someone :)

**Comment by felipebelluco** [comment]
@ankitabhatt17 thanks for sharing the solution. I also spotted in your solution these lines:

`const editForm = this.generateEditFormConfig(customConfig.controlTabsToIgnore, customConfig.controlOptionsToIgnore`

Can you show these classes, because I'm having a hard time trying to hide tabs and options from editForm dialog.

Thank you in advance.

**Comment by IParthJoshi** [comment]
@felipebelluco  here is what you might wanna checkout and manipulate as your need.
[http://formio.github.io/formio.js/app/examples/custombuilder.html](url)

This is how you could ignore tabs and options too  :

`editForm: {
    textfield: [
      {
        key: 'api',
        ignore: true
      }        
    ]
  }`

**Comment by felipebelluco** [comment]
@IParthJoshi this code ignores the whole API tab, but how can I ignore a particular option in a tab, like the placeholder option in the display tab, for instance? I've tried the following but it was unsuccessful:

`editForm: { textfield: [ { key: 'placeholder', ignore: true } ] }`

**Comment by IParthJoshi** [comment]
Do this @felipebelluco .
`editForm: { textfield: [ { key: 'display', components: [ { key: 'placeholder', ignore: true } ] } ] }`
work like charm!

**Comment by felipebelluco** [comment]
@IParthJoshi indeed it works like a charm! That's exactly what I was looking for. Thank you very much!

**Comment by efortes** [comment]
I spend quite some time finding a way to set a default language (No typescript info was available). Maybe this will help somebody else with the same issue

**Html**
```
<formio
  *ngIf="!submitCompleteText"
  #form
  [renderOptions]="renderOptions"
  (submit)="onSubmit($event)"
  url="https://fake.nl"
  [options]="formioOptions"
  src="https://dev-jwgbgzgzihxbonf.form.io/{{ formid }}"
></formio>
```

**Code**:
```
  renderOptions = {
    language: 'nl'
  }

  formioOptions: FormioOptions = {
    i18n: {
      resources: {
        nl: {
          translation: FORM_IO_I18N_NL
        }
      }
    },
    hooks: {
      beforeSubmit: this.beforeSubmit.bind(this)
    }
  }
```

**Comment by efortes** [comment]
@wag110894 this is no issue. I added this comment just to show other developers how I set the default lang with renderOptions ( in case they have similar issues ). I could not get it to work with this article: https://github.com/formio/angular-formio/wiki/Translations

**Comment by wag110894** [comment]
Apologies. Thanks for adding.
