### ISSUE TITLE
[Question]  FormioResourceService and FormioAuthService together? 

### ISSUE THREAD

**Issue by bh-adrienne** [formio/angular-formio#317]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: "3.21.5"
- Frontend framework: Angular 7
- Browser: firefox
- Browser version: developer edition

## Steps to Reproduce
1.  Follow the Wiki documentation on how to use the FormioAuthService. (I verified that I do get an authorized login)
2. Follow the Wiki documentation on setting up CRUD routes with FormioResourceService. 
3. Set all formio roles on the resource form to "Anonymous"- verified that my CRUD routes are set up as the wiki + demo example allow.
4. Change the formio roles on the resource to only allow role "Authenticated" for CRUD options.

## Expected behavior
FormioAuthService and FormioResourceService should work together in some way with some configuration? 

## Observed behavior
My FormioAuthService calls work and are successful. My code calls 
"this.service.onLoginSubmit(result);" after login and I get no errors, and later calls to FormioAuthService.getUser when I load my crud component DO return the authenticated user and their roles.
My FormioResourceService also works perfectly (set up as documented in the wiki)... when all the CRUD settings on the form access are set to "Anonymous". 
 
It's just that the FormioResourceService doesn't seem to know about the FormioAuthService- so later when I use the FormioResourceService, no auth tokens or anything are included.

This is my second attempt at using the authentication, and the whole reason I'm doing it is because it is heavily implied that this is supposed to be handled in Formiojs and not by my code manually in this issue: 
https://github.com/formio/angular-formio/issues/265

Can someone add to the Wiki or to the demo sample the correct way of making these 2 services work together? Combined in a single component, for example?

**Comment by travist** [comment]
The FormioAuthService just needs to be "provided" at the "root" module within your application. Then it will be consumed by any Resource services within that application.

**Comment by bh-adrienne** [comment]
I have this in the custom config of my top level app.module.ts already: 
```
  providers: [
 FormioAuthService,
    {
      provide: FormioAuthConfig,
      useValue: MyCustomAuthConfig
    }]
```

And my resource module provides the resource service: 
```
providers: [
    FormioResourceService,
    {
      provide: FormioResourceConfig,
      useValue: {
        name: "application",
        form: "application"
      }
    }
```
That alone is not enough for the Resource services I use on my components to authentication.

**Comment by bh-adrienne** [comment]
Thanks- between going back and looking at the FormioAuthService source code more carefully, I was able to find the bug in my code causing the authentication to fail. For anyone in the future reading this, my custom extended formio resource login component was using the documented postman API url "/user/login", instead of using "/user/login/submission", which, while it does authenticate, does not result in the authenticated token being saved properly using this service. Kind of wish the angular component/Formiojs  usage and the publicly posted API url lined up here, but they dont.
