### ISSUE TITLE
How to integrate formio and formbuilder in angular 7 application

### ISSUE THREAD

**Issue by Theaggarwal** [formio/angular-formio#320]
Hi, In my angular 7 project, i am using a library that uses core-js version 2.6.9. So i have installed below versions:
"angular-formio": "3.16.0",
"formiojs": "3.20.9"

Now on using &lt;form-builder&gt; and &lt;formio&gt; i got an error 'form-builder' is not a known element. i tried various ways but all in-vain. Please suggest @travist how can i use them. in documents, i found we only need to install packages and include the FormioModule in our module. please help.

In my app.module i wrote the following:
import { FormioModule } from 'angular-formio';
@NgModule({
imports: [FormioModule]
....
});

**Comment by travist** [comment]
This works fine. Please refer to the Angular Demo application to see if there is anything you are doing different in your application.  https://github.com/formio/angular-demo

**Comment by learner291** [comment]
> 
> 
> Hi, In my angular 7 project, i am using a library that uses core-js version 2.6.9. So i have installed below versions:
> "angular-formio": "3.16.0",
> "formiojs": "3.20.9"
> 
> Now on using <form-builder> and <formio> i got an error 'form-builder' is not a known element. i tried various ways but all in-vain. Please suggest @travist how can i use them. in documents, i found we only need to install packages and include the FormioModule in our module. please help.
> 
> In my app.module i wrote the following:
> import { FormioModule } from 'angular-formio';
> @NgModule({
> imports: [FormioModule]
> ....
> });

I am receiving the same error on formio, did you manage to fix this issue?

**Comment by travist** [comment]
We have moved on from Angular 7, so we will not be able to provide support for this. Maybe someone from the community has ran into this problem and has a solution?
