### ISSUE TITLE
Multi tenant - sharing forms between the tenants

### ISSUE THREAD

**Issue by padhumailin** [formio/angular-formio#325]
Is possible to share same forms between two or more tenants? 
Is possible to customize forms specific to tenants for example hiding / showing some components?

is there any sample angular project implementing multi tenants?

**Comment by travist** [comment]
We do have this as a feature of our commercial solution. Please reach out to support@form.io and we can demo this to you.

**Comment by padhumailin** [comment]
Is there any documentation related to multi tenant features available?

**Comment by wag110894** [comment]
We currently do not have documentation available yet for multi tenancy. We will add it to our backlogs.
