### ISSUE TITLE
How to customize the formbuilder with angular-starterkit

### ISSUE THREAD

**Issue by kkhanhluu** [formio/angular-formio#329]
Hi, 
I am new to form.io. I used the angular starter kit and everything works fine, but i need to customize the formbuilder when directing to localhost:4200/forms/:id/edit. How can I do this? Under Form folder of starter kit i see only the form.module.ts and form.module.spec.ts files. 
Many thanks

**Comment by gilsdav** [comment]
Using something like this ?
```
RouterModule.forChild(FormManagerRoutes({
    formEdit: MyEditComponent
}))
```

Refer to https://github.com/formio/angular-formio/tree/master/src/manager/edit to create your own edit component.

**Comment by kkhanhluu** [comment]
@gilsdav thanks i get it now. I want to create a "copy form" button like this in formio.portal 
![image](https://user-images.githubusercontent.com/38130967/61788176-bcfec100-ae11-11e9-9394-8191338b24f3.png). Do you have any reference?

**Comment by gilsdav** [comment]
I guess you can copy your form and perform this on it :
```
// Reset ID
this.form._id = undefined;

// Change title
this.form.title = this.form.title + '_copy';

// Change to unique name
this.form.name = _.camelCase(this.form.title).toLowerCase(); 

// Change to unique path
this.form.path = this.form.name;

// Save new form
return this.service.formio.saveForm(this.form).then(form => {

    // Redirect to new form
    this.router.navigate(['../../', form._id, 'view'], {relativeTo: this.route});

});
```
Referred to: https://github.com/formio/angular-formio/blob/master/src/manager/edit/edit.component.ts
