### ISSUE TITLE
[BUG] Edit dialog for custom component is not opening

### ISSUE THREAD

**Issue by imshivamchauhan** [formio/angular-formio#332]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 3.23.0
- Frontend framework: 3.22.0
- Browser: chrome
- Browser version: latest

## Steps to Reproduce
1. Drag custom component, (i have created a component file-preview). & save.
2. Now re-edit custom component, it opens dialog with no content(seems no view has rendered in dialog)
3. on console, it shows some error also (undefined of something)

## Expected behavior
dialog should open & user should be able to reedit the custom component from dialog.
## Observed behavior
but dialog opens but there is no view in dialog.

**Comment by wag110894** [comment]
Hello Shivam,

Can you provide a screenshot of the error?

Thanks.

**Comment by imshivamchauhan** [comment]
screenshot of error: (after clicking on edit icon of custom component)

![image](https://user-images.githubusercontent.com/33184564/61628451-f8797e00-ac9f-11e9-8c86-4950b5c32156.png)

**Comment by imshivamchauhan** [comment]
changed the implemenation of custom component & upgraded to latest version fixed this.
