### ISSUE TITLE
FormioModule causing zone.js Error

### ISSUE THREAD

**Issue by xamlzealot** [formio/angular-formio#333]
`Error: Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten.
Most likely cause is that a Promise polyfill has been loaded after Zone.js (Polyfilling Promise api is not necessary when zone.js is loaded. If you must load one, do so before loading zone.js.)
    at Function.push../node_modules/zone.js/dist/zone.js.Zone.assertZonePatched (zone.js:58)
    at new NgZone (core.js:13726)
    at getNgZone (core.js:14409)
    at PlatformRef.push../node_modules/@angular/core/fesm5/core.js.PlatformRef.bootstrapModuleFactory (core.js:14307)
    at core.js:14351
    at es.promise.js:105`

This error shows in my console whenever I add **_FormioModule_** to to my imports. Creating a module with Angular CLI and doing nothing except importing FormioModule (below), the ZoneAwarePromise error occors and nothing loads in my browser.

`import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';

import { DesignerComponent } from './Designer/designer/designer.component';
import { FormioModule } from 'angular-formio';

@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    **_FormioModule_**
  ],
  declarations: [DesignerComponent]
})
export class UICompositionModule { }
`

If I comment or remove the FormioModule import, the application loads correctly. I've not even added a component to render it anywhere, I've only imported it into my module.

Most of my research indicates that it's a loading sequence error, but I've no clue how to resolve it. Any help tracking down the issue or developing a work around?

NOTE: This same solution works FINE in a standalone project, that is, an Angular project created via command line and installing angular-formio. It's obviously a collision somewhere, but I hope to solicit some guidance in tracking it down.

Thanks in advance.

**Comment by aiwebb** [comment]
What version(s) of `angular-formio` are you observing this issue in? I know there was a window recently where we were seeing this happen, but I believe it was resolved - can you check and confirm the version?

**Comment by xamlzealot** [comment]
"dependencies": {
    "@angular-devkit/build-webpack": "^0.13.8",
    "@angular-devkit/core": "7.0.2",
    "@angular/animations": "^7.0.0",
    "@angular/cdk": "^7.0.0",
    "@angular/common": "7.0.0",
    "@angular/compiler": "7.0.0",
    "@angular/core": "7.0.0",
    "@angular/flex-layout": "^7.0.0-beta.24",
    "@angular/forms": "7.0.0",
    "@angular/http": "7.0.0",
    "@angular/material": "^7.0.0",
    "@angular/material-moment-adapter": "^7.0.0",
    "@angular/platform-browser": "7.0.0",
    "@angular/platform-browser-dynamic": "7.0.0",
    "@angular/router": "7.0.0",
    "@auth0/angular-jwt": "^2.1.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.18",
    "@ngx-formly/core": "^5.1.9",
    "@ngx-formly/kendo": "^5.1.9",
    "@ngx-formly/material": "^5.1.9",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "@progress/kendo-angular-buttons": "^4.4.2",
    "@progress/kendo-angular-dateinputs": "^3.7.4",
    "@progress/kendo-angular-dropdowns": "^3.5.5",
    "@progress/kendo-angular-excel-export": "^2.4.0",
    "@progress/kendo-angular-grid": "^3.14.3",
    "@progress/kendo-angular-inputs": "^5.2.0",
    "@progress/kendo-angular-intl": "^1.7.1",
    "@progress/kendo-angular-l10n": "^1.4.1",
    "@progress/kendo-angular-popup": "^2.0.0",
    "@progress/kendo-angular-ripple": "^1.2.0",
    "@progress/kendo-data-query": "^1.5.1",
    "@progress/kendo-drawing": "^1.5.12",
    "@progress/kendo-theme-default": "latest",
    "@progress/kendo-theme-material": "^2.5.1",
    "@progress/kendo-ui": "^2019.2.529",
    "@swimlane/ngx-charts": "^7.0.1",
    "@swimlane/ngx-datatable": "^11.1.5",
    "@types/applicationinsights-js": "^1.0.9",
    "ag-grid": "^18.1.2",
    "ag-grid-angular": "^20.2.0",
    "ag-grid-community": "^20.2.0",
    "angular-calendar": "^0.22.1",
    "angular-font-awesome": "^3.1.2",
    **"angular-formio": "^4.0.0-beta.6",**
    "angular-oauth2-oidc": "^5.0.2",
    "angular6-json-schema-form": "^7.1.0",
    "applicationinsights-js": "^1.0.20",
    "bpmn-js": "^3.2.2",
    "bpmn-js-properties-panel": "^0.29.0",
    "chartist": "^0.11.0",
    "compodoc": "0.0.41",
    "core-js": "^2.4.1",
    "d3": "^4.8.0",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "jquery": "^3.2.1",
    "lodash-es": "^4.17.11",
    "md5": "^2.2.1",
    "moment": "^2.20.0",
    "ng-chartist": "1.1.1",
    "ng2-charts": "1.6.0",
    "ng2-dragula": "1.5.0",
    "ng2-file-upload": "1.3.0",
    "ng2-smart-table": "1.2.2",
    "ng2-validation": "^4.2.0",
    "ngx-formly-tabs": "^5.1.0",
    "ngx-perfect-scrollbar": "^5.0.0",
    "ngx-quill": "^3.1.0",
    "quill": "^1.3.6",
    "ramda": "^0.26.1",
    "rxjs": "^6.4.0",
    "rxjs-compat": "^6.2.0",
    "rxjs-tslint": "^0.1.4",
    "save-svg-as-png": "^1.4.12",
    "ts-md5": "^1.2.4",
    "zone.js": "^0.8.26"
  }

**Comment by travist** [comment]
Not sure why this is getting thrown, but I do know that you can get past this issue by moving the following line out of **src/polyfills.ts**

```
import 'zone.js/dist/zone';
```

and then move it to **src/main.ts** in the following spot.

```
...
...
import { AppModule } from './app/app.module';
import { environment } from './environments/environment';
import 'zone.js/dist/zone';
```

**Comment by travist** [comment]
This is now fixed in the latest builds.
