### ISSUE TITLE
Customize FormGridBody

### ISSUE THREAD

**Issue by kkhanhluu** [formio/angular-formio#334]
Is there any way to override the FormGridBody? I want to add a button to this row 
![image](https://user-images.githubusercontent.com/38130967/61793570-bb3bfa00-ae1f-11e9-9bec-facccd3822f7.png)

**Comment by travist** [comment]
Yes, just extend it, and then pass that as the ```[components]``` property when you embed the ```<formio-grid>``` in your application.
