### ISSUE TITLE
Add custom headers

### ISSUE THREAD

**Issue by biaigi** [formio/angular-formio#335]
Hello,
I need to add a dynamic custom header to loading and saving calls.
I'm using thge latest version of angular-formio, I noticed that this logic is found in the formio.js.
How can I intercept http calls to manipulate the request?
I have tried to intercept this calls with an Angular HttpInterceptor, but it doesn't seems to work.
The 'beforeSubmit' event doesn't help me since in the callback 
I don't have the formio object available, but only the submission object.

Thanks, see you soon

**Comment by travist** [comment]
The way to do this is to create a Form.io Plugin as documented @ https://github.com/formio/formio.js/wiki/JavaScript-API#plugin-api.
