### ISSUE TITLE
SelectBoxes component spams 'console.log('checkValidity', data, dirty, rowData);'

### ISSUE THREAD

**Issue by xellafe** [formio/angular-formio#339]
I'm using a SelectBoxes component ad it prints this message every time I make a change in the form. It's quite frustrating :D

Version: 4.0.0-beta.7

**Comment by aiwebb** [comment]
Thanks @xellafe, we'll be sure to clean that up!

**Comment by xellafe** [comment]
After a second look I noticed that the problem is in formiojs library, it's not your fault.

I'll close ths and report to them.
