### ISSUE TITLE
Nested form in open source code

### ISSUE THREAD

**Issue by dmenne** [formio/angular-formio#349]
Nested form via designer is only available in the Premium Edition. Do you have an example how to obtain an hierarchy with the open source code?

**Comment by travist** [comment]
You can add nested forms in Open Source. It is called the "form" component in advanced section I believe.

**Comment by dmenne** [comment]
If someone else reads it: this is a bit misleading in the video where the nested form appears in the Premium panel. It is in the in advance panel in the open source version as mentioned by @travist.

**Comment by dmenne** [comment]
I have to correct me again: This was 3.7.x. In 4.0 it is in Premium/Nested Form, so the way it is shown in the video is correct.
