### ISSUE TITLE
[BUG] Angular-formio 4.x endlessly shows spinner when trying to render a form with nested form component

### ISSUE THREAD

**Issue by Alena-Levina** [formio/angular-formio#357]
## Environment
- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 4.0.0-rc.42
- Frontend framework: Angular 8, with angular-formio v. 4.0.0-rc.4
- Browser: Chrome
- Browser version: 78.0.3899.0

## Steps to Reproduce
1. Use angular-demo repo on 4.x branch
2. In home.component.html change src for ```<formio>``` component to https://wblpvssfqjsszgb.form.io/form/5d6902ec723d64ae07bcd37e
3. Run ng serve and check how form is rendered 

## Expected behavior
Form should be rendered, spinner should get hidden

## Observed behavior
Form is rendered, but spinner doesn't get hidden

## Example
[Screenshot](https://www.screencast.com/t/RrgyaSwtEaOP )

**Comment by aiwebb** [comment]
Working in latest.
