### ISSUE TITLE
[BUG] Phone Number Component doesn't accept multiple Input Mask

### ISSUE THREAD

**Issue by kamaloush** [formio/angular-formio#359]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [X] Local deployment
    - Version: 
- Formio.js version: latest 4.x
- Frontend framework: Ionic
- Browser: Chrome
- Browser version: Version 76.0.3809.132 (Build officiel) (64 bits)

## Steps to Reproduce
1. Add a phone number component in form builder and add multiple input mask into the options of that new component

## Expected behavior
Same behaviour as version 3.X
## Observed behavior
The component is not recognized anymore, the preview in form builder modal says 'Unknown component', and the select of input mask doesn't work on form submission mode

**Comment by jhen1422** [comment]
@kamaloush 
Thank you for the report. Please utilize the 'Textfield' component to implement multiple input mask functionality. The phone number component was not intended to carry the 'Multiple Input Mask' setting.

**Comment by kamaloush** [comment]
The 'TextField' component doesn't work either with multiple input mask.

**Comment by wag110894** [comment]
Apologies, 

We have this issue in our backlog. We welcome a pull request for this item to be resolved or we have a process to expedite this issue if you are interested. Please send an email to support@form.io if you would like the price to expedite this for you.
 
Thanks.
