### ISSUE TITLE
issue with appUrl configuration in latest release 4.0.2

### ISSUE THREAD

**Issue by dolphinsd** [formio/angular-formio#364]
FYI going back to 3.6.12 and issues disappear.

We running Angular 8.2.6

We used to use dynamic appUrl property like this:
export const BuilderConfig = {
    appUrl: () => window.location.origin,
    apiUrl: 'https://localhost'
};

latest version fails to init with javascript error:
ERROR TypeError: path.search is not a function
at Formio.js
line var isProjectUrl = path.search(projectRegEx) !== -1; // The baseURL is the same as the projectUrl, and does not contain "/project/MONGO_ID" in

**Comment by travist** [comment]
Please submit a pull request to our core and we will pull in the fix to our next renderer. Otherwise, we will add this to our bug list and get to it as soon as we can.

**Comment by dolphinsd** [comment]
@travist  we went back to 3.6.12 as all the issues disappear.
what ever is on the head in release is not stable. it works for your demo, but breaks in the apps that using previous version.

**Comment by travist** [comment]
@dolphinsd please provide us a fiddle of the issue occurring. We are not having any problems on our side with this so unless we can reproduce it, it may not ever get fixed and you will be stuck on that version.

**Comment by dolphinsd** [comment]
@travist , you do not need fiddle, just replace 
config.ts in your demo https://github.com/formio/angular-demo with this and run and you will see error
export const AppConfig = {
  appUrl: () => window.location.origin,
  apiUrl: ''
};

**Comment by dolphinsd** [comment]
@travist , this is from latest release 4.2.2 in your demo app
![image](https://user-images.githubusercontent.com/3460517/65982033-3547bb00-e42f-11e9-9508-1935f4ddac9d.png)

**Comment by travist** [comment]
AppConfig.appUrl should not be a function. It should be a string. What happens when you use the following.

```
export const AppConfig = {
appUrl: window.location.origin,
apiUrl: ''
};
```

**Comment by dolphinsd** [comment]
@travist , now  window.location.origin works in latest release
