### ISSUE TITLE
Question on Hidden Values

### ISSUE THREAD

**Issue by lailapfit** [formio/angular-formio#367]
Not a bug - just a question regarding hidden/disabled values:

Is this possible?

I am looking to make a Text Area component to be hidden when it is rendered, but the User can edit the component afterwards.

**Comment by aiwebb** [comment]
@lailapfit, you can reference the `submission` object in conditional rendering, e.g.:

```js
show = !!submission.created
```

This will render a field only if a submission has already been made; it won't be visible during the initial submission of the form, but will be visible when viewing the submission after the fact.

**Comment by lailapfit** [comment]
@aiwebb Thank you so much!! It works beautifully.
