### ISSUE TITLE
[BUG] datagrid validation malfunctioning

### ISSUE THREAD

**Issue by imshivamchauhan** [formio/angular-formio#370]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
- Formio.js version: latest
- Frontend framework: MEAN, angular-formio
- Browser: chrome, mozilla
- Browser version: latest

## Steps to Reproduce
1. Add DataGrid to form & add some text, select component with required validation in it & save the form.
2. On submit button setting, untick the disabled on form invalid checkbox.
3. Now open the above form in renderer, fill first row in datagrid with valid data.
4.  Click on add another row, and now Remove that same row, now hit submit.

## Expected behavior
It should submit the form properly.
## Observed behavior
Its showing validation errors for the deleted row also & stopping form from submitting.
@travist @randallknutson

**Comment by jhen1422** [comment]
@imshivamchauhan 
Thank you for the report. We were able to replicate this issue on our end as well and have created a ticket for the issue. We will review during our planning meeting next week. Please note, we welcome pull requests in this library. If you need this item expedited, please feel free to contact support@form.io for pricing.

**Comment by sanjaykrgaur** [comment]
I guess in Datagrid.js "removeRow" function you have to splice this.components as well to fix this

**Comment by travist** [comment]
@sanjaykrgaur if you have an idea where to resolve this issue, please submit a pull request with your change and we will take a look.

**Comment by jhen1422** [comment]
This issue has been resolved on the latest version of formio.js
