### ISSUE TITLE
Reset form after submit or execute 'submitDone' event

### ISSUE THREAD

**Issue by gladkiy** [formio/angular-formio#379]
I created form and want to submit values, here is my code:
```
onSubmit(submission) {
    this.model.dataJSON = JSON.stringify(submission.data);
    this.containerService.saveFormData(this.model).subscribe((response: Json) => {
       //todo something
    });
}
```

but when service method was executed then I see on page `Submit` button with loading and alert at the top `Submission Complete.`

How can I reset this? Or maybe execute `submitDone` event somehow?

**Comment by travist** [comment]
You can add the following to the renderer.

```
<formio [success]="successEmitter" ...></formio>
```

And then in your logic, you can emit your own event like this.

```
public successEmitter: EventEmitter<any>;

onSubmit(submission) {
  this.successEmitter.emit('Yay!!!!!');
}
```

**Comment by gladkiy** [comment]
Unfortunatelly this code just changed message at the top "Submission Complete." -> "Yay!!!!!" but loader near "Submit" button was left

**Comment by shai93** [comment]
I solved this in angular-formio. @travist @gladkiy 
Using the ready event I got a current form instance and then call it in onSubmit function
```
<formio  (ready)="ready($event)" [success]="successEmitter" (submit)="onSubmit($event)"> </formio>

// ready function
ready(event){
    this.currentForm = event.formio;
}

//onsubmit function
onSubmit(submission){ 
    this.successEmitter.emit('Created Successfully');
    this.currentForm.emit('submitDone') //call submitdone event here to stop loading
}
```
