### ISSUE TITLE
[BUG] setBaseUrl and setProjectUrl has no affect

### ISSUE THREAD

**Issue by dolphinsd** [formio/angular-formio#382]
When we used  it has no affect, it always default to localhost:4200 for the form
Formio.setBaseUrl('http://myurl');
Formio.setProjectUrl('http://myurl');

Looks like this line Webformbuilder always overrides it with default
var formio = new _Formio.default(_Formio.default.projectUrl);

For example, if file uploaded, it still calls http://localhost:4200/storage/dropbox instead of  projectUrl set

How to we set base and project url to something else?

**Comment by travist** [comment]
You need to provide your AppConfig provider seen here https://github.com/formio/angular-demo/blob/master/src/app/app.module.ts#L67
