### ISSUE TITLE
[BUG] Upgrade Angular-Formio to be able to use patch for File Upload Unexpected token * in JSON at position 1 issue #1789 

### ISSUE THREAD

**Issue by gismomtl** [formio/angular-formio#383]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [X ] Local deployment
- Formio.js version: 4.2.9

current bug https://github.com/formio/formio.js/issues/1789 on File Upload regarding Unexpected token * in JSON at position 1 should be solved.
However formio.js update is not reflected in latest angular-formio version.

Can you upgrade angular-formio so the fix will work through angular?
Thanks

**Comment by travist** [comment]
done.
