### ISSUE TITLE
[HELP] example of how to create custom storage provider in angular

### ISSUE THREAD

**Issue by dolphinsd** [formio/angular-formio#384]
Is there an example of how to create/add custom storage provider in angular?

If not, do we just add a copy cut of https://github.com/formio/formio.js/blob/ab71aa60905191b6445dfd22ee34da1c28d51277/src/providers/storage/url.js and appears?

How do we remove, disable other providers from the list?

Thanks for insight

**Comment by randallknutson** [comment]
The URL provider should work for most use cases so you may not need to fork it. This is where the storage options setting is: https://github.com/formio/formio.js/blob/master/src/components/file/editForm/File.edit.file.js#L5-L23

You could modify that using a custom form builder to remove the other options from the list and only provide the one you want (and call it whatever you want). You can modify it like this http://formio.github.io/formio.js/app/examples/custombuilder.html near the bottom where editform: textfield is it shows how to override specific fields.

**Comment by dolphinsd** [comment]
@randallknutson thanks for the insight. Have you consider more user/developer friendly approach, where for example init options allows you to turn on/off components, and providers?

**Comment by dolphinsd** [comment]
Here is a simple way to nuke all storage providers  Formio.providers.storage = [];

**Comment by travist** [comment]
Pull requests welcome.

**Comment by dolphinsd** [comment]
Here is a solution for your reference @Injectable()
export class MyStorageProvider {

    constructor()
    {
    }

    static get title() {
        return 'MyStorageProvider';
    }

    
    uploadFile(file, name, dir, progressCallback, url, options): NativePromise {

        return new NativePromise((resolve, reject) => {
        });
    }
   
    deleteFile(fileInfo) {

        return new NativePromise((resolve, reject) => {
        });
    }

    downloadFile(file) {

        return new NativePromise((resolve, reject) => {
         

        });
    }
}

if (Formio) {
    Formio.providers.storage = { MyStorageProvider };
}

**Comment by jesusduranevenbytes** [comment]
@dolphinsd can you explain a bit how you structure your code?

I have created a class like MyStorageProvider where I'll handle the file uploads/downloads. How do I add it as a storage provider? Where do you modify the Formio object? I have tried setting it in both the component which shows the form and the App Component, and it didn't work.

In both cases, when I select a file to upload from my PC, I get the error "Storage provider not found". How can I register it correctly?

Also, when I import the Formio from _angular-formio_ library, its providers property is undefined, so I have to do
```
if (Formio) {
	Formio.providers = {
		storage: { CustomFileProviderService }
	}
}
```
I am loading my schemas from an API, and loading them using an event emitter specified in the refresh property of the formio HTML element. Am I missing something initializing the Formio object?

Thank you.
