### ISSUE TITLE
How to register the angular custom component to the formio builder that can be drag and drop to the builder?

### ISSUE THREAD

**Issue by Dheeraj-Bharti** [formio/angular-formio#385]
Hello,

we would like to add an angular custom component which is already registered to the formio 
to the formio builder.
https://github.com/formio/angular-formio/issues/201 , this link provide information regarding how to register the custom component to the formio renderer. 
But I want to make that component visible to the formio builder as well. Can you please help us for the same.
I would be really grateful for your help.

Thanks a lot and best regards,
Dheeraj

**Comment by travist** [comment]
The angular-demo shows an example of how to do this like the following. https://github.com/formio/angular-demo/blob/master/src/app/app.module.ts#L23

**Comment by merobal** [comment]
If you want to register an Angular component, you can do that with the latest version (v4.3 and above). Check the documentation: https://github.com/formio/angular-formio/wiki/Custom-Components-with-Angular-Elements
