### ISSUE TITLE
 Error: Unexpected value 'undefined' imported by the module 'DynamicTestModule'

### ISSUE THREAD

**Issue by SarojPoudel** [formio/angular-formio#392]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
- Formio.js version: 4.6.1
- Frontend framework: Angular 8
- Browser: Chrome
- Browser version: 

## Expected behavior
no error
## Observed behavior
After I updated angular-formio from version 3.16.2 to 4.2.12, my unit tests are failing wherever I have imported FormioModule and set provider as FormioAppConfig.  

Here is the code.
```js
import { async, ComponentFixture, TestBed } from '@angular/core/testing';


import { FormModalComponent } from './form-modal.component';

import { FormioModule, FormioAppConfig } from 'angular-formio';
import { NgbActiveModal } from '@ng-bootstrap/ng-bootstrap';
import { configureTestSuite } from 'ng-bullet';
import {ReactiveFormsModule} from "@angular/forms";

describe('FormModalComponent', () => {
  let component: FormModalComponent;
  let fixture: ComponentFixture<FormModalComponent>;

  configureTestSuite(() => {
    TestBed.configureTestingModule({
      declarations: [FormModalComponent],
      imports: [FormioModule, ReactiveFormsModule ],
      providers: [ FormioAppConfig, NgbActiveModal]
    });
  });

  beforeEach(() => {
    fixture = TestBed.createComponent(FormModalComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});
```

**Comment by travist** [comment]
I will take a look, but curious if anyone else is having this problem?

**Comment by jbarrus** [comment]
This seems to be related to using jest unit tests with angular.

**Comment by jbarrus** [comment]
I think I found the problem, though I'm not sure yet what's causing it. The umd bundle created only has a single export - the SubmissionComponent. This is consistent with what I'm seeing from jest.

https://unpkg.com/angular-formio@4.2.12/angular-formio.umd.js

When I output the result of `import * as Formio from 'angular-formio'` I get:
` { SubmissionComponent:
       { [Function: SubmissionComponent] decorators: [ [Object] ], ctorParameters: [Function] } }`
