### ISSUE TITLE
change event was not triggering while we remove component from form builder

### ISSUE THREAD

**Issue by skmuzeer** [formio/angular-formio#394]
Hi Team,

Facing an issues in angular-formio related to change event. Whenever we remove a field it was not triggering the change function.
Even if we edit the field and click on remove button still it remains the same in json but it will remove from the UI.

I have debug and understand the change event types which are triggering as of now are addcomponent, updatecomponent and savecomponent but removecomponent was not triggering

Kindly help me out by fixing this issue asap

**Comment by aiwebb** [comment]
@skmuzeer Are you able to submit a JSFiddle that shows this?

**Comment by merobal** [comment]
Are you using the latest version? A fix was applied at formio.js v4.4.1 (angular-formio v4.2.9 and above): https://github.com/formio/formio.js/pull/1900

Also the "removeComponent" is named as "deleteComponent" in angular-formio.

**Comment by skmuzeer** [comment]
@merobal @aiwebb Thanks guys 
Initially was using version 4.0.2 now it was working with 4.2.0 looks like latest version was in beta so I have used 4.2.0
