### ISSUE TITLE
[BUG] Angular Form.IO doesn't render on IE11

### ISSUE THREAD

**Issue by ihildebrandt** [formio/angular-formio#399]
## Environment
Please provide as many details as you can: 

- Hosting type
  - [X] Angular Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version:
- Frontend framework:
- Browser: IE11
- Browser version: 11.1069.17134.0

## Steps to Reproduce
1. Open IE-11 
2. Navigate to https://formio.github.io/angular-demo/

## Expected behavior
I should see the formio demo. 

## Observed behavior
I don't see the formio demo.

## Example
From some local experimentation that I did, this seems to be an issue with some es6 format js files not getting transpiled. 

The first errors reported in the IE console were in: `@formio/bootstrap3/lib/templates/bootstrap3/iconClass.js`

When I manually changed the syntax to es5 the errors went away. I didn't go far enough with my changes to get formio to render, but I imagine that it would eventually work. 

This issue doesn't happen with formio.js, only with the Angular version.

**Comment by merobal** [comment]
@travist I checked now and it broke our setup too. It's because the new template libs aren't compiled to legacy formats (so it contains new features e.g. arrow functions or template strings) and the Angular CLI's webpack can't really compile external libs...

**Comment by wag110894** [comment]
We have added this item to our backlog. We welcome a pull request for this item to be resolved or we have a process to expedite this issue if you are interested. Please send an email to support@form.io if you would like the price to expedite this for you.
 
Thanks.

**Comment by elibus** [comment]
@merobal @wag110894 is this closed?

**Comment by jhen1422** [comment]
This issue should now be resolved on IE11

**Comment by elibus** [comment]
@jhen1422 it was working at point, however now nothing works on ie11 and Edge. The portal does not open at all, there is a js error in the browser console. The same goes for formiojs
