### ISSUE TITLE
Cannot read property 'removeLoadingState' of undefined [BUG] 

### ISSUE THREAD

**Issue by nawazsktekopt** [formio/angular-formio#402]
![choicesJs](https://user-images.githubusercontent.com/57658949/68652952-a0b59a00-0550-11ea-8a70-f6344de45436.PNG)

So when i try to initialize **dropDown** by using **choicesJs** widget this issue arose.
There is no issue with **HTML5** widget.
Please provide a way for Initialization

Thank you

**Comment by travist** [comment]
Please provide a JSFiddle showing the problem so that we can investigate.

**Comment by nawazsktekopt** [comment]
I am really sorry.
The issue was because i was getting values to bind in form first & then initializing the form.
This is what caused the error. Sorry for inconvenience.
Thank you

**Comment by kamaloush** [comment]
Hello @nawazsktekopt 
I have the same error.
Please, can you describe your solution ?
It will really save my day.

Thanks in advance,

**Comment by Alexa-Green** [comment]
@nawazsktekopt @kamel-msaoubi This is happening to me as well-- what ended up fixing it?

**Comment by Benzer1406** [comment]
Same issue happening here.

**Comment by Alexa-Green** [comment]
@nawaz7777 Thank you-- seems to be a few issues happening due to rendering/initialization that tend to be fixed with a manual rerender of form.io-- would be ideal if form.io waits to be fully initialized or could rerender itself on these bugs
