### ISSUE TITLE
Documentation of Custom Components: 

### ISSUE THREAD

**Issue by dmenne** [formio/angular-formio#405]
https://github.com/formio/angular-formio/wiki/Custom-Components-with-Angular-Elements

Conventionally it is `valueChanges`, not `valueChange`.

A working example would be useful

**Comment by travist** [comment]
@dmenne it is a Wiki so don't you have the ability to make the changes you suggested?

**Comment by dmenne** [comment]
As far I know, github wiki cannot be edited.

**Comment by travist** [comment]
@merobal this is your docs page. Will you verify this request and make the change?

Thanks @dmenne

**Comment by dmenne** [comment]
Sorry, my fault. I thought is was github documenation which cannot be edited via pull requests.

**Comment by merobal** [comment]
It's `valueChange` for two-way-binding, see `ngModel` & `ngModelChange`. So I leave as is.

I will ad working example to https://github.com/formio/angular-demo soon.

**Comment by dmenne** [comment]
My fault....
