### ISSUE TITLE
how to add custom click events to datagrid remove row buttons [help wanted]

### ISSUE THREAD

**Issue by muthuML** [formio/angular-formio#408]
### ![datagrid](https://user-images.githubusercontent.com/51108986/69130229-24820000-0ad6-11ea-8e64-f320b6c64a81.png)

In Formio - 

how to add custom click events to datagrid remove row buttons ?

(or)

is there any other ways to get deleted row index or data of the datagrid ?

**Comment by SmithXiong** [comment]
bind change event on formio
