### ISSUE TITLE
Custom component fields

### ISSUE THREAD

**Issue by dmenne** [formio/angular-formio#409]
I tried to create a [bootstrap variant](https://getbootstrap.com/docs/4.0/components/buttons/) of radio buttons using [custom components](https://github.com/formio/angular-formio/wiki/Custom-Components-with-Angular-Elements#options). `Components.components.radio.editForm` is just fine for the required parameters, and using it to enter button values works ok.

The "standard" Parameter `disabled` is available in the component, but I cannot access `values`.  As I understand the text in _Custom Options_, I must request this explicitely.

How?

```
export function RadioButtonsForm() {
  // What to return here?
  // { key: 'customOptions.myOption', [rest of the field definition] }
  return Components.components.radio.editForm()
}

const COMPONENT_OPTIONS: FormioCustomComponentInfo = {
  type: 'radiobuttons', selector: 'radio-buttons',  title: 'Radio Buttons', group: 'basic', 
  icon: 'fa fa-star', 
  editForm: RadioButtonsForm,
}
```

**Comment by merobal** [comment]
To understand the edit form, I suggest to look it up in the formio.js lib (`Radio.form.js` file). According to what I see there, you can extend the edit form of the radio component with a new tab, where you can also define your fields.

Like:
```js
export function RadioButtonsForm() {
  return Components.components.radio.editForm({
    key: 'custom',
    label: 'Custom Options',
    components: [
      { key: 'customOptions.myOption', [rest of the field definition] }
    ]
  })
}
```

(_Or you may need a full copy of the edit form if you need more customization._)

**Comment by dmenne** [comment]
Nice.
