### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by panchalmeera** [formio/angular-formio#411]
Hi Team,

I'm using 'htmlelement' component in my json to add anchor (a) tag in my navigation bar. My application is angular 7 so I want to add routerLink & routerLinkActive attributes for navigation but the sttributes are not getting applied.
Can you please tell me how to use angular routing with form.io.

This is my code :

{
                                            "type": "htmlelement",
                                            "key": "html",
                                            "tag": "a",
                                            attrs: [
                                                {
                                                    value: "about-application",
                                                    attr: "routerLink"
                                                },
                                                {
                                                    value: "active",
                                                    attr: "routerLinkActive"
                                                }
                                            ],
                                            "className":"app-link mat-button app-nav inline-element",
                                            "content":"Contract Admin Agreement",
                                            "tabindex": 0
                                        }

**Comment by travist** [comment]
This would not work with Angular since this would require you to use the Angular component registration system to know what "routerLink" is etc.

**Comment by travist** [comment]
What you should do is just emit an event that is received by the angular controller which will then route the user.
