### ISSUE TITLE
[BUG] Forms with revision history cannot be found on formmanager

### ISSUE THREAD

**Issue by Yobikap** [formio/angular-formio#417]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: LATEST
- Frontend framework: Angular 8
- Browser: LATEST
- Browser version: LATEST

## Steps to Reproduce
1. Go to the devportal @ form.io
2. Meanwhile create a form in formmanager
3. Turn on the revision functionality in devportal
4. Go back to formmanager, the form dissapear and cannot founded in formmanager

## Expected behavior
The form should be available.

**Comment by travist** [comment]
Thanks for the bug report. We will take a look.

**Comment by Yobikap** [comment]
Hi Travist,

Do you know what the status is for this problem?

Thanks

**Comment by wag110894** [comment]
Hello @Yobikap. We are unable to replicate this issue on our side. Can you try updating to the latest stable versions of angular (4.3.13) and formio.js (4.8.0-rc.5)?

**Comment by Yobikap** [comment]
Okay this has been fixed.
