### ISSUE TITLE
[BUG] Select Component regression

### ISSUE THREAD

**Issue by kamaloush** [formio/angular-formio#419]
## Environment

- Hosting type
  - [x] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: detected since 4.3.2
- Frontend framework: angular
- Browser: all
- Browser version: all

## Steps to Reproduce
1. Create a select component
2. Add fields in data
4. Render the form
5. In the console of the browser : 
ERROR TypeError: Cannot read property 'removeLoadingState' of undefined
6. Can't change the model anymore

## Expected behavior
No errors
## Observed behavior
Error, full stacktrace is :
```js
zone-evergreen.js:651 Unhandled Promise rejection: Cannot read property 'element' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'element' of undefined
    at SelectComponent.attach (Select.js:805)
    at NestedComponent.js:412
    at Array.forEach (<anonymous>)
    at TableComponent.attachComponents (NestedComponent.js:410)
    at Table.js:276
    at Array.forEach (<anonymous>)
    at Table.js:275
    at Array.forEach (<anonymous>)
    at TableComponent.attach (Table.js:274)
    at NestedComponent.js:412 TypeError: Cannot read property 'element' of undefined
    at SelectComponent.attach (http://localhost:4200/vendor.js:169058:52)
    at http://localhost:4200/vendor.js:153104:43
    at Array.forEach (<anonymous>)
    at TableComponent.attachComponents (http://localhost:4200/vendor.js:153102:52)
    at http://localhost:4200/vendor.js:172119:18
    at Array.forEach (<anonymous>)
    at http://localhost:4200/vendor.js:172118:13
    at Array.forEach (<anonymous>)
    at TableComponent.attach (http://localhost:4200/vendor.js:172117:18)
    at http://localhost:4200/vendor.js:153104:43
```
## Example
https://formio.github.io/angular-demo/#/manager/5de523c32d99cca3f95f37ab/view

**Comment by jhen1422** [comment]
@kamaloush Thank you for the report. We have created a ticket in our Angular backlog and will review during our planning meeting this week. If you need this item expedited, please feel free to contact support@form.io for pricing.

**Comment by jhen1422** [comment]
@kamaloush 
One of our devs investigated the issue and was unable to replicate the errors you described in the angular demo example you provided. Is this specific to our a certain browser?

**Comment by kamaloush** [comment]
The step to reproduce in the demo manager is :
1. Create a select component of type ChoiceJS
![image](https://user-images.githubusercontent.com/26444823/70453797-a9df4b80-1aa9-11ea-8c4c-2d939202791e.png)
2. Validate and in the console you will have this error :
![image](https://user-images.githubusercontent.com/26444823/70453897-d1ceaf00-1aa9-11ea-8123-6282533ff9bc.png)

I noticed when you refresh the demo manager, the error disappears. But I use Angular Formio with custom API and Server. The problem on my solution, the error doesn't disappear. I have created multiples forms using that select component and it is embarassing for my developments.
The problem seems to be in ChoiseJS integration.

**Comment by kamaloush** [comment]
I founded the solution,
The problem was the fact that I initialized the form builder and then injected the Json Schema.
It was working before, but now, we need to add a *ngIf on the form builder tag and set it to true only when the Json Schema is ready.

form-builder.page.html
` ...
<form-builder [form]="form" *ngIf="formLoaded"></form-builder>
...`

form-builder.page.ts
`...
this.form = action.form;
this.formLoaded = true;
...
`
Sorry for the inconveniance
