### ISSUE TITLE
[QUESTION] How to override the form renderer in the formbuilder?

### ISSUE THREAD

**Issue by JoeyHengst** [formio/angular-formio#425]
Would it be possibile to use the same structure as https://github.com/formio/angular-material-formio to render form components in the form builder? If so could you give some pointers what would be the best way to approach plz. 

So that we have one place for custom components which can be used in the form renderer and in the form builder.

Thank you.

**Comment by travist** [comment]
Yes, the Angular Material library essentially creates "Custom Components" that are wrappers for the Angular Material.  But we also have an example of Custom Components in Angular in our StarterKit application @ https://github.com/formio/angular-app-starterkit/tree/master/src/app/components.  Just be aware that this is the 3.x version and not 4.x. We need to upgrade it to work with the latest core renderer.
