### ISSUE TITLE
Button not showing ace editor on custom event selection

### ISSUE THREAD

**Issue by Dheeraj-Bharti** [formio/angular-formio#426]
In the previous version of angular-formio there was an ace editor that comes out on selection of custom event but angular-formio@4.3.0 and above version is not showing that editor not only here in **select** component as well. Please see the screenshot below.
![buttonnotshowingaceditorerror](https://user-images.githubusercontent.com/26864086/71167833-7657aa80-227b-11ea-82e1-d676cf54f97c.PNG)
Can you please look into the issue or provide an alternate solution for the same.

regards,
Dheeraj Bharti

**Comment by travist** [comment]
It seems to be loading fine in our demo application https://formio.github.io/formio.js/app/builder.

This tells me that it may be that your application is blocking the CDN where this ace editor is loaded from (https://cdn.form.io). Please check the network and verify that the editor is loading.

**Comment by Dheeraj-Bharti** [comment]
True that. It's working fine in other network. Thank you for your quick reply.

**Comment by Dheeraj-Bharti** [comment]
working fine
