### ISSUE TITLE
Page to page navigation.

### ISSUE THREAD

**Issue by Dheeraj-Bharti** [formio/angular-formio#428]
## Environment
In my application requirement is to connect the pages. suppose I've created 3-4 pages and wants to connect them through the formio pop up. How can we achieve that?

**Comment by travist** [comment]
I am not sure what you mean by "connecting pages through formio pop-up". Please elaborate.

**Comment by Dheeraj-Bharti** [comment]
I have integrated angular-formio in my application where i want to generate a multiple pages through formio builder. Pages i can build however, my concern is can we connect those pages through formio?
or i have to create my own interface.

**Comment by travist** [comment]
I think what you are asking for is Wizard feature. You can also embed nested forms within each page which is a way to connect separate forms into a multiple page wizard interface. I believe this is what you are asking for, and yes, Form.io does support that.

**Comment by Dheeraj-Bharti** [comment]
I've seen the wizard feature. However, I'm looking for the routing from one page to another. Let's say I've created login page, one Dashboard page and a customer page separately. I want to link login to dashboard page and may be from dashboard to customer page. Can we achieve that using formio?

Hope this time I'm able to make you understand my query and Thank you for your quick replies.
Marry Xmas!

**Comment by jhen1422** [comment]
Hi @Dheeraj-Bharti . Form.io offers a 'Nested Form' component which allows you to embed different forms within a 'parent' form all within the builder. These parent forms can embed many different children forms, please take a look at the documentation here for more info 
https://help.form.io/userguide/form-components/#nested-form
