### ISSUE TITLE
Trigger submit event in custom component

### ISSUE THREAD

**Issue by Schwofel** [formio/angular-formio#432]
Hello everyone,
i want to trigger a formio submit in a custom component. How would i do that?
Thx for the help.

**Comment by travist** [comment]
You can just emit a submitButton event which will make the renderer believe a submit button was clicked.

```
this.emit('submitButton', {
  state: 'submitted',
  component: this.component
});
```

**Comment by Schwofel** [comment]
Hi,
my problem is that i use a angular component which implements FormioCustomComponent<string>.
Do i have to extend a Formio class to get this.emit? At the moment this isn't working.

**Comment by Schwofel** [comment]
Please i need help. I have no problems to register a new angular elements component (angular 8).
This works as expected but i dont have a emit method.

**Comment by travist** [comment]
I believe FormioCustomComponent derives from the BaseInput class which would have access to ```this.emit``` but this is probably a question for @merobal since he implemented the Custom component code.

**Comment by Schwofel** [comment]
Thank you very much for the quick answer :)
