### ISSUE TITLE
How can i trigger a submitButton event in an Angular 8 application with angular elements?

### ISSUE THREAD

**Issue by Schwofel** [formio/angular-formio#434]
Hi @merobal,
@travist mentioned that you could possibly help me.
I want to trigger a submitButton Event (or any formio event for that matter) in a custom formio angular elements component. I know i could do this with a js component. But i would like to use angular elements.

Can you help me?

**Comment by merobal** [comment]
Yes I also read https://github.com/formio/angular-formio/issues/432
This will be a new feature, I will add it this week.

(I need to connect the Angular scope with the formio class behind it via an `Output`. I keep you posted.)

**Comment by Schwofel** [comment]
Thank you very much.

**Comment by ajaykumarsana** [comment]
@merobal 
`this.formioEvent.emit({ eventName: 'viewer', data: { url: 'assets/docs/a.pdf' } });`

this event is not getting catch in CustomEvent method
`<formio [form]='formSrc' [submission]='model' [options]='options' (customEvent)="customEvent($event)" ></formio>`

Please help.
Thanks a Lot.

**Comment by travist** [comment]
You would emit a custom event by first getting the Form.io renderer instance from the Angular controller like so.

https://gist.github.com/travist/e639060968a6ec984b38a49c3753043f

Then, you can do the following in the callback.

```
formio.emit('submitButton');
```
