### ISSUE TITLE
How can i define a Angular 8 Custom Formio Nested Component

### ISSUE THREAD

**Issue by Schwofel** [formio/angular-formio#435]
Hello everyone,
how can i create a custom nested component (layout) with  angular elements?
Is it like creating a normal custom component? I couldn't find any documentation about it.
Thank you.

**Comment by Schwofel** [comment]
I know that i need to extend NestedComponent. But how can i do that. I couldn't even get the checkmatrix example to work.

I tried importing the CheckMatrix.js file into my app.module.ts file and it can't be compiled.
i tred to register the CheckMatrix component and it won't work.
What am i doing wrong here?
Could you give me an example on how to create and register a  custom nested component with angular 8?

**Comment by travist** [comment]
All components provided in our renderer are technically "custom components". Please see how they are done within the "components" folder of our renderer.  

https://github.com/formio/formio.js/tree/master/src/components

If you need more help beyond that, then we do offer support packages if you are interested where we would walk you through creating the component you need to create.
