### ISSUE TITLE
[BUG] Formbuilder is not responding

### ISSUE THREAD

**Issue by aburakab** [formio/angular-formio#437]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x ] Local deployment
    - Version: `"angular-formio": "^4.4.2"`
- Formio.js version: 
- Frontend framework: `Angular 8.2.14`
- Browser: Chrome
- Browser version: `Version 79.0.3945.88 (Official Build) (64-bit)`

## Steps to Reproduce
1. After upgrading to the latest npm package.
2. Try to add a field and you will get this warning & error.
3. Now, I added Edit grid, the Tags component inside it. 
4. Try to delete tag component, it's not deleting that component.

## Expected behavior
I'm not sure if the error and warning related to it or not!
Or maybe because of the CDN, what if i have an offline environment?
I can see couple of urls like 

- `https://cdn.form.io/timezones.json`
- `https://cdn.form.io/ace/1.4.5/ace.js`
- `https://cdn.form.io/ckeditor/12.2.0/ckeditor.js`
- `https://cdn.form.io/quill/1.3.6`

## Example
Chrome console
```
ace.js:1 Refused to create a worker from 'blob:http://localhost:4200/dc155a54-833a-4fc1-983e-3543b6fc2e48' because it violates the following Content Security Policy directive: "script-src * 'unsafe-inline' 'unsafe-eval'". Note that 'worker-src' was not explicitly set, so 'script-src' is used as a fallback.

a @ ace.js:1
$createWorkerFromOldConfig @ ace.js:1
f @ ace.js:1
createWorker @ mode-json.js:1
$startWorker @ ace.js:1
$onChangeMode @ ace.js:1
(anonymous) @ ace.js:1
(anonymous) @ ace.js:1
(anonymous) @ ace.js:1
n @ ace.js:1
a @ ace.js:1
a @ ace.js:1
i.onload.i.onreadystatechange @ ace.js:1
wrapFn @ zone.js:1279
ZoneDelegate.invokeTask @ zone.js:431
Zone.runTask @ zone.js:198
ZoneTask.invokeTask @ zone.js:513
invokeTask @ zone.js:1671
globalZoneAwareCallback @ zone.js:1697
load (async)
customScheduleGlobal @ zone.js:1810
ZoneDelegate.scheduleTask @ zone.js:417
Zone.scheduleTask @ zone.js:241
Zone.scheduleEventTask @ zone.js:267
(anonymous) @ zone.js:1984
desc.set @ zone.js:1340
t.loadScript @ ace.js:1
t.loadModule @ ace.js:1
setMode @ ace.js:1
(anonymous) @ Component.js:1836
notifyIsolated @ npo.src.js:120
notify @ npo.src.js:97
drain @ npo.src.js:67
ZoneDelegate.invokeTask @ zone.js:431
Zone.runTask @ zone.js:198
ZoneTask.invokeTask @ zone.js:513
ZoneTask.invoke @ zone.js:502
timer @ zone.js:3041
b.<computed> @ index.js:6978
xY @ index.js:6951
zY @ index.js:6962
ace.js:1 Could not load worker DOMException: Failed to construct 'Worker': Access to the script at 'blob:http://localhost:4200/dc155a54-833a-4fc1-983e-3543b6fc2e48' is denied by the document's Content Security Policy.
    at a (https://cdn.form.io/ace/1.4.5/ace.js:1:329373)
    at f.$createWorkerFromOldConfig (https://cdn.form.io/ace/1.4.5/ace.js:1:330208)
    at new f (https://cdn.form.io/ace/1.4.5/ace.js:1:329570)
    at l.createWorker (https://cdn.form.io/ace/1.4.5/mode-json.js:1:4907)
    at d.$startWorker (https://cdn.form.io/ace/1.4.5/ace.js:1:159755)
    at d.$onChangeMode (https://cdn.form.io/ace/1.4.5/ace.js:1:158990)
    at d.<anonymous> (https://cdn.form.io/ace/1.4.5/ace.js:1:158751)
    at https://cdn.form.io/ace/1.4.5/ace.js:1:63525
    at Array.forEach (<anonymous>)
    at https://cdn.form.io/ace/1.4.5/ace.js:1:63502
```

For code or form JSON, please enclose in a code block:

```js
@Component({
  selector: 'wraplib-form-builder',
  template: `<form-builder [options]="options" [form]="model"></form-builder>`,
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class FormBuilderComponent implements OnInit {

  @Input()
  model: any = { components: [] };

  options: FormioOptions = {
  };

  constructor() { }

  ngOnInit() {
  }

}
```

**Comment by travist** [comment]
To use the ACE editor you may need to change your application Content Security Policy since that is what is crashing.

**Comment by aburakab** [comment]
Thank you for responding. 
Can I configure **form.io** by making these CDN content available locally?
Should I open another thread for this point? :)

**Comment by travist** [comment]
Having the scripts available locally would not solve this problem. This is caused by it trying to execute "eval" in the browser and your application has specifically been configured to not allow that. ACE editor performs eval's so this would need to be brought up as an issue within that library.
