### ISSUE TITLE
Is it possible to use same JSON Schema/ settings on 2 formio builder packages

### ISSUE THREAD

**Issue by Theaggarwal** [formio/angular-formio#439]
HI,
In my old angularjs application, i am using following formio packages and is working great.
"ng-formio": "2.19.6",
"ng-formio-builder": "2.19.4",

Now i am creating new angular 7 application with different packages.
"formiojs": "3.21.5",
"angular-formio": "3.17.0"

Now, i want to keep both the applications simultaneously. so same form created by 1 builder can be used in another. 
IS it possible to do so??
currently, on angular 7 i am getting few errors and form is not getting updated. (On UI new textboxes are getting added, but the form schema binded with [form] property is not getting updated.) please suggest.

Angular 7:
<form-builder [form]="formDefinition.schema" [options]="formBuilderConfig"></form-builder>

Angularjs:
<form-builder form="ctrl.formDefinition.schema"></form-builder>

**Comment by travist** [comment]
Yes this is possible. Just point the new renderer to the old JSON and it will render it just fine (hopefully).
