### ISSUE TITLE
How to customize Form builder formio

### ISSUE THREAD

**Issue by sarashid** [formio/angular-formio#440]
I'm using formio with angular 8, is it possible to customize form-builder components. I found a solution to this problem in angularjs but I want to do something like this using form-builder with angular 8
![custom](https://user-images.githubusercontent.com/17121064/71977079-99450100-3220-11ea-896e-c5ebdc98fd6c.PNG)
![normal](https://user-images.githubusercontent.com/17121064/71977099-a104a580-3220-11ea-90c6-8d47fcb46c6c.PNG)

**Comment by travist** [comment]
Yes you can. You can just override the ```editForm``` for the components you wish to change. Here are some docs on how to do that.

https://formio.github.io/formio.js/app/examples/custombuilder.html

**Comment by sarashid** [comment]
thank you for your help , but i have another question.
i override editForm from a Custom component like the following Link:
https://github.com/formio/angular-formio/wiki/Custom-Components-with-Angular-Elements

how i can make my own editForm  interact with Preview section 
Like placeholder, for example 
![editForm](https://user-images.githubusercontent.com/17121064/72528846-ad1de200-3874-11ea-9aa5-819cbe06c9da.PNG)
and this error show up after replacing old editForm by custom one  
![error](https://user-images.githubusercontent.com/17121064/72529190-6da3c580-3875-11ea-9990-d7da01e886ce.PNG)

**Comment by travist** [comment]
It should automatically interact with the preview. It could be that the error that we see there is causing javascript to not update the preview section. That would need to be resolved first.

**Comment by dinbtechit** [comment]
@sarashid  - I had the same question. did you figure out how to access to custom fields in the preview section?
