### ISSUE TITLE
Custom Error Message overrides Custom Validation Error Message  [BUG]

### ISSUE THREAD

**Issue by Deloriom** [formio/angular-formio#452]
- Hosting type
  - [x] Form.io
  - [ ] Local deployment
- Browser: opera

## Steps to Reproduce
1. in the demo, add a field to a form
2. type in custom message field
![image](https://user-images.githubusercontent.com/38706785/72900811-534f6900-3d07-11ea-982d-89c8be79300a.png)
3. create custom validation
![image](https://user-images.githubusercontent.com/38706785/72902015-8692f780-3d09-11ea-9b97-68b45b0d43e6.png)

4. test the validation

## Expected behavior
show the message defined in the custom validation

## Observed behavior
![image](https://user-images.githubusercontent.com/38706785/72902083-a3c7c600-3d09-11ea-8b69-bb8cec9fa3f4.png)

it is showing the custom message, in place of the message returned from the custom validation

**Comment by travist** [comment]
This is expected behavior. If you want to show your own custom error message, then just delete that value, and return the error you would like to see.
