### ISSUE TITLE
Info Request

### ISSUE THREAD

**Issue by hbaldwinRPT** [formio/angular-formio#455]
I'm attempting to use the formio builder and renderer, but I do not wish to use any of the formio backend, as it won't suit the needs pf the application I had this working on a previous application but now trying to replicate that I get issues regarding appConfig that did not previously to occur. Am I missing something or was this deliberately added recently. Additionally even with the AppConfig set, I get issues pertaining to misspelled modules while trying to test the form builder 
Any guidance is appreciated.

**Comment by travist** [comment]
Please provide the actual error that you are receiving. This will help identify the issues.

**Comment by hbaldwinRPT** [comment]
When empty AppConfig
```
TypeError: Cannot read property '0' of null
    at new Formio (Formio.js:179)
```

When App Config Not Present
```
You must provide an AppConfig within your application! formbuilder.component.js:26
```

**Comment by travist** [comment]
Same response as provided @ https://github.com/formio/angular-formio/issues/456
