### ISSUE TITLE
Icons are not shown

### ISSUE THREAD

**Issue by GabrielDambroski** [formio/angular-formio#457]
![screenshot](https://user-images.githubusercontent.com/43409178/73361645-1c87ce80-4284-11ea-9ec1-7a60023b7de2.png)

**Comment by travist** [comment]
You need to import font-awesome into your application. See

https://help.form.io/intro/guide/#createeventapp

**Comment by GabrielDambroski** [comment]
thanks, its component is great. five start

**Comment by simionato-ennovaresearch** [comment]
For those who come after:

1. Install FontAwesome 4 dependency by running `npm install font-awesome --save`
2. Update your angular.json, like this

```json
{
  "projects": {
    "my-project": {
      "architect": {
        "build": {
          "options": {
            "styles": [
              "./node_modules/font-awesome/css/font-awesome.min.css", // <-- Added this
              "src/styles.scss"
            ]
          }
        }
      }
    }
  }
}
```
