### ISSUE TITLE
[BUG] date component translation issue

### ISSUE THREAD

**Issue by gismomtl** [formio/angular-formio#460]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [X] Local deployment
    - Version:  1.68.x

## Steps to Reproduce
If we define the french version of the messages (Next->Suivant, Submit->Transmettre,..). element are correctly translated.
However even if January, day .. are translated in the same Angular element...  the Date component is still displaying date, day,... in english, not in French

How to do such translation?

**Comment by travist** [comment]
I believe this is a configuration of the Flatpickr https://flatpickr.js.org/localization/.  The way this would integrate with Form.io is that you need to override ```createWidget``` on the DateTime component and set the ```locale``` variable. It's not pretty so we will work on coming up with something better, but something like this should work.

```js
import { Russian } from 'flatpickr/dist/l10n/ru.js';
import { DateTimeComponent } from 'formiojs/components/datetime/DateTime.js;'
const createWidget = DateTimeComponent.prototype.createWidget;
DateTimeComponent.prototype.createWidget = function(index) {
  this.component.widget.locale = Russian;
  return createWidget.call(this, index);
};
```

**Comment by fhasni** [comment]
@travist I used the same code snippet you provided & am getting this error `ERROR TypeError: Cannot read property 'prototype' of undefined`, I am using  angular-formio 4.11.0

**Comment by travist** [comment]
It probably needs to be the following.

```js
import { French } from 'flatpickr/dist/l10n/fr.js';
import DateTimeComponent from 'formiojs/components/datetime/DateTime.js;'
const createWidget = DateTimeComponent.prototype.createWidget;
DateTimeComponent.prototype.createWidget = function(index) {
  this.component.widget.locale = French;
  return createWidget.call(this, index);
};
```
