### ISSUE TITLE
[Help] File Upload/Custom Component

### ISSUE THREAD

**Issue by samswbk** [formio/angular-formio#461]
Hello, can i hide / remove these items as the image.
I'm trying to create a custom component, like uploading files (display image = true), using the JavaScript Check Matrix example, but I'm lost, I can't figure out how to do it.

Thanks, Sam.
![Sem título](https://user-images.githubusercontent.com/49195281/73542727-22acb500-4414-11ea-8a1a-1f60c5efd38a.png)

**Comment by travist** [comment]
You don't need a custom component to do this. Just override the template for the file component. Here is docs on how to do that.  https://github.com/formio/formio.js/wiki/Templates-API

And the template you will want to override can be found @ https://github.com/formio/formio.js/blob/master/src/templates/bootstrap/file/form.ejs

**Comment by samswbk** [comment]
@travist i'm using javascript version, the docs mention on angular.

`customAdvanced: {
        title: 'Advanced',
        default: false,
        weight: 0,
        components: {
            inputcamera: {
                schema: {
                label:'camera',
                type:'file',
                key:'inputcamera',
                image:true
            }}
        }
    },`

**Comment by dev-thinks** [comment]
> You don't need a custom component to do this. Just override the template for the file component. Here is docs on how to do that. https://github.com/formio/formio.js/wiki/Templates-API
> 
> And the template you will want to override can be found @ https://github.com/formio/formio.js/blob/master/src/templates/bootstrap/file/form.ejs


Thank you @travist. This is helpful. 

Based on the documentation, I tried overriding file upload template with angular-formio in [here](https://github.com/dev-thinks/formio-custom-file-upload-template), It might helpful for others.
