### ISSUE TITLE
Converting circular structure to JSON

### ISSUE THREAD

**Issue by merobal** [formio/angular-formio#465]
## Environment
Please provide as many details as you can:

- Formio.js version: 4.5.1
- Frontend framework: 4.8.1
- Browser: Chrome
- Browser version: latest

## Steps to Reproduce
https://angular-formio-custom-demo.netlify.com/
1. Add a Table component.
2. Add any component. The components will disappear.
3. Add any component again. This error message will appear in console: `Infinite loop detected undefined 500`

## Expected behavior
No error message, no circular reference.

## Observed behavior
Circular reference, error message in console.

I cannot reproduce our issue with the demo app (only the infinite loop), but internally we get this error message:

```
Uncaught TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    --- property 'component' closes the circle
    at JSON.stringify (<anonymous>)
    at fastCloneDeep (utils.js:1350)
    at TableComponent.get (Component.js:2883)
    at get (<anonymous>)
    at TableComponent.get (NestedComponent.js:730)
    at get (<anonymous>)
    at TableComponent.get (Table.js:85)
    at Webform.js:1783
    at NestedComponent.js:198
    at arrayEach (lodash.js:516)
```

## Example
https://angular-formio-custom-demo.netlify.com/

**Comment by travist** [comment]
We will add this to our developer list to investigate.

**Comment by merobal** [comment]
@travist do you have any update on this?

**Comment by jhen1422** [comment]
@merobal Could you try using the latest version of formio.js to see if this resolves the issue?

**Comment by merobal** [comment]
Still, the same issue using `"angular-formio": "4.6.7"`
I updated the version at the demo site, you can try the repro by following the "Steps to Reproduce" mentioned above...

https://angular-formio-custom-demo.netlify.com/

**Comment by dmenne** [comment]
As suggested by @merobal, we had to revert to 4.3.3 to get around this. Please have a look.

**Comment by ullas1989** [comment]
Getting same issue with angular-formio renderer for existing forms. Any form with data grid and components added into it is giving error: `Infinite loop detected undefined 500`

**Comment by travist** [comment]
We are aware of this as a possible high priority bug. We have our planning sessions Monday and I should know more about when we will see resolution to this after that point.

**Comment by dmenne** [comment]
With 4.3.3 I have not seen the infinite recursion, but it nevertheless is suspicious that the component is created twice on every call redraw. Might be the source of the issue.

**Comment by merobal** [comment]
Still having the same issue with "angular-formio": "4.6.10"

**Comment by travist** [comment]
Thanks for the bump... I will ensure this is added to a developer on our teams list this week, or maybe early next week.

**Comment by Tkachez** [comment]
@merobal, I've tried to use angular-formio "4.6.10"/"4.6.7" and formiojs "4.5.1", but, unfortunately, was not able to reproduce the issue. Maybe you could give us more details on your environment?

**Comment by merobal** [comment]
@travist FYI I realized the issue, in this case, was I saved the form to a local model and I passed back to the formio component.

So the fix for my demo is: https://github.com/merobal/angular-formio-custom-demo/commit/1a4a96280637b986997388e05aa2662d71e957fd

FYI https://github.com/formio/angular-formio/issues/509 @ullas1989 
FYI https://github.com/formio/angular-formio/issues/507 @dmenne
