### ISSUE TITLE
[BUG] Custom Component feature does not seem to work or is not documented well enough for people to use.

### ISSUE THREAD

**Issue by travist** [formio/angular-formio#470]
## Environment
Please provide as many details as you can:

Form.io is getting a lot of support requests to figure out how to get the new Custom Components feature working in this library. This was contributed by a community member and therefore does not fall under the maintenance umbrella of our company Form.io. 

We need to do one of two things:
 - Remove that feature from this module so that Form.io can continue to support this module.
 - Move that contribution into the developers own repository.
 - Write more comprehensive documentation on how to get Custom components working with this new feature.

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version:
- Frontend framework:
- Browser:
- Browser version:

## Steps to Reproduce
1. 
2. 
3. 

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js
// your code here
```

**Comment by travist** [comment]
@merobal we really need your help here. Our Form.io support is getting encumbered with support requests that the custom component feature you added to this library is not working. We are unable to support it since we did not contribute it, and we are left with upset customers. 

We REALLY do appreciate your contribution, but one of the unfortunate side effects of adding Open Source contributions is the need to maintain those contributions in the future. I understand if you don't have the bandwidth to do that, and if that is the case, we will need to probably place the custom component features in your own repository and pull it from this one.

**Comment by merobal** [comment]
The Angular wrapper for Custom Components still working, see: https://angular-formio-custom-demo.netlify.com/ (angular-formio version 4.5.1 used there)

But there is an other independent example, the checkmatrix, which is a JS-based example, and actually that doesn't work for me either, that's why we created our version.

Also the Angular wrapper may raise other questions, like custom templates, custom edit form or custom nested component, which weren't involved in our scope.

I'm happy to document the current limitations and kindly ask the community to discover more solutions as we did: we reviewed and understand the formio.js implementation during our work.

If you receive too many support requests I'm also open to separate this functionality into own package.

**Comment by travist** [comment]
Thanks for responding @merobal. The support request we answered today, they claimed they walked through your example and could not get it to work. I have not tried myself so I cannot say otherwise. We may just need to get ramped up internally on this feature.  I will send along your working example to them... On a side note, do you believe that this would work with Ionic 4? That was the framework they were using for this.

**Comment by merobal** [comment]
@travist I added new communications that it's a community contributed feature.
- I updated the wiki with the latest faq.
- I added the live example there with the commit how I setup.
- I added a new issue template to this repo to request help with Custom Components.

Feel free to redirect each support request you receive to this repo and ask them to create a new issue here by choosing that new issue template.

**Comment by travist** [comment]
Thanks for your support @merobal. We will keep this in place then, and hopefully the additional documentation will reduce the support burden on our end. Thanks again for your attention to this.

**Comment by muneebahmad0600** [comment]
Hi @merobal @travist 
I am using the old version of the library at the moment and I have created some custom components using Angular. If I provide my own edit form (which I need to do to show additional inputs in edit form), some of component's functionalities don't work properly. 
For example: the Logic tab shows all of the input fields at all times without having to select an option like trigger type or the action type.  
Here is a screenshot of that:
![image](https://github.com/user-attachments/assets/acf3e74e-bffc-4050-9401-1fe3d6b64025)
the 2 dropdowns that should show only when simple trigger type is selected, the text area that should only show when the Javascript type trigger is selected and the text area for JSON logic all show at once. If I write any logic in any of it.. it doesn't take effect.
Is there anything I am doing wrong?
Also It would be very much appreciated If you can point to the docs where you have created custom component using Angular and also modified the editForm.
Thanks in advance
