### ISSUE TITLE
[Custom Components] 

### ISSUE THREAD

**Issue by ullas1989** [formio/angular-formio#471]
I have created a custom component as described in below article and it works fine till now.

https://github.com/formio/angular-formio/wiki/Custom-Components-with-Angular-Elements

Now I have the requirement to access all the form data inside this custom component (.ts file of the angular component). Is there any way I can do it?

**Comment by merobal** [comment]
As the custom components are written in Angular, those can reach services.
Try the following:
- Create a new service, and put a `Subject` there.
- Outside of formio (at the parent/wrapper component), handle the submission (change output, add a check if `$event.data` is exist).
- Pass the submission data to the `Subject`.
- Inside of the custom components inject that service and subscribe to the Subject. (Don't forget to unsubscribe on destroy.)

Let me know if it works for you and I add this to the FAQ part of the wiki.

**Comment by ullas1989** [comment]
Thanks @merobal, let me try this and I will get back to you.

**Comment by ullas1989** [comment]
@merobal 
This works good. Thank you for pointing me to right direction.

I am using ngrx-store to save the state but yes using an angular service will do the same thing so should work as well.

using the Change event of formio, I am able to get the most recent data of the form and store it in ngrx store. 
`<formio [submission]="formData" [form]="schema" (change)="onChange($event)"></formio>`

`onChange(event) {
    if (event.data) {
      const data = _.cloneDeep(event.data);
      this.store.dispatch(new formIoActions.SetFormsIoDataLocalCopy(data));
    }
  }`

Then store is injected as service to custom component to get the latest data.
`this.subs= this.store.select(formIoReducer.formsioDataLocalCopy)
      .subscribe(data => {
        if (data) {
          this.data = data;
          console.log('data, this.data);
        }
      });`

Also, I am modifying the schema of some components dynamically using custom logic feature of the form-io library, so I was trying to get the updated schema as well. But there is no good way to get full updated schema object. I am getting the updated schema in Change event but only for the component that is being changed.

Will keep looking into it.
