### ISSUE TITLE
[BUG] required field - required message displayed before submission or field interaction

### ISSUE THREAD

**Issue by gismomtl** [formio/angular-formio#474]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [X] Local deployment
    - Version: 1.67.0
- Formio.js version: 4.9.0-beta.8
-  Angular-Formio : 4.5.8
- Browser: Chrome

Hi, when field is set with required field, the "required message" error is displayed directly when we interact with another field not related.
directly from formio admin page, issue doesnt occured. 
And with the test jsfiddle i made neither:  https://jsfiddle.net/4vahzLxc/

So I suspect more an issue on the Angular version

**Comment by gismomtl** [comment]
issue that occur in our Angular pages
<img width="760" alt="Screen Shot 2020-02-21 at 4 05 41 PM" src="https://user-images.githubusercontent.com/30330032/75071778-13c19b80-54c4-11ea-966e-a60145dfb839.png">

**Comment by gismomtl** [comment]
any update on this issue? is it possible it could be a formio.js or formio issue and not angular-formio?

**Comment by jhen1422** [comment]
@gismomtl 
Can you try updating the formio.js version to 4.9.0-rc.2 to see if that resolves the issue

**Comment by gismomtl** [comment]
it doesnt solved the issue.
it seems to be even worth: if one simple wizard page with 1 required checkbox is defined.. if we click Next (without checking the required checkbox) the "Next" button is spinning with error in chrome console:
core.js.pre-build-optimizer.js:6014 ERROR RangeError: Maximum call stack size exceeded
    at t.get (Form.js:728)
    at t.get (Form.js:729)
    at t.get (Form.js:729)
    at t.get (Form.js:729)

**Comment by travist** [comment]
We will add this to our developer backlog so that it will get some attention on our end. Seems like a bad bug, but it would require a developer to investigate.

**Comment by gismomtl** [comment]
I was able to reproduce the issue...
check my 2 formio.js cases:
https://github.com/formio/formio.js/issues/2496
and
https://github.com/formio/formio.js/issues/2497

**Comment by gismomtl** [comment]
latest formio.js versions 4.9.0-rc.8 and up solved the issue
