### ISSUE TITLE
[Custom Components] how to execute submit action from outside formIo? 

### ISSUE THREAD

**Issue by firadisaad** [formio/angular-formio#476]
here when i add formIo tag in my angular project :
`<formio [(form)]="formPreview" (submit)="onSubmit($event)"> </formio>

<button (click)="submit()">myButton</button>
`

i'm trying to click to submit button **(myButton)** and get form data 

can someone help me ?

**Comment by travist** [comment]
You can always emit the ```submitButton``` event like so...

```
this.formio.emit('submitButton');
```

**Comment by firadisaad** [comment]
tanks for your answer,
what is **this.formio**, i need more details please

**Comment by merobal** [comment]
try this:

```
@ViewChild(FormioComponent, { static: false })
  formio: FormioComponent;

submitButton() {
    if (this.formio) {
      this.formio.formio.emit('submitButton');
    }
  }
```

**Comment by firadisaad** [comment]
tanks, it's working  👍

**Comment by Santoshah** [comment]
I am not sure but where do we import `FormioComponent ` from ?
