### ISSUE TITLE
[Question] How to load wizard type form to a specific page

### ISSUE THREAD

**Issue by ullas1989** [formio/angular-formio#479]
I have a form created using angular-formio package which is in wizard type mode with multiple pages. When forms loads, I am populating some data to it which all is working fine.

Now I need to set the page number so when wizard form loads, it is automatically displaying the current page as whatever I want to display, instead of always starting with first page of the wizard.

Any idea how can this be done?

**Comment by ullas1989** [comment]
@travist 
Thank you. I will try this.

**Comment by ullas1989** [comment]
@travist 
I tried this solution but there is no setPage() function available in either FormioComponent or FormioBaseComponent. Am I missing something?

**Comment by travist** [comment]
You can reference the "root" from any component to get access to the wizard object. So it could be the following.

```js
instance.root.setPage(2);
```
