### ISSUE TITLE
[Question] Form-io data grid component, pagination option

### ISSUE THREAD

**Issue by ullas1989** [formio/angular-formio#481]
I am looking for pagination option in the data grid component of the form IO but not able to find it using form builder.

Is there any property in schema json that I can set to enable pagination on data grid?

`{
  "label": "Data Grid",
  "disableAddingRemovingRows": false,
  "reorder": false,
  "addAnother": "Add New Row",
  "addAnotherPosition": "bottom",
  "defaultOpen": false,
  "layoutFixed": false,
  "enableRowGroups": false,
  "hideLabel": true,
  "tableView": false,
  "defaultValue": [
    {
      ...
    }
  ],
  "validate": {
    ...
  },
  "key": "dataGrid1",
  "type": "datagrid",
  "components": [
    {...}
  ],
  "input": true,
  "placeholder": "",
  "prefix": "",
  "customClass": "",
  "suffix": "",
  "multiple": false,
  "protected": false,
  "unique": false,
  "persistent": true,
  "hidden": false,
  "clearOnHide": true,
  "refreshOn": "",
  "redrawOn": "",
  "modalEdit": false,
  "labelPosition": "top",
  "description": "",
  "errorLabel": "",
  "tooltip": "",
  "tabindex": "",
  "disabled": false,
  "autofocus": false,
  "dbIndex": false,
  "customDefaultValue": "",
  "calculateValue": "",
  "widget": null,
  "attributes": {},
  "validateOn": "change",
  "conditional": {
    ...
  },
  "overlay": {
    ...
  },
  "allowCalculateOverride": false,
  "encrypted": false,
  "showCharCount": false,
  "showWordCount": false,
  "properties": {},
  "allowMultipleMasks": false,
  "tree": true,
  "id": "egq3sfe"
}`

**Comment by travist** [comment]
Pagination is currently not supported for DataGrid elements. This would need to be a new feature.

**Comment by ullas1989** [comment]
@travist 
Thanks for the answer.

What is the alternative to grid element for pagination? Can I use formio-grid inside a custom component and pass modified schema/data to it inside custom component?

`<formio-grid src="https://examples.form.io"><formio-grid>`

**Comment by travist** [comment]
Maybe, but this would require a custom component to implement a "grid" control inside a component.

**Comment by ramesh401991** [comment]
Any update on the enhancement for this request?? I'm looking for the same feature in datagrid.

**Comment by echo-liang** [comment]
Any update on the enhancement for this request?? I'm looking for the same feature in datagrid.

**Comment by vahid64** [comment]
Any update on the enhancement for this request?? I'm looking for the same feature in datagrid.
