### ISSUE TITLE
[Custom Components] Angular 9 with custom components giving error

### ISSUE THREAD

**Issue by ullas1989** [formio/angular-formio#485]
I am trying to use custom component feature with angular 9 and it is giving me below error.

ERROR in Tried to overwrite C:/.../node_modules/angular-formio/auth/auth.config.d.ts.__ivy_ngcc_bak with an ngcc back up file, which is disallowed.

**Updated:**
Once I turned off ivy and aot, things works much better.

**Comment by merobal** [comment]
Angular 9 is not yet supported at the library level

**Comment by beeman** [comment]
@merobal is there anything to say if or when Angular 9 will be supported? I'd love to use Formio in my Angular project but it's already migrated to v9.

**Comment by merobal** [comment]
@travist can answer it

**Comment by travist** [comment]
This library can be now used in Angular 9, but there are some issues that I have experienced with IVY.  For that reason, I have to add the following to my tsconfig.json in order to get all of my compilations working correctly with Angular 9.

***tsconfig.json***
```json
{
  "angularCompilerOptions": {
    "enableIvy": false
  }
}
```

I am hoping that the community would have some ideas why IVY does not want to cooperate with this library, but for now we have been able to get our Angular 9 applications to build with the following configuration in place.

**Comment by dalesingh47** [comment]
I think this is related to this issue and it extends to more than custom components:

I'm putting form.io 4.7.8 in an angular 9.1 universal project and get the following after running ngcc

```
Error: Error on worker #1: Error: Invariant violated: No format-path or format for <project path>/node_modules/angular-formio/auth : main (formatPath: formio-manager.umd.js | format: undefined) 
```

In node_modules/angular-formio/auth/package.json on line 19, main is set to: 
```
  "main": "formio-manager.umd.js",
```

Should this be set to the following instead?
```
  "main": "formio-auth.umd.js",
```

Eventually, I got the project to compile with Ivy enabled by creating an ngcc.config.js file and putting the following:

```
module.exports = {
  packages: {
    "angular-formio": {
      entryPoints: {
        ".": {
          override: {
            main: undefined
          }
        },
        "auth": {
          override: {
            main: undefined
          }
        },
        "manager": {
          override: {
            main: undefined
          }
        },
        "grid": {
          override: {
            main: undefined
          }
        },
        "resource": {
          override: {
            main: undefined
          }
        }
      }
    }
  }
}
```

In spite of the following errors, the project was able to run:

```
Error: Failed to compile entry-point formio-manager (module as esm5) due to compilation errors:
node_modules/angular-formio/formio.module.js:16:5 - error NG6002: Appears in the NgModule.imports of FormioAuth, but could not be resolved to an NgModule class.

Is it missing an @NgModule annotation?

16 var FormioModule = /** @class */ (function () {
       ~~~~~~~~~~~~

Compiling formio-grid : module as esm5
Compiling formio-resource : module as esm5
Error: Failed to compile entry-point formio-grid (module as esm5) due to compilation errors:
node_modules/angular-formio/formio.module.js:16:5 - error NG6002: Appears in the NgModule.imports of FormioGrid, but could not be resolved to an NgModule class.

Is it missing an @NgModule annotation?

16 var FormioModule = /** @class */ (function () {
       ~~~~~~~~~~~~

Error: Failed to compile entry-point formio-resource (module as esm5) due to compilation errors:
node_modules/angular-formio/formio.module.js:16:5 - error NG6002: Appears in the NgModule.imports of FormioGrid, but could not be resolved to an NgModule class.

Is it missing an @NgModule annotation?

16 var FormioModule = /** @class */ (function () {
       ~~~~~~~~~~~~
node_modules/angular-formio/formio.module.js:16:5 - error NG6002: Appears in the NgModule.imports of FormioResource, but could not be resolved to an NgModule class.

Is it missing an @NgModule annotation?

16 var FormioModule = /** @class */ (function () {
       ~~~~~~~~~~~~
node_modules/angular-formio/grid/grid.module.js:21:5 - error NG6002: Appears in the NgModule.imports of FormioResource, but itself has errors

21 var FormioGrid = /** @class */ (function () {
       ~~~~~~~~~~

```

**Comment by dalesingh47** [comment]
Created new issue since this one is closed: [https://github.com/formio/angular-formio/issues/532](url)
