### ISSUE TITLE
Browser support for IE

### ISSUE THREAD

**Issue by ullas1989** [formio/angular-formio#488]
"angular-formio": "^4.6.4",
"@angular/cli": "~9.0.5"

I am trying to open my forms using angular formio renderer in IE 11.

There are multiple scripts added inside custom logic and data section of the formio components that are not working with IE 11 at all. These works fine in chrome though. I am getting below error in IE.

Differential build is disabled and code is being compiled to es5.

An error occured within the custom function for employeeNameFirstLast SyntaxError: Syntax error
   "An error occured within the custom function for employeeNameFirstLast"
   {
      [functions]: ,
      __proto__: { },
      description: "Syntax error",
      message: "Syntax error",
      name: "SyntaxError",
      number: -2146827286,
      stack: "SyntaxError: Syntax error

**Comment by ullas1989** [comment]
@travist 
It looks like we cannot use modern javascript methods (e.g. forEach, find) for scripts written inside formio custom components (e.g. data, conditional). Can you please confirm if that is true or way to resolve this?

**Comment by travist** [comment]
Please provide a JSFiddle that fails in IE and we will take a look.

**Comment by ullas1989** [comment]
Never mind, I found out that I can use lodash instance for writing scripts in form components instead of using modern browser javascript methods. It works much better. Please excuse my ignorance.
