### ISSUE TITLE
fieldOptions do not appear in @Input fields

### ISSUE THREAD

**Issue by dmenne** [formio/angular-formio#491]
I have a Custom Component which is a replacement for the much too small radio buttons on tablets using [bootstrap buttons](https://ng-bootstrap.github.io/#/components/buttons/examples)

```
const COMPONENT_OPTIONS: FormioCustomComponentInfo = {
  type: 'radiobuttons', // custom type. Formio will identify the field with this type.
  selector: 'radio-buttons', // custom selector. Angular Elements will create a custom html tag with this selector
  title: 'Radio Buttons', // Title of the component
  group: 'basic', // Build Group
  icon: 'fa fa-star', // Icon
  fieldOptions: ['values', 'label', 'key'],
  editForm: Components.components.radio.editForm
}
```
Rendering of the components and the display of the edit form works fine. However, the only @Input field that are accessible in 
```
export class RadioButtonsComponent  implements FormioCustomComponent...
```
is `@Input()  type: string;` and `disabled`. I might have missed a rare one, but have tested the usual suspects.

The documentation says:

*Explicit Options* : Due to performance reasons not all the options are bound to the component. If you want to reach fields from the schema, define in the fieldOptions array at the field registration.

Did I miss something? I am using 4.3.3 because of the infinite recursion bug in later versions already reported by @merobal.

Later: I have tested with the wrapping app:   `fieldOptions: ['placeholder', 'key', 'hidden','label']`. This works as expected. So the problem might be my special `editForm`.

**Comment by merobal** [comment]
Fixed by 4.4.3, so you can use this once the other infinite loop issue is fixed.
Meantime at your custom editForm try `customOptions.something` as the key and you can have Input `something`.
