### ISSUE TITLE
[Custom Components]  Panel ist not rendered when loaded in lazy mode

### ISSUE THREAD

**Issue by dmenne** [formio/angular-formio#502]
As suggested by @merobal, the following issue is reposted here

https://github.com/merobal/angular-formio-custom-demo/issues/3

Example by @upexcel https://github.com/upexcel/formio-question

Netlify: https://wonderful-perlman-0d1430.netlify.com/#/test

The Preview Panel doesn't render the component when using formio in a lazy loaded module.
When I add the rating field in lazy loaded formio it doesn't load.

-----
dmenne:

In my app,  the preview and the component on the form do not render.

Surprisingly, the Default Window in the editor is displayed correctly. This can also be seen in the netlify app by @upexcel

An example how to use lazy load with custom components would be welcome

**Comment by dmenne** [comment]
Works for me when I keep only lazy loading and register in rating component:

https://github.com/dmenne/formio-question

**Comment by quynhlx** [comment]
The same issue. 
 In my app, there are multi lazy load modules need to use custom component. 
When custom component was registered in lazy load module, it worked.
But I don't think we should register in each module. And we have to change selector name for them.

**Comment by dmenne** [comment]
Agreed, I independently stumbled over this today:

-- To use lazy loading, I have to register custom components in the loaded submodule.
-- To use is in other parts, I have to register it in app.module, which is also what  https://angular.io/guide/ngmodule-faq suggests.

Any Angular-guru around? Is there some way of saying "force-use the registration in the parent module"?

**Comment by dmenne** [comment]
Help, I am stuck. Any ideas?

**Comment by JRiggenbach** [comment]
@dmenne  Assuming you're still waiting for an answer to this?

**Comment by dmenne** [comment]
No, I have totally given up using Formio. Too many rough corners. We switched to ODK Collect, which is not that flexible, but works reasonably.
