### ISSUE TITLE
Override Component Labels?

### ISSUE THREAD

**Issue by JRiggenbach** [formio/angular-formio#517]
Is there any way possible to override the label names via the edit form override config?  I attempted the following on the Data tab -> Persistence key but nothing changed.

`editForm: {
        textfield: [
          { key: 'display', ignore: false, components: [ { key: 'placeholder', ignore: true} ]},
          { key: 'data', ignore: false,
            components: [
              { key: 'persistent', ignore: false, label: 'Save Where?',
                values: [
                { label: 'None', value: false },
                { label: 'Patient Profile', value: true },
                { label: 'Patient and Vendor', value: false}],
              },
            ],
          },
        ],
      },`

If not, I would be interested possibly making a pull request to extend the config override for label names, but would likely need a little kick in the right direction.  I'm scouring through WebformBuilder.js at the moment and see some things around this options...is this a good starting point?  Thanks.

**Comment by travist** [comment]
```editForm``` is a function that returns the form.  Can you try to change it to the following?

```
editForm: () => {
  return {
    components: [
       ...
    ]
  };
}
```

**Comment by JRiggenbach** [comment]
@travist Thanks for the response.  I missing where editForm is a function however; perhaps my question was misleading. I'm following the custom form builder [example](http://formio.github.io/formio.js/app/examples/custombuilder.html) and it has editForm as a simple JSON object.

I attempted to modify my options per your recommendation, but it didn't seem to work; I wasn't even able to ignore certain components either
![builderoptions](https://user-images.githubusercontent.com/1473610/79145112-15a22f80-7d8e-11ea-8167-45ba52b9b751.PNG)

**Comment by travist** [comment]
Instead of overriding them from the "options" just override the component directly, like this.

```
const TextFieldComponent = Formio.Components.components.textfield;
TextFieldComponent.editForm = function() {
  return {
    components: [
      {
        label: 'Label',
        key: 'label',
        type: 'textfield'
      }
    ]
  };
};
```

Interesting Note:  You can actually run the snippet in your console when viewing our Next portal @ https://next.form.io to see how it works. You can also view any components EditForm by running the following in console.

```
console.log(Formio.Components.components.textarea.editForm());
```

**Comment by JRiggenbach** [comment]
@travist Thanks for the kick in the right direction.  Learning more and more about this library each day.  I just registered my own custom angular component; don't know how it's going to work in the wild yet, but the fact I was able to add my own custom angular component to this tool is awesome.  Keep up the great work!  Once I get more comfortable with this repo, I'd love to come back and contribute to it.

**Comment by firadisaad** [comment]
Hello everybody

`const TextFieldComponent = Formio.Components.components.textfield;`
doesn't work for me,
i cannot find Formio, do i need to import some library ?

thanks.

**Comment by JRiggenbach** [comment]
@firadisaad You might be getting stomped by Typescript.  Try adding a declare statement for Formio and set the type to any



`import { Component, AfterViewInit, ViewChild, ElementRef } from '@angular/core';
import { FormManagerConfig } from 'angular-formio/manager';
import { FormBuilderComponent } from 'angular-formio/core';
import { ActivatedRoute } from '@angular/router';
import { editForm } from '@questionnaire/formioConfig';

**declare var Formio: any;**

const TextFieldComponent = Formio.Components.components.textfield;
TextFieldComponent.editForm = () => editForm;

@Component({
  selector: 'app-questionnaire-builder',
  templateUrl: './questionnaire-builder.component.html',
  styleUrls: ['./questionnaire-builder.component.scss'],
})
export class QuestionnaireBuilderComponent implements AfterViewInit {
...`

**Comment by firadisaad** [comment]
i'm really appreciate it, thanks

**Comment by lfbertucci** [comment]
Hi, sorry for this reply so late, but I'm facing the same problem, trying to change de default labels from editForm.

I managed to change the editForm function from textfield directly in component, but the labels doesn't change. @JRiggenbach can you provides some example? 

I appreciate it.
thks
