### ISSUE TITLE
[QUESTION] How to change a component's key name in the form builder

### ISSUE THREAD

**Issue by sofiaisreis** [formio/angular-formio#525]
Hello there!
I am trying to rename the form-builder tab’s internal options like “label”, but I can't figure out how.
Is is possible? I want to have 'Question' instead of 'Label'. I would appreciate an example, if possible.
 
![image](https://user-images.githubusercontent.com/9540964/79882321-4e738180-83ea-11ea-8f5c-3b5291382967.png)

Thanks in advance! :)

**Comment by travist** [comment]
Yes you can do this. Every component has its own editForm property. You can see it by typing the following in the console.

```js
Formio.Components.components.textfield.editForm();
```

This just returns JSON that is the edit form. This JSON can be modified by doing something like the following.

```js
var editForm = Formio.Components.components.textfield.editForm;
Formio.Components.components.textfield.editForm = function() {
  var json = editForm();
  var comp = FormioUtils.getComponent(json.components, 'label');
  comp.label = 'This is different!';
  return json;
};
```

You can try this out in the browsers console at https://next.form.io to see it working.

**Comment by sofiaisreis** [comment]
Thanks!
