### ISSUE TITLE
Add a custom group to my formio builder[Question] 

### ISSUE THREAD

**Issue by firadisaad** [formio/angular-formio#528]
Hello,

I'm wondering how to add a custom group like basic, advanced, Layout ...

thanks

**Comment by wag110894** [comment]
Hello @firadisaad, can you take a look at this example: https://formio.github.io/formio.js/app/examples/custombuilder.html

**Comment by firadisaad** [comment]
@wag110894 thanks for your replay,

i'm using angular 8 with typeScript, for that i need to know more information to implement it.

thanks.

**Comment by travist** [comment]
You can pass in the options shown in the custombuilder example using the [options] parameter in the ```<form-builder></form-builder>```

**Comment by dmenne** [comment]
See https://github.com/dmenne/custom-radio/blob/master/src/app/app.component.ts for an example.

**Comment by firadisaad** [comment]
@dmenne  thank you so much !
