### ISSUE TITLE
How to register a new component group

### ISSUE THREAD

**Issue by dmenne** [formio/angular-formio#544]
I want to insert my custom components in a separate group. I have read 

https://github.com/formio/ngFormBuilder/issues/422#issuecomment-489523758

but how would I do this in Angular?

Related: I want to create a group with all suggested components - new from me, and a collection of exisiting one.

**Comment by travist** [comment]
Form builder groups are registered through the configuration provided to the core builder library. Here is an example configuration that creates a new group. 

https://formio.github.io/formio.js/app/examples/custombuilder.html

I believe this could be translated to the builder like so.

```
<form-builder [options]="{
  builder: {
    ...
  }
}"></form-builder>
```

Hope this helps.

**Comment by dmenne** [comment]
Thanks, works.
