### ISSUE TITLE
What type is "value" in a multiple-select box?

### ISSUE THREAD

**Issue by dmenne** [formio/angular-formio#545]
In a multiple-select box, the following is transferred as JSON:

      "mySelect": {
          "first": true,
          "second": false
      },
If I want to mimic this behavior for custom components, what should I use as type, for example in the following:

```
implements FormioCustomComponent<{}>

 @Input()
  value: {}

 @Output()
  valueChange = new EventEmitter<{}>()

  updateValue(payload: string) {
  // Dummy implementation:
    this.value = { first: true, second: false }
    this.valueChange.emit(this.value) ;
  }

```

**Comment by merobal** [comment]
See: https://www.typescriptlang.org/docs/handbook/utility-types.html#recordkt
E.g. `Record<string, boolean>`

**Comment by dmenne** [comment]
I had already tried variant of the above, but why is `value` always reset to an empty string ('')? 

```
export class MulticheckButtonsComponent  implements
  FormioCustomComponent<Record<string, boolean>>, OnInit {

  @Input()
  value: Record<string, boolean>
```

**Comment by dmenne** [comment]
Ok, got it.
```
emptyValue: {} // Optional: the emptyValue of the field
```
