### ISSUE TITLE
Info:  Missing icons when using fortawesome

### ISSUE THREAD

**Issue by dmenne** [formio/angular-formio#547]
npm `fontawesome` uses version 4 of the icons. Since I needed some of version 5 icons, I used

```
 "@fortawesome/fontawesome-free": "^5.13.0",
```
in package.json

and
```
  "node_modules/@fortawesome/fontawesome-free/css/all.css",
```
in angular.json. Works almost, but some of the default icons in the editors are missing, eg. move, remove. You can get them back with the following in styles.scss:

``` 
.fa-remove:before {
  content: "\f00d"
  }

.fa-times-circle-o:before {
    content: "\f057"
}

.fa-arrows:before {
  content: "\f0b2"
}
```

**Comment by wag110894** [comment]
@dmenne, 

We have this item as an existing backlog item. For reference, the ticket number is FJS-523. We will let you know once we have upgraded to support version 5 of fontawesome.

**Comment by dev-thinks** [comment]
cool workaround @dmenne. meanwhile, here is the code for fa-refresh icon for signature-

.fa-refresh:before {
  content: "\f021"
}

**Comment by dmenne** [comment]
Sorry, I am gone. We decided to give up on formio, documentation on customs stuff is just too sparse. Using ODK Collect now, much less flexible, but it works.
