### ISSUE TITLE
Formio builder doesn't set the key correctly on text inputs

### ISSUE THREAD

**Issue by sterichards** [formio/angular-formio#551]
Using a text input as an example, if I add that field to the form, the key is always `textField1` or `textField2` etc

There doesn't seem to be an option to edit that key via the formio builder interface

This causes problems for me because I want to store a form rendered response, but it looks like the following:

```
{
    "textField1": "Michael Jordan",
    "email": "michael@jordan.com",
    "submit": true,
    "textField2": "silver",
    "textField3": "rodman",
    "doYouOwnACar": "yes",
    "doYouHaveAPet": "yes",
    "age": 50,
    "whatYearWasItMade": 2016
}
```

But that is not useful once stored in a database because the text input key fields don't represent the question that was asked to the user

**Comment by wag110894** [comment]
@sterichards You can edit the API key to whatever you would like so that it relates to the question that the user is asking.

**Comment by sterichards** [comment]
> @sterichards You can edit the API key to whatever you would like so that it relates to the question that the user is asking.

Do you have any documentation links for this as I cannot find anything regarding this

**Comment by wag110894** [comment]
Hello @sterichards 

Here you go: https://documenter.getpostman.com/view/684631/formio-api/2Jvuks?version=latest

**Comment by sterichards** [comment]
> Hello @sterichards
> 
> Here you go: https://documenter.getpostman.com/view/684631/formio-api/2Jvuks?version=latest

I am not using the formio api. I have built a custom web service that stores the form JSON in a database and that is then retrieved with a web service call to build the form renderer

The JSON from the user response is then sent to a separate web service endpoint

But the problem is that the form builder, when creating the form, isn't giving me any option to set the key of form element on text fields so I have no reference to the form label/question

**Comment by travist** [comment]
> But the problem is that the form builder, when creating the form, isn't giving me any option to set the key of form element on text fields so I have no reference to the form label/question

Are you saying that you do not see the ```Property Name``` field when you edit the component under the API tab?  That is the option to set the key of the form element on text fields.

**Comment by sterichards** [comment]
> Are you saying that you do not see the `Property Name` field when you edit the component under the API tab? That is the option to set the key of the form element on text fields.

I don't have an API tab as seen here - https://ibb.co/QFBXZzn

**Comment by sterichards** [comment]
I have solved the issue which was caused by my own fault

I had added the following to the formOptions JSON:

```
editForm: {
      textfield: [
        {
          key: 'api',
          ignore: true
        }
      ]
    }
```
