### ISSUE TITLE
[Custom Components] 

### ISSUE THREAD

**Issue by ashusaini** [formio/angular-formio#553]
**Explicit Options
Due to performance reasons not all the options are bound to the component. If you want to reach fields from the schema, define in the fieldOptions array at the field registration.**

I am creating custom input like select and i want to access values i.e. array. but when i am adding fieldOptions: ['values']  and try to bind   
`@Input() values: any; `
in the component i am not able to see change in values as per doc it should be reflected in the document.

**Implicit Custom Options**
It is rendering in Edit form but

I tried to add customOption as well and tried to get it in 
`@Input() myoption `
it's also not reflecting the changes i am getting 'undefined'.

**Comment by ashusaini** [comment]
I got it it's not reflecting in ngOnInit but it's working.No issues Thanks

**Comment by sandeepaem** [comment]
@ashusaini It is interesting, I couldn't figure out how you were able to access the variables.

I have used 4.7.0/4.9.0 and even the latest 5 version too, but nothing is returning Custom Fields from Edit form. Only @input() placeholder is returning the value as expected, not even Key of the Component. 

Kindly provide your expertise, Thanks

**Comment by sandeepaem** [comment]
Hi, Thanks, I got it, Form.io Developers are attaching the fieldOptions as @Input fields, just that they are not available at NgOnInit.

Interesting if somehow make it work on NgOnIt. Thanks.

 if (isArray(fieldOptions) && fieldOptions.length > 0) {
                        for (var key in fieldOptions) {
                            if (fieldOptions.hasOwnProperty(key)) {
                                this._customAngularElement[fieldOptions[key]] = this.component[fieldOptions[key]];
                            }
                        }
                    }
