### ISSUE TITLE
How to add a new tab in formio Angular?

### ISSUE THREAD

**Issue by ajaykumarsana** [formio/angular-formio#554]
Hi @travist ,
I been searching through the issues a lot for "Adding custom tab in form io", 
Here i elaborate more what's query is ?

After drag any component this is how it appears, is it possible to add custom tab beside to any existing tab?
![image](https://user-images.githubusercontent.com/1854019/83145609-af415880-a112-11ea-8578-b250564a01e2.png)

please help me. Thanks a lot

**Comment by travist** [comment]
You just need to modify the "editForm" of that component and add another tab to the JSON of the tabs component there. Something like this maybe?...

```
const editForm = Formio.Components.components.textarea.editForm;
Formio.Components.components.textarea.editForm = function() {
  const form = editForm();
  const tabs = Formio.Utils.getComponent(form.components, 'tabs');
  tabs.components.push({
    key: 'custom',
    label: 'Custom',
    components: [
      ...
    ]
  });
  return form;
};
```

**Comment by ajaykumarsana** [comment]
Hi @travist 
Thank you for the response, I'm having one issue here.
I.e when i try to print tabs in console custom tab shows but in UI **custom** tab not appear.
PFA.
![image](https://user-images.githubusercontent.com/1854019/83227337-93d15e80-a1a1-11ea-9919-dc6a5ff76b5d.png)

Pleae help!!

**Comment by travist** [comment]
My code above would have edited it for the Text Area component only. Here you are showing Text Field. Is that the issue?

**Comment by ajaykumarsana** [comment]
Hi @travist 
No, In your code i've made changes to textfield and applied. 
Can you please provide a solution?

**Comment by ajaykumarsana** [comment]
Hi @travist 
I'll share my code snippet , please let me know where did i missed.
**app.module.ts**
`import { AppConfig } from './formio-config';
import { FormioAppConfig} from 'angular-formio';
import { Components , Utils  } from 'formiojs';

const editForm = Components.components.textarea.editForm;
Components.components.textarea.editForm = function() {
  const form = editForm();
  const tabs = Utils.getComponent(form.components, 'tabs', true);
  tabs.components.push({
    key: 'custom',
    label: 'Custom',
    components: tabs.components[3].components
  });
  return form;
};

console.log(Components.components.textarea.editForm());`

I've tried to print `console.log(Components.components.textarea.editForm());` in the html where i use **form-builder** 

 both console.log statements showing **custom** tag which shown as below 
![image](https://user-images.githubusercontent.com/1854019/83326743-18040e80-a294-11ea-8a11-b039c541437e.png)


But its not showing in UI :(

So, do we need to register or export **editForm** in above code to reflect in UI?
please help.
Thank you for your patience in reading my comments.

**Comment by travist** [comment]
We will need some time to work up the prototype for this and provide a more detailed example (as well as try out your example). We may not get to this until later this week, but maybe someone from the community has done this and can provide code snippet.

**Comment by sr-msilva** [comment]
I am assuming that the logic of the formio works as if everything were Component. So I followed this concept and it worked here as follows:

<pre>
 Formio.builder(document.getElementById('builder'), {},{
            //attachMode:'full',
            editForm: {
                textfield:[
                    { 
                        key: 'display', //Add in existing tab
                        components: [ 
                            {
                                title: 'Add field in existing Tab',
                                key: 'demo1',  
                                type: 'textfield', //field type, any existing and valid component
                                label: 'Add field in existing Tab Label',                            
                                input: false
                            }
                        ]
                    },
                    { 
                        key: 'newTab', //ADD new custom TAB
                        label:"NEW Tab",
                        components: [  //ADD custom components in TAB
                            {
                                title: 'First Name',
                                key: 'firstname',  
                                type: 'textfield',
                                label: 'First Name',                            
                                input: true
                            },
                            {
                                title: 'List Names',
                                key: 'listnames',  
                                type: 'textarea',
                                label: 'List Names',                            
                                input: true
                            },
                        ]
                    },
                    {
                        key: 'api', //remove TAB
                        ignore: true
                    }      
                ]
            }
</pre>

![Captura de tela_2021-05-02_01-44-50](https://user-images.githubusercontent.com/25569858/116802484-92af5c80-aae9-11eb-9765-dd675fe03ae4.png)
![Captura de tela_2021-05-02_01-44-43](https://user-images.githubusercontent.com/25569858/116802491-a22ea580-aae9-11eb-8678-aa1330fe8c75.png)
![Captura de tela_2021-05-02_01-45-00](https://user-images.githubusercontent.com/25569858/116802495-a8248680-aae9-11eb-97cc-3cb504ffbb3c.png)

**Comment by vinayrdy966** [comment]
how to add click event here like in api tab, add another which add key and tab

**Comment by lane-formio** [comment]
I'd suggest opening a new issue and possibly give some more information on what you are trying to do now?

**Comment by vinayrdy966** [comment]
thanks for quick response.
submitted new issue - [https://github.com/formio/angular/issues/1068](https://github.com/formio/angular/issues/1068)

**Comment by vinayrdy966** [comment]
How to add button event in formio? I'm adding custom button in angular formio.
