### ISSUE TITLE
[Question] How to take translation input from user creating the form?

### ISSUE THREAD

**Issue by jyoti0291** [formio/angular-formio#557]
Hi @travist and @YuryRybakSoftensity 
Is there any way to take the label translations input directly from the user while adding any component to the form?

Like add more input fields for label translations:
Label --> Default Language (en)
Label ja --> japanese
Label sp --> Spanish

and so on...

<img width="996" alt="Screen Shot 2020-05-29 at 12 55 48" src="https://user-images.githubusercontent.com/22149791/83233380-3bec2500-a1ac-11ea-8a1a-d9404e3eb621.png">

Any help would be appreciated!!!

**Comment by travist** [comment]
We currently do not have a way to do this, but have developed a pattern that would allow translations outside of the rendering environment. Please see https://help.form.io/tutorials/walkthroughs/resource/ as an example.

**Comment by jyoti0291** [comment]
Got it @travist 

Thank you so much.
