### ISSUE TITLE
Form-Builder:How to Customize Field Properties Popup

### ISSUE THREAD

**Issue by ASHIK5261** [formio/angular-formio#566]
I need to customize the popup of field properties/settings. 
- How to hide/remove the some tabs
- How to hide/remove the properties under the tab 
- How can add new property/tab 

These are the requirements, suggest me a appropriate method to customize the popup

**Comment by wag110894** [comment]
@ASHIK5261 here is an example of how you can accomplish this: https://formio.github.io/formio.js/app/examples/custombuilder.html

**Comment by ASHIK5261** [comment]
Thanks @wag110894 
Here we can ignore the tabs in Edit Form.  I have more requirements.Do you have any solution for ignore some of the property of field in Edit Form. Like ignore the 'Tooltip' property in edit Form

**Comment by ASHIK5261** [comment]
@wag110894  I got the Solution. thanks
Here is the solution
"editForm": {
              "textfield": [
              {
                  "key": "display",
                  "ignore": false,
                  "components": [
                      {
                          "key": "placeholder",
                          "ignore": true
                      },
                      {
                        "key": "tooltip",
                        "ignore": true
                      },
                      {
                        "key": "widget",
                        "ignore": true
                      }
                  ]
              }      
          ]
        }

**Comment by dharaneshbestha** [comment]
Hello, would you be able to explain your solution, I am stuck at this same point, I need to hide few properties from the modal.

Thanks in advance.
