### ISSUE TITLE
[Question] Is there a way to override a formio onSubmit event?

### ISSUE THREAD

**Issue by dev-thinks** [formio/angular-formio#568]
Is there a way to override a formio onSubmit event? I tried to do as below, but no luck, not sure what am missing.

`import {Webform} from 'formiojs/Webform';

Webform.prototype.onSubmit= {...}`

Webform is resolving as undefined. any help appreciated. Tx

**Comment by travist** [comment]
I would use the module system for this. It looks like the following.

```js
import { Formio } from 'formiojs';
const Webform = Formio.Displays.displays.webform;

class ExtendedWebform extends Webform {
  onSubmit() {
    ....
  }
}

Formio.use({
  displays: {
    webform: ExtendedWebform
  }
});
```
