### ISSUE TITLE
[Question] Trigger renderer validation  

### ISSUE THREAD

**Issue by AleksandarKurta** [formio/angular-formio#570]
I have a submit button outside formio which i call on form submission, how can I trigger form validation?

**Comment by travist** [comment]
You can call the method ```checkValidity``` on the form instance and it will trigger form validation.

```js
form.checkValidity();
```

**Comment by dev-thinks** [comment]
@travist Thanks. this works, but is there a way to show/highlight the UI validation error messages? (as the normal submit behavior does inside formio) ?

**Comment by travist** [comment]
You can do this by passing the "dirty" flag to ```checkValidity```.

```js
form.checkValidity(null, true);
```

**Comment by dev-thinks** [comment]
Worked !!

Thanks for the help. I think we can mark this question as answered.

**Comment by ajaykumarsana** [comment]
@travist 
@dev-thinks 
@AleksandarKurta 

Can you please help me to have **form** instance in the method `form.checkValidity(null, true);`?
I couldn't locate checkValidity method in formio-angular repo https://github.com/formio/angular.
Probably i'm referring  at other locations.

Please help,
Thanks

**Comment by HaseebZahidengg** [comment]
@ajaykumarsana 

You can create an in stance of Formio 
import { Formio } from '@formio/angular';

Then by creating form by using Formio you can access form.checkValidity() function like this.

Formio.createForm(document.getElementById('formioRenderer'), this.formJson).then((form) => {
     form.checkValidity()
 });
