### ISSUE TITLE
[Question] how to use saveDraft in <formio>

### ISSUE THREAD

**Issue by thambui** [formio/angular-formio#574]
i have a question about saveDraft. I'm using `<formio src="{{ myUrlConfig }}"></formio>`. How can i use saveDraft in that?

**Comment by phamtien170996** [comment]
Have the same question with @thambui. I just found it in FormIO JS https://formio.github.io/formio.js/app/examples/savedraft.html. Can you please provide some information if you have?

**Comment by travist** [comment]
If you wish to have them manually saveDraft, then this can just be configured in the Form builder by adding a new Button and set the action to "Save in state" and then add "draft" to the state that will be saved. This will allow the submission to be saved as "draft". If you wish to "auto-save" then this can be configured as part of the formioOptions added to the <formio> directive like so.

```html
<formio [formioOptions]="{
  saveDraft: true
}"></formio>
```

**Comment by sandormariqldtreasury** [comment]
Is there any way to retrieve the state value of the Submission?
