### ISSUE TITLE
[Question] How do you perform a Token Swap in Angular?

### ISSUE THREAD

**Issue by daddywoodland** [formio/angular-formio#580]
Is there any way of performing a [token swap](https://help.form.io/integrations/oauth/#token-swap) in the Angular Library?

I've had a look through the source and can't find anything.  Thanks for any helpy ou can offer.

**Comment by travist** [comment]
The token swap is just an API call. You can do this either using a "fetch" library provided through Angular, or you can probably use the ```Formio.request``` method as part of our JavaScript SDK, but ultimately this is just an API call that needs to be made to the server to perform this function.

**Comment by daddywoodland** [comment]
Thanks Travis :)

So one of the end points listed in the [API documentation](https://apidocs.form.io/?version=latest#03acc709-aaba-b066-c69b-fb7ab92a48d0) will allow me to swap tokens?

**Comment by daddywoodland** [comment]
> The token swap is just an API call. You can do this either using a "fetch" library provided through Angular, or you can probably use the `Formio.request` method as part of our JavaScript SDK, but ultimately this is just an API call that needs to be made to the server to perform this function.

Hi again @travist , sorry to be a pain but I've been looking over the API documentation and reread the docs but can't see where to call on the API to setup a token swap, are you about to point me in the right direction please?

**Comment by travist** [comment]
This should be just the "/current" endpoint documented @ https://apidocs.form.io/?version=latest#05418b8d-c761-c34e-bbae-ccb434619aea but using the Bearer token headers described in the token swap documentation @ https://help.form.io/integrations/oauth/#token-swap

**Comment by daddywoodland** [comment]
Thanks, I'm trying but getting a bad request at the mo.  WIll persevere though!  I set the header as described in the token swap example too but am thinking I need to find a way to send through 'external: true' as well.  

The sample request/response in the docs for this end point looks to be a duplicate of 'Form Login' unfortunately so I'll dig around in the code to see if I can find the /current end point and what form it's expecting requests to arrive in.

Thanks again

**Comment by randallknutson** [comment]
Make sure your oauth settings are set up correctly. If it is not set up it will not perform the swap correctly.

**Comment by daddywoodland** [comment]
> Make sure your oauth settings are set up correctly. If it is not set up it will not perform the swap correctly.

Thanks, I'm happy I'm doig the request as instructed now but am getting a 400 Bad Request back unfortunately.  

Things are a bit tricky with the oauth settings and token as I'm trying to integrate firebase auth and the documentation for that is hit and miss but I'll double check.

It would be useful to see the logs from my call to formio API in case there's any hint in there but I can't seem to find them.  

Thanks for your help though!

**Comment by randallknutson** [comment]
They may be in the "Action Logs" section although those have been a little spotty recently. Other than that you can enable DEBUG=formio:* as an environment variable to get more verbose output on a server.
