### ISSUE TITLE
How can I better handle the form JSON in my own database?[Question] 

### ISSUE THREAD

**Issue by sterichards** [formio/angular-formio#584]
I have been developing an Angular 8 CMS which includes angular-form builder / renderer and allows CMS users to create forms and external users to submit forms. When creating a form within the CMS, I POST the JSON to my own custom Symfony API server and store the JSON against a Form entity. That all works good....

When an external user completes and submits a form, the JSON is posted to my own web service and is stored in an FormSubmission entity. That also works good....

Now, the problem I am finding is that it is unreliable to match a form submission response to a form question because I only have string matching to help me

I understand that it is really upon me to write code to handle the matching but I am wondering if there is anything within the angular-formio library that can help me with this?

**Comment by sterichards** [comment]
So after some thought today it seems to me that I need a database representation of each question of each form and also a database representation of each form question response with a database relation between question and form

The form and response JSON will still exist in the database but only for angular formio to parse and display the form and also for the response that formio sends back to my web server

I would appreciate any further suggestions if you are reading this

Many thanks

**Comment by travist** [comment]
The formio.js library contains some utils that allows you to find a component provided the "key" of the data.

```js
const component = FormioUtils.getComponent(form.components, 'firstName');
console.log(component);
```

This can be used to traverse the form components array to find the component JSON that has the metadata to describe the component for a specific field in the submission.

**Comment by sterichards** [comment]
> The formio.js library contains some utils that allows you to find a component provided the "key" of the data.
> 
> ```js
> const component = FormioUtils.getComponent(form.components, 'firstName');
> console.log(component);
> ```
> 
> This can be used to traverse the form components array to find the component JSON that has the metadata to describe the component for a specific field in the submission.

This worked great and is exactly what I needed to help me

Thank you :)

**Comment by ManadayM** [comment]
> When an external user completes and submits a form, the JSON is posted to my own web service

Hi @sterichards,

Could you please let me know how did you manage to post the form data to your endpoint through the Form Render component? I'm unable to spot any documentation around this topic that enables us to set our custom endpoint. I cannot allow any 3rd party service to store our data due to its sensitivity and privacy concerns.

Any guidance or help is highly appreciated.

I also apologize for posting help questions here but I found the Form IO Gitter community is not very active.

**Comment by sterichards** [comment]
> > When an external user completes and submits a form, the JSON is posted to my own web service
> 
> Hi @sterichards,
> 
> Could you please let me know how did you manage to post the form data to your endpoint through the Form Render component? I'm unable to spot any documentation around this topic that enables us to set our custom endpoint. I cannot allow any 3rd party service to store our data due to its sensitivity and privacy concerns.
> 
> Any guidance or help is highly appreciated.
> 
> I also apologize for posting help questions here but I found the Form IO Gitter community is not very active.
> 
> Thanks,
> Manaday

I'm happy to help, it's OK

I am very "rusty" with this project because it got discontinued but I still have the code. Maybe this helps:

Component code - https://pastebin.com/Y3QUuuwL

Template code - https://pastebin.com/1TPbuQrN

If that doesn't help I can give you access to the repo so you can look through the code yourself

**Comment by ManadayM** [comment]
So kind of you. That was very quick @sterichards! Thanks much for your time and efforts.

I think I could've better narrated my question in the first place.

I've achieved all items from the following Todo list except the last one. That's where I seek help.

- [x] Form Builder component integration to design the form
- [x] Saving generated JSON form schema to my (mock) backend API
- [x] Fetching and rendering JSON form schema using Form Renderer (formio) component for my web app users to allow them to fill the form
- [ ] Posting/Saving filled form data to my backend API (This is where I'm stuck).

The code snippets you've shared seem to save JSON Schema (#2) to the backend API which I've also achieved.

If your repo doesn't contain any sensitive information then I'd request you to kindly grant access to it. That'd be a great help. 

Again many thanks! 😊🙏🏼

**Comment by sterichards** [comment]
> So kind of you. That was very quick @sterichards! Thanks much for your time and efforts.
> 
> I think I could've better narrated my question in the first place.
> 
> I've achieved all items from the following Todo list except the last one. That's where I seek help.
> 
> * [x]  Form Builder component integration to design the form
> * [x]  Saving generated JSON form schema to my (mock) backend API
> * [x]  Fetching and rendering JSON form schema using Form Renderer (formio) component for my web app users to allow them to fill the form
> * [ ]  Posting/Saving filled form data to my backend API (This is where I'm stuck).
> 
> The code snippets you've shared seem to save JSON Schema (#2) to the backend API which I've also achieved.
> 
> If your repo doesn't contain any sensitive information then I'd request you to kindly grant access to it. That'd be a great help.
> 
> Again many thanks! 😊🙏🏼

@ManadayM  - https://github.com/sterichards/fillform-web-app

Hope you find what you need

**Comment by ManadayM** [comment]
Thank you so much, @sterichards! I'm going through your implementation now. 🤞🏼
