### ISSUE TITLE
[RENDERER OPTIONS ISSUE]

### ISSUE THREAD

**Issue by EAGarfield** [formio/angular-formio#589]
## Environment
Please provide as many details as you can:

 Hi, I am having an issue while using rendererOptions

error: Can't bind to 'rendererOptions' since it isn't a known property of 'formio.

I included the FormioModule and FormManagerModule and I am still getting the same issue

Are there any other module solutions?

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: "^4.8.0-rc.6",
- Frontend framework:  
- Browser:
- Browser version: 

## Steps to Reproduce
1. 
2. 
3. 

## Expected behavior
breadcrumbSettings:{clickable: false}
## Observed behavior
breadcrumbSettings:{clickable: true}
## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js


<formio [options]="options"
[rendererOptions]="{breadcrumbSettings:{clickable: false}}"
[form]='formJson'
(submit)='onFormSubmit($event)'>
```

**Comment by travist** [comment]
It's ```renderOptions``` and not ```rendererOptions```
