### ISSUE TITLE
[Custom Components] 

### ISSUE THREAD

**Issue by krishanil** [formio/angular-formio#590]
[30563 ISSUE.docx](https://github.com/formio/angular-formio/files/4962084/30563.ISSUE.docx)

 We have  small issue in from-io which we cannot sort it out.  The problem is  text field component validation. Normally  we are using field values Required, maximum, minimum  length , Regular expression (^[0-9]*$] and  Custom error message (Npm id is required ) .  The custom error is displaying twice  when we are validating the form.  I am sending the screen shots  doc  for more information .

no embedded URL for our version, we are using Angular Form IO.
It is embedded  as third party application.

**Comment by wag110894** [comment]
Hello @krishanil, This issue has been resolved in version 4.11.2 of Angular-formio.
