### ISSUE TITLE
[BUG] --FJS-1067

### ISSUE THREAD

**Issue by gopikrishna123** [formio/angular-formio#592]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: ^4.8.0-rc.6
- Frontend framework:
- Browser:
- Browser version:

## Steps to Reproduce
After changing the default values for Checkbox, Select boxes, Select and Radio components, it is not reflected in the Form IO builder section.
In the below screenshot,I have initially set the default radio button value as "a1".This works fine.
But when I am editing the same component and changing the default value to "a2" then it doesn't reflect in the builder section

![image](https://user-images.githubusercontent.com/24910318/88316266-8807a180-cce5-11ea-97dc-2ea331802302.png)

Screenshot after editing the default value to "a2".It still shows "a1" as default in the UI, but the JSON value has got updated correctly.

![image](https://user-images.githubusercontent.com/24910318/88316296-95249080-cce5-11ea-8342-ef5fc96e34fe.png)

**Comment by cmcortez** [comment]
This was reviewed and answered via direct support.

**Comment by iknityanand** [comment]
@cmcortez  can you post the solution here.

**Comment by wag110894** [comment]
@iknityanand Absolutely. This is by design, as our builder mode does not show configurations
