### ISSUE TITLE
[Question] Builder Initialized Output Event

### ISSUE THREAD

**Issue by Vedhachala** [formio/angular-formio#597]
Hi Formio team,
I need the **builder instance** once the builder is initialized. This is similar to the (ready) event available for <formio> selector.
The change output event does not address our use case. 
I am expecting something like this: 
`<form-builder [form]="formJSON" (ready)="builderLoaded($event)"></form-builder>`

So is there any plan to introduce this or any workaround to achieve this.?

**Comment by travist** [comment]
You can get it like this.

```js
import { Component, AfterViewInit, ViewChild } from '@angular/core';
import { FormBuilderComponent } from 'angular-formio';

@Component({
  template: '<form-builder></form-builder>'
})
export class FormRenderComponent implements AfterViewInit {
  @ViewChild(FormBuilderComponent) formBuilder: FormBuilderComponent;
  ngAfterViewInit() {
    this.formBuilder.ready.then((builder) => {
      // "builder" is the form builder instance.
      console.log(builder);
    });
  }
}
```
