### ISSUE TITLE
[Question] Need to remove default submit button from form-builder form

### ISSUE THREAD

**Issue by pooja-waikar** [formio/angular-formio#600]
I am using angular-formio version : ^3.27.3.

<form-builder  [form]="form" (change)="onChange($event)"></form-builder>
this is my tag.how to remove default submit button

**Comment by travist** [comment]
There is a configuration option to remove the default submit button.

```js
<form-builder [form]="form" [options]="{
  noDefaultSubmitButton: true
}"></form-builder>
```

**Comment by pooja-waikar** [comment]
thank you for your quick response.

I tried above solution but it still not working for me.
my angular-formio version is ^3.27.3.
