### ISSUE TITLE
Is there any documentation of the JSON structure of a form that will help my identify the different element types[Question] 

### ISSUE THREAD

**Issue by sterichards** [formio/angular-formio#601]
I am parsing the form JSON into PHP and looping through the structure to identify the form elements, mainly the questions on the form (textfield labels etc)

Is there any documentation that will help me compose a good loop to separate the tabs / panels etc from the actual questions?

**Comment by travist** [comment]
It's a little outdated, but this may help.

https://github.com/formio/formio.js/wiki/Form-JSON-Schema
