### ISSUE TITLE
Passing Authentication in select component to non formio URl endpoint [Question] 

### ISSUE THREAD

**Issue by bandman0226** [formio/angular-formio#602]
We recently upgraded to:
angular formio 4.9.2 and fomiojs 4.9.26

When using a select component we would use plug in hooks to set our authentication for our endpoint (not formio) using the preRequest. After the upgrade the preRequest does not fire off and anything else we tried to use seems to get a 401. Has anyone else done this and if so how can this be accomplished?

**Comment by saravanapriyanm** [comment]
Have you found a solution?
