### ISSUE TITLE
language has been removed from FormioOptions 

### ISSUE THREAD

**Issue by sriram275** [formio/angular-formio#604]
Team,

Due to removal of this property from FormioOptions, now difficult to set language as one of the option to formio by using 
`<formio [form]="myFormJSON" [options]="myFormioOptions"></formio>` 
component of angular-formio for renderer.

And got removed this line in the following assigning options code and which was there erlier versions of angular-formio.
**```language:get(this.options, 'language', null),```**
https://github.com/formio/angular-formio/blob/353ec7b7d7832ba125c0cf1c90afa1944321334b/src/FormioBaseComponent.ts#L84

Is there any way to pass language by **using formio component of angular-formio library**? 

This option is there in `<form-builder></form-builder>` component but only issue in `<formio></formio>`

Thanks.

**Comment by travist** [comment]
Just add it to the ```renderOptions```.

```html
<formio [renderOptions]="{
  language: 'en'
}"></formio>
```

**Comment by sriram275** [comment]
Yeah,  I have done the same before your reply and it worked.
Will it help some on if we document here https://github.com/formio/angular-formio/wiki/Translations

**Comment by travist** [comment]
Yes, I will add that.
