### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by alanm101** [formio/angular-formio#606]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: N/A
- Frontend framework: N/A
- Browser: Chrome and Safari
- Browser version:

## Steps to Reproduce
1. Go to: https://formio.github.io/angular-demo
2. Enter test details
3. Submit

## Expected behavior
Submit response is "Submission Complete"

## Observed behavior
Submit response is "[object Object]"

## Why is this a problem?
The same response is shown on custom deployments.
## Example
See attached screen recording.

<img width="579" alt="CleanShot 2020-08-10 at 15 12 37@2x" src="https://user-images.githubusercontent.com/2248721/89786299-fe950380-db1b-11ea-8cc9-c078fff7f0cc.png">

**Comment by alanm101** [comment]
Screen shout from Ubuntu & Firefox. Same issue. Remember, this is on the HOSTED example of the formio angular demo app. 
<img width="890" alt="CleanShot 2020-08-10 at 16 23 18@2x" src="https://user-images.githubusercontent.com/2248721/89793415-212c1a00-db26-11ea-8762-49269010f8e6.png">

**Comment by wag110894** [comment]
Hello @alanm101, Thanks for reaching out!  This was an issue from formio.js. This issue is resolved, but we have not updated the angular demo page to the latest. We will get that updated and the issue will no longer occur. 

Have a great day!

**Comment by alanm101** [comment]
I closed too soon. Thanks for the response @wag110894. I did mention the problem is occurring in a custom deployment. The example shown was to eliminate user (i.e. me) errors.

I did a clean installation of formio v1.90.5 and angular-demo 2.7.0. I then created my own forms and included them in the angular cards. That's where my problem is causing issues.

If the problem is in the angular-demo 2.7.0 codebase, please suggest a solution. A lower codebase? A different formio.js inclusion?

Thanks,
Alan.

**Comment by alanm101** [comment]
Resolved with change to package.json.
