### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by thanhvietnguyen255** [formio/angular-formio#612]
Hello everyone, 
Could you give examples on how to export a form/form submission to PDF file?
Or convert to HTML so from that HTML I can export to PDF file.

I'm using package angular-formio-pdf
However, it's not pretty. It cannot export the signature (it display base64 instead of an image) and some other issues.

Thanks.

**Comment by travist** [comment]
angular-formio-pdf is not a library that we support, and PDF export is actually an Enterprise feature that we offer. If you do not want to use our Enterprise platform, then I am afraid you will need to come up with a solution from the community.

**Comment by thanhvietnguyen255** [comment]
Thanks for your answer @travist .

Is there no other solution?
I only use the PDF export feature instead of all features of the Enterprise platform so I don't really want to buy it.
I have searched but no luck from the community. Hope you can suggest me some free packages.

Regards.

**Comment by thanhvietnguyen255** [comment]
Never mind about it. I will use this package https://github.com/UN-FAO/fast-export
