### ISSUE TITLE
[Question] How to translate Datepicker

### ISSUE THREAD

**Issue by Stefan99353** [formio/angular-formio#616]
Hi,

how is it possible to tranlate the Datepicker popup. I think formio is using Datepickr as their picker.
I want to tranlate/set the locale to german.
Can i do this by using the options binding of the formio tag?

**Comment by randallknutson** [comment]
We have information about this in this issue: https://github.com/formio/formio.js/issues/2040

**Comment by randallknutson** [comment]
https://github.com/formio/formio.js/pull/3129
