### ISSUE TITLE
[Question]  Any way to include Max file count and total file size in "File" component

### ISSUE THREAD

**Issue by dev-thinks** [formio/angular-formio#621]
As the referred [angularjs file component](https://github.com/danialfarid/ng-file-upload#full-reference) has this feature, is there a way to define it in anguar-formio file component?

a. max file count allowed
b. total file size allowed

Thanks,

**Comment by travist** [comment]
Our file component does not use the angularjs file component. This would be a separate implementation in the formio.js renderer @ https://github.com/formio/formio.js

**Comment by dev-thinks** [comment]
Thank you @travist. but am not seeing a property for max file count when uploading multiple or total file size. Am i missing something or any other workaround?

**Comment by travist** [comment]
This would need to be developed as a new feature. You would not see it with current implementation until this feature is added.

**Comment by dev-thinks** [comment]
Thank you for confirmation.
