### ISSUE TITLE
[Custom Components] Access Relative Form Data

### ISSUE THREAD

**Issue by michealharrington** [formio/angular-formio#629]
Hi,
I'm trying to create a custom component that is driven by the data in the datagrid row that it is in.
Ex. Column 1 selects an option from a drop down, my custom component in column 2, needs to know what was selected in column 1.

I can't find any way to have my custom component get access to the forms data.
I've thought about this solution: https://github.com/formio/angular-formio/issues/471 but the custom component does not contain any identifying information so changing column 1 in a row would affect ALL rows because the custom component doesn't know what row it is in.

Any advice would be appreciated.

**Comment by wag110894** [comment]
@michealharrington, are you still experiencing this issue? If so, we do offer Support Packages that are for training, support or development services. The hours can be used in one-hour increments at your convenience over a 90 day period. We will assign one of our senior developers to work directly with you in online sessions. Please let me know if you are interested and I can provide you with our Support Package Options.

**Comment by michealharrington** [comment]
I found a way around this by using Logic to pass data down into the "placeholder" input where my custom component can grab it and perform actions on it.

**Comment by wag110894** [comment]
Great to hear! I will close this ticket.
