### ISSUE TITLE
[Question] Can you provide a shared prop for duplicate customConditional props across multiple components/tabs/etc.?

### ISSUE THREAD

**Issue by penrodlol** [formio/angular-formio#634]
Scenario: I have a formio-builder whos JSON config has multiple components and tabs. Some of these components and tabs share the same customConditonal prop w/ same logic.

Proposition: I'd like to cut back on the redundancy here by potentially providing some form of shared config prop in which each customConditional duplicate scenario can inherit. I know of ways where you can use FormioUtils to traverse through your JSON config but I'd prefer to add just a single config prop within my JSON to be inherited throughout and avoid having to write any traversal logic. To put it simple, is there a way to initialize custom metadata to be inherited across your JSON config? Not sure if there's a way to accomplish this...

**Comment by travist** [comment]
This is what form modules can do. If you use our hosted platform, you can see this if you edit your project configuration and click on Custom JS and CSS. Here you can do something like this.

```
{
  options: {
    form: {
      evalContext: {
        validatePhone: function(input) {
          return input.match(/^[2-9]\d{2}-\d{3}-\d{4}$/);
        }
      }
    }
  }
}
```

This will now introduce ```validatePhone``` into all evaluation contexts and can be used like so.

```js
valid = validatePhone(input) ? true : 'Phone is invalid';
```

This can also just be passed into the renderer using the options of the renderer itself if you are not using the hosted form modules.

**Comment by penrodlol** [comment]
@travist Used this in my project and it worked! Thanks!!
