### ISSUE TITLE
[Question] Does this project support Angular 10?

### ISSUE THREAD

**Issue by qingliaowu** [formio/angular-formio#636]
Does this project support Angular 10?

**Comment by travist** [comment]
Yes, we just upgraded this library to Angular 10, but it is still in an "alpha" state. The version 5.x of this library is the version that supports Angular 10. This is currently available as 5.0.0-alpha.1 but we are in the process of upgrading our applications to fully support and test the official 5.x release.

**Comment by qingliaowu** [comment]
Got it, thank you Travis
