### ISSUE TITLE
Data table data filter option, Column level search functionality [Question] 

### ISSUE THREAD

**Issue by Kadhiresan-K** [formio/angular-formio#637]
Hi All and @travist 

**Question**: How to add a column-level search option in the data table, like the below-attached image I need to provide a filter option to the end-user.

![Screenshot 2020-10-22 at 10 30 49 PM](https://user-images.githubusercontent.com/70190306/96905590-44742d80-14b6-11eb-9308-e64ba551f5f1.png)

Here using Search Name, Search Position, Office, Age, Start date, and Salary textbox users can filter the data on the UI side. **Note**: Only search for the data which is available on the page/UI, no need to make any API calls when searching.

I have referred to the [angular-formio Data Table](https://github.com/formio/angular-formio/wiki/Data-Table), But not able to find a search option related code.

Tech I am using Angular 9
formiojs: "^4.8.0-rc.12"
angular-formio: "^4.6.7"

Any example/reference related to the above question will help, Thanks.

**Comment by travist** [comment]
We do not have a search option in our "built-in" grid feature. It would need to be added. The other alternative is you can hook up any grid library to the API's provided by the Form.io submission API's.

**Comment by Kadhiresan-K** [comment]
ok, thanks

**Comment by Kadhiresan-K** [comment]
Hi All and @travist 

Is there is any way to detect the TextField onChange, instead of capturing Form onChange 
(OR )
Is there is any way to add a custom function(trigger) to the TextField, So that I can write my own logic to filter the data for the data table, like the screenshot attached in the previous message?

**Comment by travist** [comment]
You can do something like this.

```js
var textFieldChange = Formio.Components.components.textfield.prototype.onChange;
Formio.Components.components.textfield.prototype.onChange = function() {
  console.log('Textfield has changed!!!');
  return textFieldChange.apply(this, arguments);
};
```

**Comment by sudheerReddy9047** [comment]
@Kadhiresan-K can you please share the code snippet you used to achieve the column level filter in table.

**Comment by sudheerReddy9047** [comment]
@travist can you help to implement filter for data grid based on the value of the 1st component inside data grid ?
