### ISSUE TITLE
[BUG] [FormBuilder] Property name in API page don't allow Chinese but will be changed automatically once Label in Display Page is typed with Chinese.

### ISSUE THREAD

**Issue by huangchinlin** [formio/angular-formio#644]
angular-formio: 4.11.0
formio: 4.12.0-rc.19

[FormBuilder] 
Property name in API page don't allow Chinese but will be changed automatically once Label in Display Page is typed with Chinese.

**Comment by wag110894** [comment]
Hello @huangchinlin,

Thanks for reaching out!

You can save the component initially and then go back and change the Label to Chinese.

**Comment by huangchinlin** [comment]
@wag110894 Thanks! It can be a temporary solution, beacuse need at least 2 times efforts to create a new form.

I'd like to suggest that can make a global setting to assign the prefix for "Key" value. When it be setted, related processes can reference it to generate the "Key" value in "New Form process". 

for example: 
  if prefix != "" or undefined or null, the result of Key will be prefix1~N.
  else: key = Label || Title || ... || ...

**Comment by travist** [comment]
We would support such an option. If you add a pull request to https://github.com/formio/formio.js with this proposed change, then we will review and accept it.

**Comment by huangchinlin** [comment]
@travist Thanks for reply. I have post the request. https://github.com/formio/formio.js/issues/3457
