### ISSUE TITLE
[Question] Adding styles to one of the columns in column component

### ISSUE THREAD

**Issue by praveend03** [formio/angular-formio#649]
Hello,

I am exploring and learning the angular-formio, I would like to know whether anyone can add a style, for ex: border, to one of the columns in the column component. I am not able to find a way to customize the styles for each of the columns in the column component. I would really appreciate your help to answer this question. Thank you.

**Comment by travist** [comment]
This would be done with just CSS added to your Angular application.

**Comment by praveend03** [comment]
@travist Thank you very much for the response.
