### ISSUE TITLE
Dynamic variable in (Select Component) "Data Source url" [Question] 

### ISSUE THREAD

**Issue by mohammadaaqib** [formio/angular-formio#657]
i want to pass dynamic path param in my URL like (https://vpic.nhtsa.dot.gov/api/vehicles/{{_makerId_}})
can i pass dynamic variable  **makerId** from my component

**Comment by travist** [comment]
You just need a component on your form called "makerId" (it can be a hidden field). Then, you will add the following for your URL.

```https://vpic.nhtsa.dot.gov/api/vehicles/{{data.makerId}}```

you will then need to ensure that this url component refreshes on the makerId component (there is a configuration for that)?

**Comment by mohammadaaqib** [comment]
> You just need a component on your form called "makerId" (it can be a hidden field). Then, you will add the following for your URL.
> 
> `https://vpic.nhtsa.dot.gov/api/vehicles/{{data.makerId}}`
> 
> you will then need to ensure that this url component refreshes on the makerId component (there is a configuration for that)?

thanks, @travist  for your reply. From component I mean my angular component. I want to pass makerId from my angular component In select URL
