### ISSUE TITLE
Question: Angular-formio vs formio.js

### ISSUE THREAD

**Issue by learner291** [formio/angular-formio#672]
I have a couple of quick questions regarding the two libraries. Does the angular-formio contain all the components that formio.js has? Is there any major differences between the two libraries apart from the platform?

**Comment by wag110894** [comment]
Hello @learner291,

Thanks for reaching out!

Angular-formio contains all that form.io has. As you can see in the changelogs, that formio.js is referenced in angular-formio. https://github.com/formio/angular-formio/blob/master/CHANGELOG.md
There are no major differences between the two libraries.

I hope that this helps.

Thanks.

**Comment by learner291** [comment]
Thanks
